

#ifndef CORE1_THREAD_CONFIG_H_
#define CORE1_THREAD_CONFIG_H_

#include "os_thread_type.h"
#include "core1_task_cfg.h"


#define	 CORE1_THREAD0_SWITCH	CORE1_TASK0_SWITCH
#define	 CORE1_THREAD1_SWITCH 	CORE1_TASK1_SWITCH
#define	 CORE1_THREAD2_SWITCH 	CORE1_TASK2_SWITCH
#define	 CORE1_THREAD3_SWITCH	CORE1_TASK3_SWITCH
#define	 CORE1_THREAD4_SWITCH	CORE1_TASK4_SWITCH
#define	 CORE1_THREAD5_SWITCH	CORE1_TASK5_SWITCH
#define	 CORE1_THREAD6_SWITCH	CORE1_TASK6_SWITCH
#define	 CORE1_THREAD7_SWITCH	CORE1_TASK7_SWITCH
#define	 CORE1_THREAD8_SWITCH	CORE1_TASK8_SWITCH
#define	 CORE1_THREAD9_SWITCH	CORE1_TASK9_SWITCH
#define	 CORE1_THREAD10_SWITCH	CORE1_TASK10_SWITCH
#define	 CORE1_THREAD11_SWITCH 	CORE1_TASK11_SWITCH
#define	 CORE1_THREAD12_SWITCH 	CORE1_TASK12_SWITCH
#define	 CORE1_THREAD13_SWITCH	CORE1_TASK13_SWITCH
#define	 CORE1_THREAD14_SWITCH	CORE1_TASK14_SWITCH
#define	 CORE1_THREAD15_SWITCH	CORE1_TASK15_SWITCH
#define	 CORE1_THREAD16_SWITCH	CORE1_TASK16_SWITCH
#define	 CORE1_THREAD17_SWITCH	CORE1_TASK17_SWITCH
#define	 CORE1_THREAD18_SWITCH	CORE1_TASK18_SWITCH
#define	 CORE1_THREAD19_SWITCH	CORE1_TASK19_SWITCH
#define	 CORE1_THREAD20_SWITCH	CORE1_TASK20_SWITCH
#define	 CORE1_THREAD21_SWITCH 	CORE1_TASK21_SWITCH
#define	 CORE1_THREAD22_SWITCH 	CORE1_TASK22_SWITCH
#define	 CORE1_THREAD23_SWITCH	CORE1_TASK23_SWITCH
#define	 CORE1_THREAD24_SWITCH	CORE1_TASK24_SWITCH
#define	 CORE1_THREAD25_SWITCH	CORE1_TASK25_SWITCH
#define	 CORE1_THREAD26_SWITCH	CORE1_TASK26_SWITCH
#define	 CORE1_THREAD27_SWITCH	CORE1_TASK27_SWITCH
#define	 CORE1_THREAD28_SWITCH	CORE1_TASK28_SWITCH
#define	 CORE1_THREAD29_SWITCH	CORE1_TASK29_SWITCH
#define	 CORE1_THREAD30_SWITCH	CORE1_TASK30_SWITCH
#define	 CORE1_THREAD31_SWITCH 	CORE1_TASK31_SWITCH
#define	 CORE1_THREAD32_SWITCH 	CORE1_TASK32_SWITCH
#define	 CORE1_THREAD33_SWITCH	CORE1_TASK33_SWITCH
#define	 CORE1_THREAD34_SWITCH	CORE1_TASK34_SWITCH
#define	 CORE1_THREAD35_SWITCH	CORE1_TASK35_SWITCH
#define	 CORE1_THREAD36_SWITCH	CORE1_TASK36_SWITCH
#define	 CORE1_THREAD37_SWITCH	CORE1_TASK37_SWITCH
#define	 CORE1_THREAD38_SWITCH	CORE1_TASK38_SWITCH
#define	 CORE1_THREAD39_SWITCH	CORE1_TASK39_SWITCH
#define	 CORE1_THREAD40_SWITCH	CORE1_TASK40_SWITCH
#define	 CORE1_THREAD41_SWITCH 	CORE1_TASK41_SWITCH
#define	 CORE1_THREAD42_SWITCH 	CORE1_TASK42_SWITCH
#define	 CORE1_THREAD43_SWITCH	CORE1_TASK43_SWITCH
#define	 CORE1_THREAD44_SWITCH	CORE1_TASK44_SWITCH
#define	 CORE1_THREAD45_SWITCH	CORE1_TASK45_SWITCH
#define	 CORE1_THREAD46_SWITCH	CORE1_TASK46_SWITCH
#define	 CORE1_THREAD47_SWITCH	CORE1_TASK47_SWITCH
#define	 CORE1_THREAD48_SWITCH	CORE1_TASK48_SWITCH
#define	 CORE1_THREAD49_SWITCH	CORE1_TASK49_SWITCH
#define	 CORE1_THREAD50_SWITCH	CORE1_TASK50_SWITCH
#define	 CORE1_THREAD51_SWITCH 	CORE1_TASK51_SWITCH
#define	 CORE1_THREAD52_SWITCH 	CORE1_TASK52_SWITCH
#define	 CORE1_THREAD53_SWITCH	CORE1_TASK53_SWITCH
#define	 CORE1_THREAD54_SWITCH	CORE1_TASK54_SWITCH
#define	 CORE1_THREAD55_SWITCH	CORE1_TASK55_SWITCH
#define	 CORE1_THREAD56_SWITCH	CORE1_TASK56_SWITCH
#define	 CORE1_THREAD57_SWITCH	CORE1_TASK57_SWITCH
#define	 CORE1_THREAD58_SWITCH	CORE1_TASK58_SWITCH
#define	 CORE1_THREAD59_SWITCH	CORE1_TASK59_SWITCH
#define	 CORE1_THREAD60_SWITCH	CORE1_TASK60_SWITCH
#define	 CORE1_THREAD61_SWITCH 	CORE1_TASK61_SWITCH
#define	 CORE1_THREAD62_SWITCH 	CORE1_TASK62_SWITCH
#define	 CORE1_THREAD63_SWITCH	CORE1_TASK63_SWITCH
#define	 CORE1_THREAD64_SWITCH	CORE1_TASK64_SWITCH
#define	 CORE1_THREAD65_SWITCH	CORE1_TASK65_SWITCH
#define	 CORE1_THREAD66_SWITCH	CORE1_TASK66_SWITCH
#define	 CORE1_THREAD67_SWITCH	CORE1_TASK67_SWITCH
#define	 CORE1_THREAD68_SWITCH	CORE1_TASK68_SWITCH
#define	 CORE1_THREAD69_SWITCH	CORE1_TASK69_SWITCH
#define	 CORE1_THREAD70_SWITCH	CORE1_TASK70_SWITCH
#define	 CORE1_THREAD71_SWITCH 	CORE1_TASK71_SWITCH
#define	 CORE1_THREAD72_SWITCH 	CORE1_TASK72_SWITCH
#define	 CORE1_THREAD73_SWITCH	CORE1_TASK73_SWITCH
#define	 CORE1_THREAD74_SWITCH	CORE1_TASK74_SWITCH
#define	 CORE1_THREAD75_SWITCH	CORE1_TASK75_SWITCH
#define	 CORE1_THREAD76_SWITCH	CORE1_TASK76_SWITCH
#define	 CORE1_THREAD77_SWITCH	CORE1_TASK77_SWITCH
#define	 CORE1_THREAD78_SWITCH	CORE1_TASK78_SWITCH
#define	 CORE1_THREAD79_SWITCH	CORE1_TASK79_SWITCH
#define	 CORE1_THREAD80_SWITCH	CORE1_TASK80_SWITCH
#define	 CORE1_THREAD81_SWITCH 	CORE1_TASK81_SWITCH
#define	 CORE1_THREAD82_SWITCH	CORE1_TASK82_SWITCH
#define	 CORE1_THREAD83_SWITCH	CORE1_TASK83_SWITCH
#define	 CORE1_THREAD84_SWITCH	CORE1_TASK84_SWITCH
#define	 CORE1_THREAD85_SWITCH	CORE1_TASK85_SWITCH
#define	 CORE1_THREAD86_SWITCH	CORE1_TASK86_SWITCH
#define	 CORE1_THREAD87_SWITCH	CORE1_TASK87_SWITCH
#define	 CORE1_THREAD88_SWITCH	CORE1_TASK88_SWITCH
#define	 CORE1_THREAD89_SWITCH	CORE1_TASK89_SWITCH
#define	 CORE1_THREAD90_SWITCH	CORE1_TASK90_SWITCH
#define	 CORE1_THREAD91_SWITCH 	CORE1_TASK91_SWITCH
#define	 CORE1_THREAD92_SWITCH 	CORE1_TASK92_SWITCH
#define	 CORE1_THREAD93_SWITCH	CORE1_TASK93_SWITCH
#define	 CORE1_THREAD94_SWITCH	CORE1_TASK94_SWITCH
#define	 CORE1_THREAD95_SWITCH	CORE1_TASK95_SWITCH
#define	 CORE1_THREAD96_SWITCH	CORE1_TASK96_SWITCH
#define	 CORE1_THREAD97_SWITCH	CORE1_TASK97_SWITCH
#define	 CORE1_THREAD98_SWITCH	CORE1_TASK98_SWITCH
#define	 CORE1_THREAD99_SWITCH	CORE1_TASK99_SWITCH
#define	 CORE1_THREAD100_SWITCH	CORE1_TASK100_SWITCH

#if (CORE1_THREAD0_SWITCH == ON) 
#define	 CORE1_THREAD_ID0    	 CORE1_TASK_ID0
#endif
#if (CORE1_THREAD1_SWITCH == ON)
#define	 CORE1_THREAD_ID1        CORE1_TASK_ID1
#endif
#if (CORE1_THREAD2_SWITCH == ON)
#define	 CORE1_THREAD_ID2		 CORE1_TASK_ID2
#endif
#if (CORE1_THREAD3_SWITCH == ON)
#define	 CORE1_THREAD_ID3		 CORE1_TASK_ID3
#endif
#if (CORE1_THREAD4_SWITCH == ON)
#define	 CORE1_THREAD_ID4		 CORE1_TASK_ID4
#endif
#if (CORE1_THREAD5_SWITCH == ON)
#define	 CORE1_THREAD_ID5		 CORE1_TASK_ID5
#endif
#if (CORE1_THREAD6_SWITCH == ON)
#define	 CORE1_THREAD_ID6		 CORE1_TASK_ID6
#endif
#if (CORE1_THREAD7_SWITCH == ON)
#define	 CORE1_THREAD_ID7		 CORE1_TASK_ID7
#endif
#if (CORE1_THREAD8_SWITCH == ON)
#define	 CORE1_THREAD_ID8		 CORE1_TASK_ID8
#endif
#if (CORE1_THREAD9_SWITCH == ON)
#define	 CORE1_THREAD_ID9		 CORE1_TASK_ID9
#endif
#if (CORE1_THREAD10_SWITCH == ON)
#define	 CORE1_THREAD_ID10		 CORE1_TASK_ID10
#endif
#if (CORE1_THREAD11_SWITCH == ON)
#define	 CORE1_THREAD_ID11		 CORE1_TASK_ID11
#endif
#if (CORE1_THREAD12_SWITCH == ON)
#define	 CORE1_THREAD_ID12		 CORE1_TASK_ID12
#endif
#if (CORE1_THREAD13_SWITCH == ON)
#define	 CORE1_THREAD_ID13		 CORE1_TASK_ID13
#endif
#if (CORE1_THREAD14_SWITCH == ON)
#define	 CORE1_THREAD_ID14		 CORE1_TASK_ID14
#endif
#if (CORE1_THREAD15_SWITCH == ON)
#define	 CORE1_THREAD_ID15		 CORE1_TASK_ID15
#endif
#if (CORE1_THREAD16_SWITCH == ON)
#define	 CORE1_THREAD_ID16		 CORE1_TASK_ID16
#endif
#if (CORE1_THREAD17_SWITCH == ON)
#define	 CORE1_THREAD_ID17		 CORE1_TASK_ID17
#endif
#if (CORE1_THREAD18_SWITCH == ON)
#define	 CORE1_THREAD_ID18		 CORE1_TASK_ID18
#endif
#if (CORE1_THREAD19_SWITCH == ON)
#define	 CORE1_THREAD_ID19		 CORE1_TASK_ID19
#endif
#if (CORE1_THREAD20_SWITCH == ON)
#define	 CORE1_THREAD_ID20		 CORE1_TASK_ID20
#endif
#if (CORE1_THREAD21_SWITCH == ON)
#define	 CORE1_THREAD_ID21		 CORE1_TASK_ID21
#endif
#if (CORE1_THREAD22_SWITCH == ON)
#define	 CORE1_THREAD_ID22		 CORE1_TASK_ID22
#endif
#if (CORE1_THREAD23_SWITCH == ON)
#define	 CORE1_THREAD_ID23		 CORE1_TASK_ID23
#endif
#if (CORE1_THREAD24_SWITCH == ON)
#define	 CORE1_THREAD_ID24		 CORE1_TASK_ID24
#endif
#if (CORE1_THREAD25_SWITCH == ON)
#define	 CORE1_THREAD_ID25		 CORE1_TASK_ID25
#endif
#if (CORE1_THREAD26_SWITCH == ON)
#define	 CORE1_THREAD_ID26		 CORE1_TASK_ID26
#endif
#if (CORE1_THREAD27_SWITCH == ON)
#define	 CORE1_THREAD_ID27		 CORE1_TASK_ID27
#endif
#if (CORE1_THREAD28_SWITCH == ON)
#define	 CORE1_THREAD_ID28		 CORE1_TASK_ID28
#endif
#if (CORE1_THREAD29_SWITCH == ON)
#define	 CORE1_THREAD_ID29		 CORE1_TASK_ID29
#endif
#if (CORE1_THREAD30_SWITCH == ON)
#define	 CORE1_THREAD_ID30		 CORE1_TASK_ID30
#endif
#if (CORE1_THREAD31_SWITCH == ON)
#define	 CORE1_THREAD_ID31		 CORE1_TASK_ID31
#endif
#if (CORE1_THREAD32_SWITCH == ON)
#define	 CORE1_THREAD_ID32		 CORE1_TASK_ID32
#endif
#if (CORE1_THREAD33_SWITCH == ON)
#define	 CORE1_THREAD_ID33		 CORE1_TASK_ID33
#endif
#if (CORE1_THREAD34_SWITCH == ON)
#define	 CORE1_THREAD_ID34		 CORE1_TASK_ID34
#endif
#if (CORE1_THREAD35_SWITCH == ON)
#define	 CORE1_THREAD_ID35		 CORE1_TASK_ID35
#endif
#if (CORE1_THREAD36_SWITCH == ON)
#define	 CORE1_THREAD_ID36		 CORE1_TASK_ID36
#endif
#if (CORE1_THREAD37_SWITCH == ON)
#define	 CORE1_THREAD_ID37		 CORE1_TASK_ID37
#endif
#if (CORE1_THREAD38_SWITCH == ON)
#define	 CORE1_THREAD_ID38		 CORE1_TASK_ID38
#endif
#if (CORE1_THREAD39_SWITCH == ON)
#define	 CORE1_THREAD_ID39		 CORE1_TASK_ID39
#endif
#if (CORE1_THREAD40_SWITCH == ON)
#define	 CORE1_THREAD_ID40		 CORE1_TASK_ID40
#endif
#if (CORE1_THREAD41_SWITCH == ON)
#define	 CORE1_THREAD_ID41		 CORE1_TASK_ID41
#endif
#if (CORE1_THREAD42_SWITCH == ON)
#define	 CORE1_THREAD_ID42		 CORE1_TASK_ID42
#endif
#if (CORE1_THREAD43_SWITCH == ON)
#define	 CORE1_THREAD_ID43		 CORE1_TASK_ID43
#endif
#if (CORE1_THREAD44_SWITCH == ON)
#define	 CORE1_THREAD_ID44		 CORE1_TASK_ID44
#endif
#if (CORE1_THREAD45_SWITCH == ON)
#define	 CORE1_THREAD_ID45		 CORE1_TASK_ID45
#endif
#if (CORE1_THREAD46_SWITCH == ON)
#define	 CORE1_THREAD_ID46		 CORE1_TASK_ID46
#endif
#if (CORE1_THREAD47_SWITCH == ON)
#define	 CORE1_THREAD_ID47		 CORE1_TASK_ID47
#endif
#if (CORE1_THREAD48_SWITCH == ON)
#define	 CORE1_THREAD_ID48		 CORE1_TASK_ID48
#endif
#if (CORE1_THREAD49_SWITCH == ON)
#define	 CORE1_THREAD_ID49		 CORE1_TASK_ID49
#endif
#if (CORE1_THREAD50_SWITCH == ON)
#define	 CORE1_THREAD_ID50		 CORE1_TASK_ID50
#endif
#if (CORE1_THREAD51_SWITCH == ON)
#define	 CORE1_THREAD_ID51		 CORE1_TASK_ID51
#endif
#if (CORE1_THREAD52_SWITCH == ON)
#define	 CORE1_THREAD_ID52		 CORE1_TASK_ID52
#endif
#if (CORE1_THREAD53_SWITCH == ON)
#define	 CORE1_THREAD_ID53		 CORE1_TASK_ID53
#endif
#if (CORE1_THREAD54_SWITCH == ON)
#define	 CORE1_THREAD_ID54		 CORE1_TASK_ID54
#endif
#if (CORE1_THREAD55_SWITCH == ON)
#define	 CORE1_THREAD_ID55		 CORE1_TASK_ID55
#endif
#if (CORE1_THREAD56_SWITCH == ON)
#define	 CORE1_THREAD_ID56		 CORE1_TASK_ID56
#endif
#if (CORE1_THREAD57_SWITCH == ON)
#define	 CORE1_THREAD_ID57		 CORE1_TASK_ID57
#endif
#if (CORE1_THREAD58_SWITCH == ON)
#define	 CORE1_THREAD_ID58		 CORE1_TASK_ID58
#endif
#if (CORE1_THREAD59_SWITCH == ON)
#define	 CORE1_THREAD_ID59		 CORE1_TASK_ID59
#endif
#if (CORE1_THREAD60_SWITCH == ON)
#define	 CORE1_THREAD_ID60		 CORE1_TASK_ID60
#endif
#if (CORE1_THREAD61_SWITCH == ON)
#define	 CORE1_THREAD_ID61		 CORE1_TASK_ID61
#endif
#if (CORE1_THREAD62_SWITCH == ON)
#define	 CORE1_THREAD_ID62		 CORE1_TASK_ID62
#endif
#if (CORE1_THREAD63_SWITCH == ON)
#define	 CORE1_THREAD_ID63		 CORE1_TASK_ID63
#endif
#if (CORE1_THREAD64_SWITCH == ON)
#define	 CORE1_THREAD_ID64		 CORE1_TASK_ID64
#endif
#if (CORE1_THREAD65_SWITCH == ON)
#define	 CORE1_THREAD_ID65		 CORE1_TASK_ID65
#endif
#if (CORE1_THREAD66_SWITCH == ON)
#define	 CORE1_THREAD_ID66		 CORE1_TASK_ID66
#endif
#if (CORE1_THREAD67_SWITCH == ON)
#define	 CORE1_THREAD_ID67		 CORE1_TASK_ID67
#endif
#if (CORE1_THREAD68_SWITCH == ON)
#define	 CORE1_THREAD_ID68		 CORE1_TASK_ID68
#endif
#if (CORE1_THREAD69_SWITCH == ON)
#define	 CORE1_THREAD_ID69		 CORE1_TASK_ID69
#endif
#if (CORE1_THREAD70_SWITCH == ON)
#define	 CORE1_THREAD_ID70		 CORE1_TASK_ID70
#endif
#if (CORE1_THREAD71_SWITCH == ON)
#define	 CORE1_THREAD_ID71		 CORE1_TASK_ID71
#endif
#if (CORE1_THREAD72_SWITCH == ON)
#define	 CORE1_THREAD_ID72		 CORE1_TASK_ID72
#endif
#if (CORE1_THREAD73_SWITCH == ON)
#define	 CORE1_THREAD_ID73		 CORE1_TASK_ID73
#endif
#if (CORE1_THREAD74_SWITCH == ON)
#define	 CORE1_THREAD_ID74		 CORE1_TASK_ID74
#endif
#if (CORE1_THREAD75_SWITCH == ON)
#define	 CORE1_THREAD_ID75		 CORE1_TASK_ID75
#endif
#if (CORE1_THREAD76_SWITCH == ON)
#define	 CORE1_THREAD_ID76		 CORE1_TASK_ID76
#endif
#if (CORE1_THREAD77_SWITCH == ON)
#define	 CORE1_THREAD_ID77		 CORE1_TASK_ID77
#endif
#if (CORE1_THREAD78_SWITCH == ON)
#define	 CORE1_THREAD_ID78		 CORE1_TASK_ID78
#endif
#if (CORE1_THREAD79_SWITCH == ON)
#define	 CORE1_THREAD_ID79		 CORE1_TASK_ID79
#endif
#if (CORE1_THREAD80_SWITCH == ON)
#define	 CORE1_THREAD_ID80		 CORE1_TASK_ID80
#endif
#if (CORE1_THREAD81_SWITCH == ON)
#define	 CORE1_THREAD_ID81		 CORE1_TASK_ID81
#endif
#if (CORE1_THREAD82_SWITCH == ON)
#define	 CORE1_THREAD_ID82		 CORE1_TASK_ID82
#endif
#if (CORE1_THREAD83_SWITCH == ON)
#define	 CORE1_THREAD_ID83		 CORE1_TASK_ID83
#endif
#if (CORE1_THREAD84_SWITCH == ON)
#define	 CORE1_THREAD_ID84		 CORE1_TASK_ID84
#endif
#if (CORE1_THREAD85_SWITCH == ON)
#define	 CORE1_THREAD_ID85		 CORE1_TASK_ID85
#endif
#if (CORE1_THREAD86_SWITCH == ON)
#define	 CORE1_THREAD_ID86		 CORE1_TASK_ID86
#endif
#if (CORE1_THREAD87_SWITCH == ON)
#define	 CORE1_THREAD_ID87		 CORE1_TASK_ID87
#endif
#if (CORE1_THREAD88_SWITCH == ON)
#define	 CORE1_THREAD_ID88		 CORE1_TASK_ID88
#endif
#if (CORE1_THREAD89_SWITCH == ON)
#define	 CORE1_THREAD_ID89		 CORE1_TASK_ID89
#endif
#if (CORE1_THREAD90_SWITCH == ON)
#define	 CORE1_THREAD_ID90		 CORE1_TASK_ID90
#endif
#if (CORE1_THREAD91_SWITCH == ON)
#define	 CORE1_THREAD_ID91		 CORE1_TASK_ID91
#endif
#if (CORE1_THREAD92_SWITCH == ON)
#define	 CORE1_THREAD_ID92		 CORE1_TASK_ID92
#endif
#if (CORE1_THREAD93_SWITCH == ON)
#define	 CORE1_THREAD_ID93		 CORE1_TASK_ID93
#endif
#if (CORE1_THREAD94_SWITCH == ON)
#define	 CORE1_THREAD_ID94		 CORE1_TASK_ID94
#endif
#if (CORE1_THREAD95_SWITCH == ON)
#define	 CORE1_THREAD_ID95		 CORE1_TASK_ID95
#endif
#if (CORE1_THREAD96_SWITCH == ON)
#define	 CORE1_THREAD_ID96		 CORE1_TASK_ID96
#endif
#if (CORE1_THREAD97_SWITCH == ON)
#define	 CORE1_THREAD_ID97		 CORE1_TASK_ID97
#endif
#if (CORE1_THREAD98_SWITCH == ON)
#define	 CORE1_THREAD_ID98		 CORE1_TASK_ID98
#endif
#if (CORE1_THREAD99_SWITCH == ON)
#define	 CORE1_THREAD_ID99		 CORE1_TASK_ID99
#endif
#if (CORE1_THREAD100_SWITCH == ON)
#define	 CORE1_THREAD_ID100		 CORE1_TASK_ID100
#endif
#define	 CORE1_THREAD_MAX_ID_NUM CORE1_TASK_MAX_ID_NUM


/* core 1*/
/* 1 thread config initialization */ 

#if (CORE1_THREAD0_SWITCH == ON) 
#define CORE1_THREAD0_TYPE             CORE1_TASK0_TYPE             
#define CORE1_THREAD0_PERIOD           CORE1_TASK0_PERIOD
#define CORE1_THREAD0_ACTIVED          CORE1_TASK0_ACTIVED
#define CORE1_THREAD0_ACTIVED_COREID   CORE1_TASK0_ACTIVED_COREID
#define CORE1_THREAD0_PRIORITY         CORE1_TASK0_PRIORITY
#define CORE1_THREAD0_MODE             CORE1_TASK0_MODE
#define CORE1_THREAD0_STACK_SIZE       CORE1_TASK0_STACK_SIZE
#define CORE1_THREAD0_CALL_DEPTH       CORE1_TASK0_CALL_DEPTH 
#endif
#if (CORE1_THREAD1_SWITCH == ON)
#define CORE1_THREAD1_TYPE             CORE1_TASK1_TYPE             
#define CORE1_THREAD1_PERIOD           CORE1_TASK1_PERIOD
#define CORE1_THREAD1_ACTIVED          CORE1_TASK1_ACTIVED
#define CORE1_THREAD1_ACTIVED_COREID   CORE1_TASK1_ACTIVED_COREID
#define CORE1_THREAD1_PRIORITY         CORE1_TASK1_PRIORITY
#define CORE1_THREAD1_MODE             CORE1_TASK1_MODE
#define CORE1_THREAD1_STACK_SIZE       CORE1_TASK1_STACK_SIZE
#define CORE1_THREAD1_CALL_DEPTH       CORE1_TASK1_CALL_DEPTH  
#endif
#if (CORE1_THREAD2_SWITCH == ON)
#define CORE1_THREAD2_TYPE             CORE1_TASK2_TYPE             
#define CORE1_THREAD2_PERIOD           CORE1_TASK2_PERIOD
#define CORE1_THREAD2_ACTIVED          CORE1_TASK2_ACTIVED
#define CORE1_THREAD2_ACTIVED_COREID   CORE1_TASK3_ACTIVED_COREID
#define CORE1_THREAD2_PRIORITY         CORE1_TASK2_PRIORITY
#define CORE1_THREAD2_MODE             CORE1_TASK2_MODE
#define CORE1_THREAD2_STACK_SIZE       CORE1_TASK2_STACK_SIZE
#define CORE1_THREAD2_CALL_DEPTH       CORE1_TASK2_CALL_DEPTH 
#endif
#if (CORE1_THREAD3_SWITCH == ON)
#define CORE1_THREAD3_TYPE             CORE1_TASK3_TYPE             
#define CORE1_THREAD3_PERIOD           CORE1_TASK3_PERIOD
#define CORE1_THREAD3_ACTIVED          CORE1_TASK3_ACTIVED
#define CORE1_THREAD3_ACTIVED_COREID   CORE1_TASK3_ACTIVED_COREID
#define CORE1_THREAD3_PRIORITY         CORE1_TASK3_PRIORITY
#define CORE1_THREAD3_MODE             CORE1_TASK3_MODE
#define CORE1_THREAD3_STACK_SIZE       CORE1_TASK3_STACK_SIZE
#define CORE1_THREAD3_CALL_DEPTH       CORE1_TASK3_CALL_DEPTH 
#endif
#if (CORE1_THREAD4_SWITCH == ON)
#define CORE1_THREAD4_TYPE             CORE1_TASK4_TYPE             
#define CORE1_THREAD4_PERIOD           CORE1_TASK4_PERIOD
#define CORE1_THREAD4_ACTIVED          CORE1_TASK4_ACTIVED
#define CORE1_THREAD4_ACTIVED_COREID   CORE1_TASK4_ACTIVED_COREID
#define CORE1_THREAD4_PRIORITY         CORE1_TASK4_PRIORITY
#define CORE1_THREAD4_MODE             CORE1_TASK4_MODE
#define CORE1_THREAD4_STACK_SIZE       CORE1_TASK4_STACK_SIZE
#define CORE1_THREAD4_CALL_DEPTH       CORE1_TASK4_CALL_DEPTH 
#endif
#if (CORE1_THREAD5_SWITCH == ON)
#define CORE1_THREAD5_TYPE             CORE1_TASK5_TYPE             
#define CORE1_THREAD5_PERIOD           CORE1_TASK5_PERIOD
#define CORE1_THREAD5_ACTIVED          CORE1_TASK5_ACTIVED
#define CORE1_THREAD5_ACTIVED_COREID   CORE1_TASK5_ACTIVED_COREID
#define CORE1_THREAD5_PRIORITY         CORE1_TASK5_PRIORITY
#define CORE1_THREAD5_MODE             CORE1_TASK5_MODE
#define CORE1_THREAD5_STACK_SIZE       CORE1_TASK5_STACK_SIZE
#define CORE1_THREAD5_CALL_DEPTH       CORE1_TASK5_CALL_DEPTH 
#endif
#if (CORE1_THREAD6_SWITCH == ON)
#define CORE1_THREAD6_TYPE             CORE1_TASK6_TYPE             
#define CORE1_THREAD6_PERIOD           CORE1_TASK6_PERIOD
#define CORE1_THREAD6_ACTIVED          CORE1_TASK6_ACTIVED
#define CORE1_THREAD6_ACTIVED_COREID   CORE1_TASK6_ACTIVED_COREID
#define CORE1_THREAD6_PRIORITY         CORE1_TASK6_PRIORITY
#define CORE1_THREAD6_MODE             CORE1_TASK6_MODE
#define CORE1_THREAD6_STACK_SIZE       CORE1_TASK6_STACK_SIZE
#define CORE1_THREAD6_CALL_DEPTH       CORE1_TASK6_CALL_DEPTH 
#endif
#if (CORE1_THREAD7_SWITCH == ON)
#define CORE1_THREAD7_TYPE             CORE1_TASK7_TYPE             
#define CORE1_THREAD7_PERIOD           CORE1_TASK7_PERIOD
#define CORE1_THREAD7_ACTIVED          CORE1_TASK7_ACTIVED
#define CORE1_THREAD7_ACTIVED_COREID   CORE1_TASK7_ACTIVED_COREID
#define CORE1_THREAD7_PRIORITY         CORE1_TASK7_PRIORITY
#define CORE1_THREAD7_MODE             CORE1_TASK7_MODE
#define CORE1_THREAD7_STACK_SIZE       CORE1_TASK7_STACK_SIZE
#define CORE1_THREAD7_CALL_DEPTH       CORE1_TASK7_CALL_DEPTH
#endif
#if (CORE1_THREAD8_SWITCH == ON)
#define CORE1_THREAD8_TYPE             CORE1_TASK8_TYPE             
#define CORE1_THREAD8_PERIOD           CORE1_TASK8_PERIOD
#define CORE1_THREAD8_ACTIVED          CORE1_TASK8_ACTIVED
#define CORE1_THREAD8_ACTIVED_COREID   CORE1_TASK8_ACTIVED_COREID
#define CORE1_THREAD8_PRIORITY         CORE1_TASK8_PRIORITY
#define CORE1_THREAD8_MODE             CORE1_TASK8_MODE
#define CORE1_THREAD8_STACK_SIZE       CORE1_TASK8_STACK_SIZE
#define CORE1_THREAD8_CALL_DEPTH       CORE1_TASK8_CALL_DEPTH
#endif
#if (CORE1_THREAD9_SWITCH == ON)
#define CORE1_THREAD9_TYPE             CORE1_TASK9_TYPE             
#define CORE1_THREAD9_PERIOD           CORE1_TASK9_PERIOD
#define CORE1_THREAD9_ACTIVED          CORE1_TASK9_ACTIVED
#define CORE1_THREAD9_ACTIVED_COREID   CORE1_TASK9_ACTIVED_COREID
#define CORE1_THREAD9_PRIORITY         CORE1_TASK9_PRIORITY
#define CORE1_THREAD9_MODE             CORE1_TASK9_MODE
#define CORE1_THREAD9_STACK_SIZE       CORE1_TASK9_STACK_SIZE
#define CORE1_THREAD9_CALL_DEPTH       CORE1_TASK9_CALL_DEPTH
#endif
#if (CORE1_THREAD10_SWITCH == ON)
#define CORE1_THREAD10_TYPE            CORE1_TASK10_TYPE             
#define CORE1_THREAD10_PERIOD          CORE1_TASK10_PERIOD
#define CORE1_THREAD10_ACTIVED         CORE1_TASK10_ACTIVED
#define CORE1_THREAD10_ACTIVED_COREID  CORE1_TASK10_ACTIVED_COREID
#define CORE1_THREAD10_PRIORITY        CORE1_TASK10_PRIORITY
#define CORE1_THREAD10_MODE            CORE1_TASK10_MODE
#define CORE1_THREAD10_STACK_SIZE      CORE1_TASK10_STACK_SIZE
#define CORE1_THREAD10_CALL_DEPTH      CORE1_TASK10_CALL_DEPTH
#endif
#if (CORE1_THREAD11_SWITCH == ON)
#define CORE1_THREAD11_TYPE            CORE1_TASK11_TYPE             
#define CORE1_THREAD11_PERIOD          CORE1_TASK11_PERIOD
#define CORE1_THREAD11_ACTIVED         CORE1_TASK11_ACTIVED
#define CORE1_THREAD11_ACTIVED_COREID  CORE1_TASK11_ACTIVED_COREID
#define CORE1_THREAD11_PRIORITY        CORE1_TASK11_PRIORITY
#define CORE1_THREAD11_MODE            CORE1_TASK11_MODE
#define CORE1_THREAD11_STACK_SIZE      CORE1_TASK11_STACK_SIZE
#define CORE1_THREAD11_CALL_DEPTH      CORE1_TASK11_CALL_DEPTH  
#endif
#if (CORE1_THREAD12_SWITCH == ON)
#define CORE1_THREAD12_TYPE            CORE1_TASK12_TYPE             
#define CORE1_THREAD12_PERIOD          CORE1_TASK12_PERIOD
#define CORE1_THREAD12_ACTIVED         CORE1_TASK12_ACTIVED
#define CORE1_THREAD12_ACTIVED_COREID  CORE1_TASK12_ACTIVED_COREID
#define CORE1_THREAD12_PRIORITY        CORE1_TASK12_PRIORITY
#define CORE1_THREAD12_MODE            CORE1_TASK12_MODE
#define CORE1_THREAD12_STACK_SIZE      CORE1_TASK12_STACK_SIZE
#define CORE1_THREAD12_CALL_DEPTH      CORE1_TASK12_CALL_DEPTH 
#endif
#if (CORE1_THREAD13_SWITCH == ON)
#define CORE1_THREAD13_TYPE            CORE1_TASK13_TYPE             
#define CORE1_THREAD13_PERIOD          CORE1_TASK13_PERIOD
#define CORE1_THREAD13_ACTIVED         CORE1_TASK13_ACTIVED
#define CORE1_THREAD13_ACTIVED_COREID  CORE1_TASK13_ACTIVED_COREID
#define CORE1_THREAD13_PRIORITY        CORE1_TASK13_PRIORITY
#define CORE1_THREAD13_MODE            CORE1_TASK13_MODE
#define CORE1_THREAD13_STACK_SIZE      CORE1_TASK13_STACK_SIZE
#define CORE1_THREAD13_CALL_DEPTH      CORE1_TASK13_CALL_DEPTH 
#endif
#if (CORE1_THREAD14_SWITCH == ON)
#define CORE1_THREAD14_TYPE            CORE1_TASK14_TYPE             
#define CORE1_THREAD14_PERIOD          CORE1_TASK14_PERIOD
#define CORE1_THREAD14_ACTIVED         CORE1_TASK14_ACTIVED
#define CORE1_THREAD14_ACTIVED_COREID  CORE1_TASK14_ACTIVED_COREID
#define CORE1_THREAD14_PRIORITY        CORE1_TASK14_PRIORITY
#define CORE1_THREAD14_MODE            CORE1_TASK14_MODE
#define CORE1_THREAD14_STACK_SIZE      CORE1_TASK14_STACK_SIZE
#define CORE1_THREAD14_CALL_DEPTH      CORE1_TASK14_CALL_DEPTH 
#endif
#if (CORE1_THREAD15_SWITCH == ON)
#define CORE1_THREAD15_TYPE            CORE1_TASK15_TYPE             
#define CORE1_THREAD15_PERIOD          CORE1_TASK15_PERIOD
#define CORE1_THREAD15_ACTIVED         CORE1_TASK15_ACTIVED
#define CORE1_THREAD15_ACTIVED_COREID  CORE1_TASK15_ACTIVED_COREID
#define CORE1_THREAD15_PRIORITY        CORE1_TASK15_PRIORITY
#define CORE1_THREAD15_MODE            CORE1_TASK15_MODE
#define CORE1_THREAD15_STACK_SIZE      CORE1_TASK15_STACK_SIZE
#define CORE1_THREAD15_CALL_DEPTH      CORE1_TASK15_CALL_DEPTH 
#endif
#if (CORE1_THREAD16_SWITCH == ON)
#define CORE1_THREAD16_TYPE            CORE1_TASK16_TYPE             
#define CORE1_THREAD16_PERIOD          CORE1_TASK16_PERIOD
#define CORE1_THREAD16_ACTIVED         CORE1_TASK16_ACTIVED
#define CORE1_THREAD16_ACTIVED_COREID  CORE1_TASK16_ACTIVED_COREID
#define CORE1_THREAD16_PRIORITY        CORE1_TASK16_PRIORITY
#define CORE1_THREAD16_MODE            CORE1_TASK16_MODE
#define CORE1_THREAD16_STACK_SIZE      CORE1_TASK16_STACK_SIZE
#define CORE1_THREAD16_CALL_DEPTH      CORE1_TASK16_CALL_DEPTH 
#endif
#if (CORE1_THREAD17_SWITCH == ON)
#define CORE1_THREAD17_TYPE            CORE1_TASK17_TYPE             
#define CORE1_THREAD17_PERIOD          CORE1_TASK17_PERIOD
#define CORE1_THREAD17_ACTIVED         CORE1_TASK17_ACTIVED
#define CORE1_THREAD17_ACTIVED_COREID  CORE1_TASK17_ACTIVED_COREID
#define CORE1_THREAD17_PRIORITY        CORE1_TASK17_PRIORITY
#define CORE1_THREAD17_MODE            CORE1_TASK17_MODE
#define CORE1_THREAD17_STACK_SIZE      CORE1_TASK17_STACK_SIZE
#define CORE1_THREAD17_CALL_DEPTH      CORE1_TASK17_CALL_DEPTH
#endif
#if (CORE1_THREAD18_SWITCH == ON)
#define CORE1_THREAD18_TYPE            CORE1_TASK18_TYPE             
#define CORE1_THREAD18_PERIOD          CORE1_TASK18_PERIOD
#define CORE1_THREAD18_ACTIVED         CORE1_TASK18_ACTIVED
#define CORE1_THREAD18_ACTIVED_COREID  CORE1_TASK18_ACTIVED_COREID
#define CORE1_THREAD18_PRIORITY        CORE1_TASK18_PRIORITY
#define CORE1_THREAD18_MODE            CORE1_TASK18_MODE
#define CORE1_THREAD18_STACK_SIZE      CORE1_TASK18_STACK_SIZE
#define CORE1_THREAD18_CALL_DEPTH      CORE1_TASK18_CALL_DEPTH
#endif
#if (CORE1_THREAD19_SWITCH == ON)
#define CORE1_THREAD19_TYPE            CORE1_TASK19_TYPE             
#define CORE1_THREAD19_PERIOD          CORE1_TASK19_PERIOD
#define CORE1_THREAD19_ACTIVED         CORE1_TASK19_ACTIVED
#define CORE1_THREAD19_ACTIVED_COREID  CORE1_TASK19_ACTIVED_COREID
#define CORE1_THREAD19_PRIORITY        CORE1_TASK19_PRIORITY
#define CORE1_THREAD19_MODE            CORE1_TASK19_MODE
#define CORE1_THREAD19_STACK_SIZE      CORE1_TASK19_STACK_SIZE
#define CORE1_THREAD19_CALL_DEPTH      CORE1_TASK19_CALL_DEPTH
#endif
#if (CORE1_THREAD20_SWITCH == ON)
#define CORE1_THREAD20_TYPE            CORE1_TASK20_TYPE             
#define CORE1_THREAD20_PERIOD          CORE1_TASK20_PERIOD
#define CORE1_THREAD20_ACTIVED         CORE1_TASK20_ACTIVED
#define CORE1_THREAD20_ACTIVED_COREID  CORE1_TASK20_ACTIVED_COREID
#define CORE1_THREAD20_PRIORITY        CORE1_TASK20_PRIORITY
#define CORE1_THREAD20_MODE            CORE1_TASK20_MODE
#define CORE1_THREAD20_STACK_SIZE      CORE1_TASK20_STACK_SIZE
#define CORE1_THREAD20_CALL_DEPTH      CORE1_TASK20_CALL_DEPTH
#endif
#if (CORE1_THREAD21_SWITCH == ON)
#define CORE1_THREAD21_TYPE            CORE1_TASK21_TYPE             
#define CORE1_THREAD21_PERIOD          CORE1_TASK21_PERIOD
#define CORE1_THREAD21_ACTIVED         CORE1_TASK21_ACTIVED
#define CORE1_THREAD21_ACTIVED_COREID  CORE1_TASK21_ACTIVED_COREID
#define CORE1_THREAD21_PRIORITY        CORE1_TASK21_PRIORITY
#define CORE1_THREAD21_MODE            CORE1_TASK21_MODE
#define CORE1_THREAD21_STACK_SIZE      CORE1_TASK21_STACK_SIZE
#define CORE1_THREAD21_CALL_DEPTH      CORE1_TASK21_CALL_DEPTH  
#endif
#if (CORE1_THREAD22_SWITCH == ON)
#define CORE1_THREAD22_TYPE            CORE1_TASK22_TYPE             
#define CORE1_THREAD22_PERIOD          CORE1_TASK22_PERIOD
#define CORE1_THREAD22_ACTIVED         CORE1_TASK22_ACTIVED
#define CORE1_THREAD22_ACTIVED_COREID  CORE1_TASK22_ACTIVED_COREID
#define CORE1_THREAD22_PRIORITY        CORE1_TASK22_PRIORITY
#define CORE1_THREAD22_MODE            CORE1_TASK22_MODE
#define CORE1_THREAD22_STACK_SIZE      CORE1_TASK22_STACK_SIZE
#define CORE1_THREAD22_CALL_DEPTH      CORE1_TASK22_CALL_DEPTH 
#endif
#if (CORE1_THREAD23_SWITCH == ON)
#define CORE1_THREAD23_TYPE            CORE1_TASK23_TYPE             
#define CORE1_THREAD23_PERIOD          CORE1_TASK23_PERIOD
#define CORE1_THREAD23_ACTIVED         CORE1_TASK23_ACTIVED
#define CORE1_THREAD23_ACTIVED_COREID  CORE1_TASK23_ACTIVED_COREID
#define CORE1_THREAD23_PRIORITY        CORE1_TASK23_PRIORITY
#define CORE1_THREAD23_MODE            CORE1_TASK23_MODE
#define CORE1_THREAD23_STACK_SIZE      CORE1_TASK23_STACK_SIZE
#define CORE1_THREAD23_CALL_DEPTH      CORE1_TASK23_CALL_DEPTH 
#endif
#if (CORE1_THREAD24_SWITCH == ON)
#define CORE1_THREAD24_TYPE            CORE1_TASK24_TYPE             
#define CORE1_THREAD24_PERIOD          CORE1_TASK24_PERIOD
#define CORE1_THREAD24_ACTIVED         CORE1_TASK24_ACTIVED
#define CORE1_THREAD24_ACTIVED_COREID  CORE1_TASK24_ACTIVED_COREID
#define CORE1_THREAD24_PRIORITY        CORE1_TASK24_PRIORITY
#define CORE1_THREAD24_MODE            CORE1_TASK24_MODE
#define CORE1_THREAD24_STACK_SIZE      CORE1_TASK24_STACK_SIZE
#define CORE1_THREAD24_CALL_DEPTH      CORE1_TASK24_CALL_DEPTH 
#endif
#if (CORE1_THREAD25_SWITCH == ON)
#define CORE1_THREAD25_TYPE            CORE1_TASK25_TYPE             
#define CORE1_THREAD25_PERIOD          CORE1_TASK25_PERIOD
#define CORE1_THREAD25_ACTIVED         CORE1_TASK25_ACTIVED
#define CORE1_THREAD25_ACTIVED_COREID  CORE1_TASK25_ACTIVED_COREID
#define CORE1_THREAD25_PRIORITY        CORE1_TASK25_PRIORITY
#define CORE1_THREAD25_MODE            CORE1_TASK25_MODE
#define CORE1_THREAD25_STACK_SIZE      CORE1_TASK25_STACK_SIZE
#define CORE1_THREAD25_CALL_DEPTH      CORE1_TASK25_CALL_DEPTH 
#endif
#if (CORE1_THREAD26_SWITCH == ON)
#define CORE1_THREAD26_TYPE            CORE1_TASK26_TYPE             
#define CORE1_THREAD26_PERIOD          CORE1_TASK26_PERIOD
#define CORE1_THREAD26_ACTIVED         CORE1_TASK26_ACTIVED
#define CORE1_THREAD26_ACTIVED_COREID  CORE1_TASK26_ACTIVED_COREID
#define CORE1_THREAD26_PRIORITY        CORE1_TASK26_PRIORITY
#define CORE1_THREAD26_MODE            CORE1_TASK26_MODE
#define CORE1_THREAD26_STACK_SIZE      CORE1_TASK26_STACK_SIZE
#define CORE1_THREAD26_CALL_DEPTH      CORE1_TASK26_CALL_DEPTH 
#endif
#if (CORE1_THREAD27_SWITCH == ON)
#define CORE1_THREAD27_TYPE            CORE1_TASK27_TYPE             
#define CORE1_THREAD27_PERIOD          CORE1_TASK27_PERIOD
#define CORE1_THREAD27_ACTIVED         CORE1_TASK27_ACTIVED
#define CORE1_THREAD27_ACTIVED_COREID  CORE1_TASK27_ACTIVED_COREID
#define CORE1_THREAD27_PRIORITY        CORE1_TASK27_PRIORITY
#define CORE1_THREAD27_MODE            CORE1_TASK27_MODE
#define CORE1_THREAD27_STACK_SIZE      CORE1_TASK27_STACK_SIZE
#define CORE1_THREAD27_CALL_DEPTH      CORE1_TASK27_CALL_DEPTH
#endif
#if (CORE1_THREAD28_SWITCH == ON)
#define CORE1_THREAD28_TYPE            CORE1_TASK28_TYPE             
#define CORE1_THREAD28_PERIOD          CORE1_TASK28_PERIOD
#define CORE1_THREAD28_ACTIVED         CORE1_TASK28_ACTIVED
#define CORE1_THREAD28_ACTIVED_COREID  CORE1_TASK28_ACTIVED_COREID
#define CORE1_THREAD28_PRIORITY        CORE1_TASK28_PRIORITY
#define CORE1_THREAD28_MODE            CORE1_TASK28_MODE
#define CORE1_THREAD28_STACK_SIZE      CORE1_TASK28_STACK_SIZE
#define CORE1_THREAD28_CALL_DEPTH      CORE1_TASK28_CALL_DEPTH
#endif
#if (CORE1_THREAD29_SWITCH == ON)
#define CORE1_THREAD29_TYPE            CORE1_TASK29_TYPE             
#define CORE1_THREAD29_PERIOD          CORE1_TASK29_PERIOD
#define CORE1_THREAD29_ACTIVED         CORE1_TASK29_ACTIVED
#define CORE1_THREAD29_ACTIVED_COREID  CORE1_TASK29_ACTIVED_COREID
#define CORE1_THREAD29_PRIORITY        CORE1_TASK29_PRIORITY
#define CORE1_THREAD29_MODE            CORE1_TASK29_MODE
#define CORE1_THREAD29_STACK_SIZE      CORE1_TASK29_STACK_SIZE
#define CORE1_THREAD29_CALL_DEPTH      CORE1_TASK29_CALL_DEPTH
#endif
#if (CORE1_THREAD30_SWITCH == ON)
#define CORE1_THREAD30_TYPE            CORE1_TASK30_TYPE             
#define CORE1_THREAD30_PERIOD          CORE1_TASK30_PERIOD
#define CORE1_THREAD30_ACTIVED         CORE1_TASK30_ACTIVED
#define CORE1_THREAD30_ACTIVED_COREID  CORE1_TASK30_ACTIVED_COREID
#define CORE1_THREAD30_PRIORITY        CORE1_TASK30_PRIORITY
#define CORE1_THREAD30_MODE            CORE1_TASK30_MODE
#define CORE1_THREAD30_STACK_SIZE      CORE1_TASK30_STACK_SIZE
#define CORE1_THREAD30_CALL_DEPTH      CORE1_TASK30_CALL_DEPTH
#endif
#if (CORE1_THREAD31_SWITCH == ON)
#define CORE1_THREAD31_TYPE            CORE1_TASK31_TYPE             
#define CORE1_THREAD31_PERIOD          CORE1_TASK31_PERIOD
#define CORE1_THREAD31_ACTIVED         CORE1_TASK31_ACTIVED
#define CORE1_THREAD31_ACTIVED_COREID  CORE1_TASK31_ACTIVED_COREID
#define CORE1_THREAD31_PRIORITY        CORE1_TASK31_PRIORITY
#define CORE1_THREAD31_MODE            CORE1_TASK31_MODE
#define CORE1_THREAD31_STACK_SIZE      CORE1_TASK31_STACK_SIZE
#define CORE1_THREAD31_CALL_DEPTH      CORE1_TASK31_CALL_DEPTH  
#endif
#if (CORE1_THREAD32_SWITCH == ON)
#define CORE1_THREAD32_TYPE            CORE1_TASK32_TYPE             
#define CORE1_THREAD32_PERIOD          CORE1_TASK32_PERIOD
#define CORE1_THREAD32_ACTIVED         CORE1_TASK32_ACTIVED
#define CORE1_THREAD32_ACTIVED_COREID  CORE1_TASK32_ACTIVED_COREID
#define CORE1_THREAD32_PRIORITY        CORE1_TASK32_PRIORITY
#define CORE1_THREAD32_MODE            CORE1_TASK32_MODE
#define CORE1_THREAD32_STACK_SIZE      CORE1_TASK32_STACK_SIZE
#define CORE1_THREAD32_CALL_DEPTH      CORE1_TASK32_CALL_DEPTH 
#endif
#if (CORE1_THREAD33_SWITCH == ON)
#define CORE1_THREAD33_TYPE            CORE1_TASK33_TYPE             
#define CORE1_THREAD33_PERIOD          CORE1_TASK33_PERIOD
#define CORE1_THREAD33_ACTIVED         CORE1_TASK33_ACTIVED
#define CORE1_THREAD33_ACTIVED_COREID  CORE1_TASK33_ACTIVED_COREID
#define CORE1_THREAD33_PRIORITY        CORE1_TASK33_PRIORITY
#define CORE1_THREAD33_MODE            CORE1_TASK33_MODE
#define CORE1_THREAD33_STACK_SIZE      CORE1_TASK33_STACK_SIZE
#define CORE1_THREAD33_CALL_DEPTH      CORE1_TASK33_CALL_DEPTH 
#endif
#if (CORE1_THREAD34_SWITCH == ON)
#define CORE1_THREAD34_TYPE            CORE1_TASK34_TYPE             
#define CORE1_THREAD34_PERIOD          CORE1_TASK34_PERIOD
#define CORE1_THREAD34_ACTIVED         CORE1_TASK34_ACTIVED
#define CORE1_THREAD34_ACTIVED_COREID  CORE1_TASK34_ACTIVED_COREID
#define CORE1_THREAD34_PRIORITY        CORE1_TASK34_PRIORITY
#define CORE1_THREAD34_MODE            CORE1_TASK34_MODE
#define CORE1_THREAD34_STACK_SIZE      CORE1_TASK34_STACK_SIZE
#define CORE1_THREAD34_CALL_DEPTH      CORE1_TASK34_CALL_DEPTH 
#endif
#if (CORE1_THREAD35_SWITCH == ON)
#define CORE1_THREAD35_TYPE            CORE1_TASK35_TYPE             
#define CORE1_THREAD35_PERIOD          CORE1_TASK35_PERIOD
#define CORE1_THREAD35_ACTIVED         CORE1_TASK35_ACTIVED
#define CORE1_THREAD35_ACTIVED_COREID  CORE1_TASK35_ACTIVED_COREID
#define CORE1_THREAD35_PRIORITY        CORE1_TASK35_PRIORITY
#define CORE1_THREAD35_MODE            CORE1_TASK35_MODE
#define CORE1_THREAD35_STACK_SIZE      CORE1_TASK35_STACK_SIZE
#define CORE1_THREAD35_CALL_DEPTH      CORE1_TASK35_CALL_DEPTH 
#endif
#if (CORE1_THREAD36_SWITCH == ON)
#define CORE1_THREAD36_TYPE            CORE1_TASK36_TYPE             
#define CORE1_THREAD36_PERIOD          CORE1_TASK36_PERIOD
#define CORE1_THREAD36_ACTIVED         CORE1_TASK36_ACTIVED
#define CORE1_THREAD36_ACTIVED_COREID  CORE1_TASK36_ACTIVED_COREID
#define CORE1_THREAD36_PRIORITY        CORE1_TASK36_PRIORITY
#define CORE1_THREAD36_MODE            CORE1_TASK36_MODE
#define CORE1_THREAD36_STACK_SIZE      CORE1_TASK36_STACK_SIZE
#define CORE1_THREAD36_CALL_DEPTH      CORE1_TASK36_CALL_DEPTH 
#endif
#if (CORE1_THREAD37_SWITCH == ON)
#define CORE1_THREAD37_TYPE            CORE1_TASK37_TYPE             
#define CORE1_THREAD37_PERIOD          CORE1_TASK37_PERIOD
#define CORE1_THREAD37_ACTIVED         CORE1_TASK37_ACTIVED
#define CORE1_THREAD37_ACTIVED_COREID  CORE1_TASK37_ACTIVED_COREID
#define CORE1_THREAD37_PRIORITY        CORE1_TASK37_PRIORITY
#define CORE1_THREAD37_MODE            CORE1_TASK37_MODE
#define CORE1_THREAD37_STACK_SIZE      CORE1_TASK37_STACK_SIZE
#define CORE1_THREAD37_CALL_DEPTH      CORE1_TASK37_CALL_DEPTH
#endif
#if (CORE1_THREAD38_SWITCH == ON)
#define CORE1_THREAD38_TYPE            CORE1_TASK38_TYPE             
#define CORE1_THREAD38_PERIOD          CORE1_TASK38_PERIOD
#define CORE1_THREAD38_ACTIVED         CORE1_TASK38_ACTIVED
#define CORE1_THREAD38_ACTIVED_COREID  CORE1_TASK38_ACTIVED_COREID
#define CORE1_THREAD38_PRIORITY        CORE1_TASK38_PRIORITY
#define CORE1_THREAD38_MODE            CORE1_TASK38_MODE
#define CORE1_THREAD38_STACK_SIZE      CORE1_TASK38_STACK_SIZE
#define CORE1_THREAD38_CALL_DEPTH      CORE1_TASK38_CALL_DEPTH
#endif
#if (CORE1_THREAD39_SWITCH == ON)
#define CORE1_THREAD39_TYPE            CORE1_TASK39_TYPE             
#define CORE1_THREAD39_PERIOD          CORE1_TASK39_PERIOD
#define CORE1_THREAD39_ACTIVED         CORE1_TASK39_ACTIVED
#define CORE1_THREAD39_ACTIVED_COREID  CORE1_TASK39_ACTIVED_COREID
#define CORE1_THREAD39_PRIORITY        CORE1_TASK39_PRIORITY
#define CORE1_THREAD39_MODE            CORE1_TASK39_MODE
#define CORE1_THREAD39_STACK_SIZE      CORE1_TASK39_STACK_SIZE
#define CORE1_THREAD39_CALL_DEPTH      CORE1_TASK39_CALL_DEPTH
#endif
#if (CORE1_THREAD40_SWITCH == ON)
#define CORE1_THREAD40_TYPE            CORE1_TASK40_TYPE             
#define CORE1_THREAD40_PERIOD          CORE1_TASK40_PERIOD
#define CORE1_THREAD40_ACTIVED         CORE1_TASK40_ACTIVED
#define CORE1_THREAD40_ACTIVED_COREID  CORE1_TASK40_ACTIVED_COREID
#define CORE1_THREAD40_PRIORITY        CORE1_TASK40_PRIORITY
#define CORE1_THREAD40_MODE            CORE1_TASK40_MODE
#define CORE1_THREAD40_STACK_SIZE      CORE1_TASK40_STACK_SIZE
#define CORE1_THREAD40_CALL_DEPTH      CORE1_TASK40_CALL_DEPTH
#endif
#if (CORE1_THREAD41_SWITCH == ON)
#define CORE1_THREAD41_TYPE            CORE1_TASK41_TYPE             
#define CORE1_THREAD41_PERIOD          CORE1_TASK41_PERIOD
#define CORE1_THREAD41_ACTIVED         CORE1_TASK41_ACTIVED
#define CORE1_THREAD41_ACTIVED_COREID  CORE1_TASK41_ACTIVED_COREID
#define CORE1_THREAD41_PRIORITY        CORE1_TASK41_PRIORITY
#define CORE1_THREAD41_MODE            CORE1_TASK41_MODE
#define CORE1_THREAD41_STACK_SIZE      CORE1_TASK41_STACK_SIZE
#define CORE1_THREAD41_CALL_DEPTH      CORE1_TASK41_CALL_DEPTH  
#endif
#if (CORE1_THREAD42_SWITCH == ON)
#define CORE1_THREAD42_TYPE            CORE1_TASK42_TYPE             
#define CORE1_THREAD42_PERIOD          CORE1_TASK42_PERIOD
#define CORE1_THREAD42_ACTIVED         CORE1_TASK42_ACTIVED
#define CORE1_THREAD42_ACTIVED_COREID  CORE1_TASK42_ACTIVED_COREID
#define CORE1_THREAD42_PRIORITY        CORE1_TASK42_PRIORITY
#define CORE1_THREAD42_MODE            CORE1_TASK42_MODE
#define CORE1_THREAD42_STACK_SIZE      CORE1_TASK42_STACK_SIZE
#define CORE1_THREAD42_CALL_DEPTH      CORE1_TASK42_CALL_DEPTH 
#endif
#if (CORE1_THREAD43_SWITCH == ON)
#define CORE1_THREAD43_TYPE            CORE1_TASK43_TYPE             
#define CORE1_THREAD43_PERIOD          CORE1_TASK43_PERIOD
#define CORE1_THREAD43_ACTIVED         CORE1_TASK43_ACTIVED
#define CORE1_THREAD43_ACTIVED_COREID  CORE1_TASK43_ACTIVED_COREID
#define CORE1_THREAD43_PRIORITY        CORE1_TASK43_PRIORITY
#define CORE1_THREAD43_MODE            CORE1_TASK43_MODE
#define CORE1_THREAD43_STACK_SIZE      CORE1_TASK43_STACK_SIZE
#define CORE1_THREAD43_CALL_DEPTH      CORE1_TASK43_CALL_DEPTH 
#endif
#if (CORE1_THREAD44_SWITCH == ON)
#define CORE1_THREAD44_TYPE            CORE1_TASK44_TYPE             
#define CORE1_THREAD44_PERIOD          CORE1_TASK44_PERIOD
#define CORE1_THREAD44_ACTIVED         CORE1_TASK44_ACTIVED
#define CORE1_THREAD44_ACTIVED_COREID  CORE1_TASK44_ACTIVED_COREID
#define CORE1_THREAD44_PRIORITY        CORE1_TASK44_PRIORITY
#define CORE1_THREAD44_MODE            CORE1_TASK44_MODE
#define CORE1_THREAD44_STACK_SIZE      CORE1_TASK44_STACK_SIZE
#define CORE1_THREAD44_CALL_DEPTH      CORE1_TASK44_CALL_DEPTH 
#endif
#if (CORE1_THREAD45_SWITCH == ON)
#define CORE1_THREAD45_TYPE            CORE1_TASK45_TYPE             
#define CORE1_THREAD45_PERIOD          CORE1_TASK45_PERIOD
#define CORE1_THREAD45_ACTIVED         CORE1_TASK45_ACTIVED
#define CORE1_THREAD45_ACTIVED_COREID  CORE1_TASK45_ACTIVED_COREID
#define CORE1_THREAD45_PRIORITY        CORE1_TASK45_PRIORITY
#define CORE1_THREAD45_MODE            CORE1_TASK45_MODE
#define CORE1_THREAD45_STACK_SIZE      CORE1_TASK45_STACK_SIZE
#define CORE1_THREAD45_CALL_DEPTH      CORE1_TASK45_CALL_DEPTH 
#endif
#if (CORE1_THREAD46_SWITCH == ON)
#define CORE1_THREAD46_TYPE            CORE1_TASK46_TYPE             
#define CORE1_THREAD46_PERIOD          CORE1_TASK46_PERIOD
#define CORE1_THREAD46_ACTIVED         CORE1_TASK46_ACTIVED
#define CORE1_THREAD46_ACTIVED_COREID  CORE1_TASK46_ACTIVED_COREID
#define CORE1_THREAD46_PRIORITY        CORE1_TASK46_PRIORITY
#define CORE1_THREAD46_MODE            CORE1_TASK46_MODE
#define CORE1_THREAD46_STACK_SIZE      CORE1_TASK46_STACK_SIZE
#define CORE1_THREAD46_CALL_DEPTH      CORE1_TASK46_CALL_DEPTH 
#endif
#if (CORE1_THREAD47_SWITCH == ON)
#define CORE1_THREAD47_TYPE            CORE1_TASK47_TYPE             
#define CORE1_THREAD47_PERIOD          CORE1_TASK47_PERIOD
#define CORE1_THREAD47_ACTIVED         CORE1_TASK47_ACTIVED
#define CORE1_THREAD47_ACTIVED_COREID  CORE1_TASK47_ACTIVED_COREID
#define CORE1_THREAD47_PRIORITY        CORE1_TASK47_PRIORITY
#define CORE1_THREAD47_MODE            CORE1_TASK47_MODE
#define CORE1_THREAD47_STACK_SIZE      CORE1_TASK47_STACK_SIZE
#define CORE1_THREAD47_CALL_DEPTH      CORE1_TASK47_CALL_DEPTH
#endif
#if (CORE1_THREAD48_SWITCH == ON)
#define CORE1_THREAD48_TYPE            CORE1_TASK48_TYPE             
#define CORE1_THREAD48_PERIOD          CORE1_TASK48_PERIOD
#define CORE1_THREAD48_ACTIVED         CORE1_TASK48_ACTIVED
#define CORE1_THREAD48_ACTIVED_COREID  CORE1_TASK48_ACTIVED_COREID
#define CORE1_THREAD48_PRIORITY        CORE1_TASK48_PRIORITY
#define CORE1_THREAD48_MODE            CORE1_TASK48_MODE
#define CORE1_THREAD48_STACK_SIZE      CORE1_TASK48_STACK_SIZE
#define CORE1_THREAD48_CALL_DEPTH      CORE1_TASK48_CALL_DEPTH
#endif
#if (CORE1_THREAD49_SWITCH == ON)
#define CORE1_THREAD49_TYPE            CORE1_TASK49_TYPE             
#define CORE1_THREAD49_PERIOD          CORE1_TASK49_PERIOD
#define CORE1_THREAD49_ACTIVED         CORE1_TASK49_ACTIVED
#define CORE1_THREAD49_ACTIVED_COREID  CORE1_TASK49_ACTIVED_COREID
#define CORE1_THREAD49_PRIORITY        CORE1_TASK49_PRIORITY
#define CORE1_THREAD49_MODE            CORE1_TASK49_MODE
#define CORE1_THREAD49_STACK_SIZE      CORE1_TASK49_STACK_SIZE
#define CORE1_THREAD49_CALL_DEPTH      CORE1_TASK49_CALL_DEPTH
#endif
#if (CORE1_THREAD50_SWITCH == ON)
#define CORE1_THREAD50_TYPE            CORE1_TASK50_TYPE             
#define CORE1_THREAD50_PERIOD          CORE1_TASK50_PERIOD
#define CORE1_THREAD50_ACTIVED         CORE1_TASK50_ACTIVED
#define CORE1_THREAD50_ACTIVED_COREID  CORE1_TASK50_ACTIVED_COREID
#define CORE1_THREAD50_PRIORITY        CORE1_TASK50_PRIORITY
#define CORE1_THREAD50_MODE            CORE1_TASK50_MODE
#define CORE1_THREAD50_STACK_SIZE      CORE1_TASK50_STACK_SIZE
#define CORE1_THREAD50_CALL_DEPTH      CORE1_TASK50_CALL_DEPTH
#endif
#if (CORE1_THREAD51_SWITCH == ON)
#define CORE1_THREAD51_TYPE            CORE1_TASK51_TYPE             
#define CORE1_THREAD51_PERIOD          CORE1_TASK51_PERIOD
#define CORE1_THREAD51_ACTIVED         CORE1_TASK51_ACTIVED
#define CORE1_THREAD51_ACTIVED_COREID  CORE1_TASK51_ACTIVED_COREID
#define CORE1_THREAD51_PRIORITY        CORE1_TASK51_PRIORITY
#define CORE1_THREAD51_MODE            CORE1_TASK51_MODE
#define CORE1_THREAD51_STACK_SIZE      CORE1_TASK51_STACK_SIZE
#define CORE1_THREAD51_CALL_DEPTH      CORE1_TASK51_CALL_DEPTH  
#endif
#if (CORE1_THREAD52_SWITCH == ON)
#define CORE1_THREAD52_TYPE            CORE1_TASK52_TYPE             
#define CORE1_THREAD52_PERIOD          CORE1_TASK52_PERIOD
#define CORE1_THREAD52_ACTIVED         CORE1_TASK52_ACTIVED
#define CORE1_THREAD52_ACTIVED_COREID  CORE1_TASK52_ACTIVED_COREID
#define CORE1_THREAD52_PRIORITY        CORE1_TASK52_PRIORITY
#define CORE1_THREAD52_MODE            CORE1_TASK52_MODE
#define CORE1_THREAD52_STACK_SIZE      CORE1_TASK52_STACK_SIZE
#define CORE1_THREAD52_CALL_DEPTH      CORE1_TASK52_CALL_DEPTH 
#endif
#if (CORE1_THREAD53_SWITCH == ON)
#define CORE1_THREAD53_TYPE            CORE1_TASK53_TYPE             
#define CORE1_THREAD53_PERIOD          CORE1_TASK53_PERIOD
#define CORE1_THREAD53_ACTIVED         CORE1_TASK53_ACTIVED
#define CORE1_THREAD53_ACTIVED_COREID  CORE1_TASK53_ACTIVED_COREID
#define CORE1_THREAD53_PRIORITY        CORE1_TASK53_PRIORITY
#define CORE1_THREAD53_MODE            CORE1_TASK53_MODE
#define CORE1_THREAD53_STACK_SIZE      CORE1_TASK53_STACK_SIZE
#define CORE1_THREAD53_CALL_DEPTH      CORE1_TASK53_CALL_DEPTH 
#endif
#if (CORE1_THREAD54_SWITCH == ON)
#define CORE1_THREAD54_TYPE            CORE1_TASK54_TYPE             
#define CORE1_THREAD54_PERIOD          CORE1_TASK54_PERIOD
#define CORE1_THREAD54_ACTIVED         CORE1_TASK54_ACTIVED
#define CORE1_THREAD54_ACTIVED_COREID  CORE1_TASK54_ACTIVED_COREID
#define CORE1_THREAD54_PRIORITY        CORE1_TASK54_PRIORITY
#define CORE1_THREAD54_MODE            CORE1_TASK54_MODE
#define CORE1_THREAD54_STACK_SIZE      CORE1_TASK54_STACK_SIZE
#define CORE1_THREAD54_CALL_DEPTH      CORE1_TASK54_CALL_DEPTH 
#endif
#if (CORE1_THREAD55_SWITCH == ON)
#define CORE1_THREAD55_TYPE            CORE1_TASK55_TYPE             
#define CORE1_THREAD55_PERIOD          CORE1_TASK55_PERIOD
#define CORE1_THREAD55_ACTIVED         CORE1_TASK55_ACTIVED
#define CORE1_THREAD55_ACTIVED_COREID  CORE1_TASK55_ACTIVED_COREID
#define CORE1_THREAD55_PRIORITY        CORE1_TASK55_PRIORITY
#define CORE1_THREAD55_MODE            CORE1_TASK55_MODE
#define CORE1_THREAD55_STACK_SIZE      CORE1_TASK55_STACK_SIZE
#define CORE1_THREAD55_CALL_DEPTH      CORE1_TASK55_CALL_DEPTH 
#endif
#if (CORE1_THREAD56_SWITCH == ON)
#define CORE1_THREAD56_TYPE            CORE1_TASK56_TYPE             
#define CORE1_THREAD56_PERIOD          CORE1_TASK56_PERIOD
#define CORE1_THREAD56_ACTIVED         CORE1_TASK56_ACTIVED
#define CORE1_THREAD56_ACTIVED_COREID  CORE1_TASK56_ACTIVED_COREID
#define CORE1_THREAD56_PRIORITY        CORE1_TASK56_PRIORITY
#define CORE1_THREAD56_MODE            CORE1_TASK56_MODE
#define CORE1_THREAD56_STACK_SIZE      CORE1_TASK56_STACK_SIZE
#define CORE1_THREAD56_CALL_DEPTH      CORE1_TASK56_CALL_DEPTH 
#endif
#if (CORE1_THREAD57_SWITCH == ON)
#define CORE1_THREAD57_TYPE            CORE1_TASK57_TYPE             
#define CORE1_THREAD57_PERIOD          CORE1_TASK57_PERIOD
#define CORE1_THREAD57_ACTIVED         CORE1_TASK57_ACTIVED
#define CORE1_THREAD57_ACTIVED_COREID  CORE1_TASK57_ACTIVED_COREID
#define CORE1_THREAD57_PRIORITY        CORE1_TASK57_PRIORITY
#define CORE1_THREAD57_MODE            CORE1_TASK57_MODE
#define CORE1_THREAD57_STACK_SIZE      CORE1_TASK57_STACK_SIZE
#define CORE1_THREAD57_CALL_DEPTH      CORE1_TASK57_CALL_DEPTH
#endif
#if (CORE1_THREAD58_SWITCH == ON)
#define CORE1_THREAD58_TYPE            CORE1_TASK58_TYPE             
#define CORE1_THREAD58_PERIOD          CORE1_TASK58_PERIOD
#define CORE1_THREAD58_ACTIVED         CORE1_TASK58_ACTIVED
#define CORE1_THREAD58_ACTIVED_COREID  CORE1_TASK58_ACTIVED_COREID
#define CORE1_THREAD58_PRIORITY        CORE1_TASK58_PRIORITY
#define CORE1_THREAD58_MODE            CORE1_TASK58_MODE
#define CORE1_THREAD58_STACK_SIZE      CORE1_TASK58_STACK_SIZE
#define CORE1_THREAD58_CALL_DEPTH      CORE1_TASK58_CALL_DEPTH
#endif
#if (CORE1_THREAD59_SWITCH == ON)
#define CORE1_THREAD59_TYPE            CORE1_TASK59_TYPE             
#define CORE1_THREAD59_PERIOD          CORE1_TASK59_PERIOD
#define CORE1_THREAD59_ACTIVED         CORE1_TASK59_ACTIVED
#define CORE1_THREAD59_ACTIVED_COREID  CORE1_TASK59_ACTIVED_COREID
#define CORE1_THREAD59_PRIORITY        CORE1_TASK59_PRIORITY
#define CORE1_THREAD59_MODE            CORE1_TASK59_MODE
#define CORE1_THREAD59_STACK_SIZE      CORE1_TASK59_STACK_SIZE
#define CORE1_THREAD59_CALL_DEPTH      CORE1_TASK59_CALL_DEPTH
#endif
#if (CORE1_THREAD60_SWITCH == ON)
#define CORE1_THREAD60_TYPE            CORE1_TASK60_TYPE             
#define CORE1_THREAD60_PERIOD          CORE1_TASK60_PERIOD
#define CORE1_THREAD60_ACTIVED         CORE1_TASK60_ACTIVED
#define CORE1_THREAD60_ACTIVED_COREID  CORE1_TASK60_ACTIVED_COREID
#define CORE1_THREAD60_PRIORITY        CORE1_TASK60_PRIORITY
#define CORE1_THREAD60_MODE            CORE1_TASK60_MODE
#define CORE1_THREAD60_STACK_SIZE      CORE1_TASK60_STACK_SIZE
#define CORE1_THREAD60_CALL_DEPTH      CORE1_TASK60_CALL_DEPTH
#endif
#if (CORE1_THREAD61_SWITCH == ON)
#define CORE1_THREAD61_TYPE            CORE1_TASK61_TYPE             
#define CORE1_THREAD61_PERIOD          CORE1_TASK61_PERIOD
#define CORE1_THREAD61_ACTIVED         CORE1_TASK61_ACTIVED
#define CORE1_THREAD61_ACTIVED_COREID  CORE1_TASK61_ACTIVED_COREID
#define CORE1_THREAD61_PRIORITY        CORE1_TASK61_PRIORITY
#define CORE1_THREAD61_MODE            CORE1_TASK61_MODE
#define CORE1_THREAD61_STACK_SIZE      CORE1_TASK61_STACK_SIZE
#define CORE1_THREAD61_CALL_DEPTH      CORE1_TASK61_CALL_DEPTH  
#endif
#if (CORE1_THREAD62_SWITCH == ON)
#define CORE1_THREAD62_TYPE            CORE1_TASK62_TYPE             
#define CORE1_THREAD62_PERIOD          CORE1_TASK62_PERIOD
#define CORE1_THREAD62_ACTIVED         CORE1_TASK62_ACTIVED
#define CORE1_THREAD62_ACTIVED_COREID  CORE1_TASK62_ACTIVED_COREID
#define CORE1_THREAD62_PRIORITY        CORE1_TASK62_PRIORITY
#define CORE1_THREAD62_MODE            CORE1_TASK62_MODE
#define CORE1_THREAD62_STACK_SIZE      CORE1_TASK62_STACK_SIZE
#define CORE1_THREAD62_CALL_DEPTH      CORE1_TASK62_CALL_DEPTH 
#endif
#if (CORE1_THREAD63_SWITCH == ON)
#define CORE1_THREAD63_TYPE            CORE1_TASK63_TYPE             
#define CORE1_THREAD63_PERIOD          CORE1_TASK63_PERIOD
#define CORE1_THREAD63_ACTIVED         CORE1_TASK63_ACTIVED
#define CORE1_THREAD63_ACTIVED_COREID  CORE1_TASK63_ACTIVED_COREID
#define CORE1_THREAD63_PRIORITY        CORE1_TASK63_PRIORITY
#define CORE1_THREAD63_MODE            CORE1_TASK63_MODE
#define CORE1_THREAD63_STACK_SIZE      CORE1_TASK63_STACK_SIZE
#define CORE1_THREAD63_CALL_DEPTH      CORE1_TASK63_CALL_DEPTH 
#endif
#if (CORE1_THREAD64_SWITCH == ON)
#define CORE1_THREAD64_TYPE            CORE1_TASK64_TYPE             
#define CORE1_THREAD64_PERIOD          CORE1_TASK64_PERIOD
#define CORE1_THREAD64_ACTIVED         CORE1_TASK64_ACTIVED
#define CORE1_THREAD64_ACTIVED_COREID  CORE1_TASK64_ACTIVED_COREID
#define CORE1_THREAD64_PRIORITY        CORE1_TASK64_PRIORITY
#define CORE1_THREAD64_MODE            CORE1_TASK64_MODE
#define CORE1_THREAD64_STACK_SIZE      CORE1_TASK64_STACK_SIZE
#define CORE1_THREAD64_CALL_DEPTH      CORE1_TASK64_CALL_DEPTH 
#endif
#if (CORE1_THREAD65_SWITCH == ON)
#define CORE1_THREAD65_TYPE            CORE1_TASK65_TYPE             
#define CORE1_THREAD65_PERIOD          CORE1_TASK65_PERIOD
#define CORE1_THREAD65_ACTIVED         CORE1_TASK65_ACTIVED
#define CORE1_THREAD65_ACTIVED_COREID  CORE1_TASK65_ACTIVED_COREID
#define CORE1_THREAD65_PRIORITY        CORE1_TASK65_PRIORITY
#define CORE1_THREAD65_MODE            CORE1_TASK65_MODE
#define CORE1_THREAD65_STACK_SIZE      CORE1_TASK65_STACK_SIZE
#define CORE1_THREAD65_CALL_DEPTH      CORE1_TASK65_CALL_DEPTH 
#endif
#if (CORE1_THREAD66_SWITCH == ON)
#define CORE1_THREAD66_TYPE            CORE1_TASK66_TYPE             
#define CORE1_THREAD66_PERIOD          CORE1_TASK66_PERIOD
#define CORE1_THREAD66_ACTIVED         CORE1_TASK66_ACTIVED
#define CORE1_THREAD66_ACTIVED_COREID  CORE1_TASK66_ACTIVED_COREID
#define CORE1_THREAD66_PRIORITY        CORE1_TASK66_PRIORITY
#define CORE1_THREAD66_MODE            CORE1_TASK66_MODE
#define CORE1_THREAD66_STACK_SIZE      CORE1_TASK66_STACK_SIZE
#define CORE1_THREAD66_CALL_DEPTH      CORE1_TASK66_CALL_DEPTH 
#endif
#if (CORE1_THREAD67_SWITCH == ON)
#define CORE1_THREAD67_TYPE            CORE1_TASK67_TYPE             
#define CORE1_THREAD67_PERIOD          CORE1_TASK67_PERIOD
#define CORE1_THREAD67_ACTIVED         CORE1_TASK67_ACTIVED
#define CORE1_THREAD67_ACTIVED_COREID  CORE1_TASK67_ACTIVED_COREID
#define CORE1_THREAD67_PRIORITY        CORE1_TASK67_PRIORITY
#define CORE1_THREAD67_MODE            CORE1_TASK67_MODE
#define CORE1_THREAD67_STACK_SIZE      CORE1_TASK67_STACK_SIZE
#define CORE1_THREAD67_CALL_DEPTH      CORE1_TASK67_CALL_DEPTH
#endif
#if (CORE1_THREAD68_SWITCH == ON)
#define CORE1_THREAD68_TYPE            CORE1_TASK68_TYPE             
#define CORE1_THREAD68_PERIOD          CORE1_TASK68_PERIOD
#define CORE1_THREAD68_ACTIVED         CORE1_TASK68_ACTIVED
#define CORE1_THREAD68_ACTIVED_COREID  CORE1_TASK68_ACTIVED_COREID
#define CORE1_THREAD68_PRIORITY        CORE1_TASK68_PRIORITY
#define CORE1_THREAD68_MODE            CORE1_TASK68_MODE
#define CORE1_THREAD68_STACK_SIZE      CORE1_TASK68_STACK_SIZE
#define CORE1_THREAD68_CALL_DEPTH      CORE1_TASK68_CALL_DEPTH
#endif
#if (CORE1_THREAD69_SWITCH == ON)
#define CORE1_THREAD69_TYPE            CORE1_TASK69_TYPE             
#define CORE1_THREAD69_PERIOD          CORE1_TASK69_PERIOD
#define CORE1_THREAD69_ACTIVED         CORE1_TASK69_ACTIVED
#define CORE1_THREAD69_ACTIVED_COREID  CORE1_TASK69_ACTIVED_COREID
#define CORE1_THREAD69_PRIORITY        CORE1_TASK69_PRIORITY
#define CORE1_THREAD69_MODE            CORE1_TASK69_MODE
#define CORE1_THREAD69_STACK_SIZE      CORE1_TASK69_STACK_SIZE
#define CORE1_THREAD69_CALL_DEPTH      CORE1_TASK69_CALL_DEPTH
#endif
#if (CORE1_THREAD70_SWITCH == ON)
#define CORE1_THREAD70_TYPE            CORE1_TASK70_TYPE             
#define CORE1_THREAD70_PERIOD          CORE1_TASK70_PERIOD
#define CORE1_THREAD70_ACTIVED         CORE1_TASK70_ACTIVED
#define CORE1_THREAD70_ACTIVED_COREID  CORE1_TASK70_ACTIVED_COREID
#define CORE1_THREAD70_PRIORITY        CORE1_TASK70_PRIORITY
#define CORE1_THREAD70_MODE            CORE1_TASK70_MODE
#define CORE1_THREAD70_STACK_SIZE      CORE1_TASK70_STACK_SIZE
#define CORE1_THREAD70_CALL_DEPTH      CORE1_TASK70_CALL_DEPTH
#endif
#if (CORE1_THREAD71_SWITCH == ON)
#define CORE1_THREAD71_TYPE            CORE1_TASK71_TYPE             
#define CORE1_THREAD71_PERIOD          CORE1_TASK71_PERIOD
#define CORE1_THREAD71_ACTIVED         CORE1_TASK71_ACTIVED
#define CORE1_THREAD71_ACTIVED_COREID  CORE1_TASK71_ACTIVED_COREID
#define CORE1_THREAD71_PRIORITY        CORE1_TASK71_PRIORITY
#define CORE1_THREAD71_MODE            CORE1_TASK71_MODE
#define CORE1_THREAD71_STACK_SIZE      CORE1_TASK71_STACK_SIZE
#define CORE1_THREAD71_CALL_DEPTH      CORE1_TASK71_CALL_DEPTH  
#endif
#if (CORE1_THREAD72_SWITCH == ON)
#define CORE1_THREAD72_TYPE            CORE1_TASK72_TYPE             
#define CORE1_THREAD72_PERIOD          CORE1_TASK72_PERIOD
#define CORE1_THREAD72_ACTIVED         CORE1_TASK72_ACTIVED
#define CORE1_THREAD72_ACTIVED_COREID  CORE1_TASK72_ACTIVED_COREID
#define CORE1_THREAD72_PRIORITY        CORE1_TASK72_PRIORITY
#define CORE1_THREAD72_MODE            CORE1_TASK72_MODE
#define CORE1_THREAD72_STACK_SIZE      CORE1_TASK72_STACK_SIZE
#define CORE1_THREAD72_CALL_DEPTH      CORE1_TASK72_CALL_DEPTH 
#endif
#if (CORE1_THREAD73_SWITCH == ON)
#define CORE1_THREAD73_TYPE            CORE1_TASK73_TYPE             
#define CORE1_THREAD73_PERIOD          CORE1_TASK73_PERIOD
#define CORE1_THREAD73_ACTIVED         CORE1_TASK73_ACTIVED
#define CORE1_THREAD73_ACTIVED_COREID  CORE1_TASK73_ACTIVED_COREID
#define CORE1_THREAD73_PRIORITY        CORE1_TASK73_PRIORITY
#define CORE1_THREAD73_MODE            CORE1_TASK73_MODE
#define CORE1_THREAD73_STACK_SIZE      CORE1_TASK73_STACK_SIZE
#define CORE1_THREAD73_CALL_DEPTH      CORE1_TASK73_CALL_DEPTH 
#endif
#if (CORE1_THREAD74_SWITCH == ON)
#define CORE1_THREAD74_TYPE            CORE1_TASK74_TYPE             
#define CORE1_THREAD74_PERIOD          CORE1_TASK74_PERIOD
#define CORE1_THREAD74_ACTIVED         CORE1_TASK74_ACTIVED
#define CORE1_THREAD74_ACTIVED_COREID  CORE1_TASK74_ACTIVED_COREID
#define CORE1_THREAD74_PRIORITY        CORE1_TASK74_PRIORITY
#define CORE1_THREAD74_MODE            CORE1_TASK74_MODE
#define CORE1_THREAD74_STACK_SIZE      CORE1_TASK74_STACK_SIZE
#define CORE1_THREAD74_CALL_DEPTH      CORE1_TASK74_CALL_DEPTH 
#endif
#if (CORE1_THREAD75_SWITCH == ON)
#define CORE1_THREAD75_TYPE            CORE1_TASK75_TYPE             
#define CORE1_THREAD75_PERIOD          CORE1_TASK75_PERIOD
#define CORE1_THREAD75_ACTIVED         CORE1_TASK75_ACTIVED
#define CORE1_THREAD75_ACTIVED_COREID  CORE1_TASK75_ACTIVED_COREID
#define CORE1_THREAD75_PRIORITY        CORE1_TASK75_PRIORITY
#define CORE1_THREAD75_MODE            CORE1_TASK75_MODE
#define CORE1_THREAD75_STACK_SIZE      CORE1_TASK75_STACK_SIZE
#define CORE1_THREAD75_CALL_DEPTH      CORE1_TASK75_CALL_DEPTH 
#endif
#if (CORE1_THREAD76_SWITCH == ON)
#define CORE1_THREAD76_TYPE            CORE1_TASK76_TYPE             
#define CORE1_THREAD76_PERIOD          CORE1_TASK76_PERIOD
#define CORE1_THREAD76_ACTIVED         CORE1_TASK76_ACTIVED
#define CORE1_THREAD76_ACTIVED_COREID  CORE1_TASK76_ACTIVED_COREID
#define CORE1_THREAD76_PRIORITY        CORE1_TASK76_PRIORITY
#define CORE1_THREAD76_MODE            CORE1_TASK76_MODE
#define CORE1_THREAD76_STACK_SIZE      CORE1_TASK76_STACK_SIZE
#define CORE1_THREAD76_CALL_DEPTH      CORE1_TASK76_CALL_DEPTH 
#endif
#if (CORE1_THREAD77_SWITCH == ON)
#define CORE1_THREAD77_TYPE            CORE1_TASK77_TYPE             
#define CORE1_THREAD77_PERIOD          CORE1_TASK77_PERIOD
#define CORE1_THREAD77_ACTIVED         CORE1_TASK77_ACTIVED
#define CORE1_THREAD77_ACTIVED_COREID  CORE1_TASK77_ACTIVED_COREID
#define CORE1_THREAD77_PRIORITY        CORE1_TASK77_PRIORITY
#define CORE1_THREAD77_MODE            CORE1_TASK77_MODE
#define CORE1_THREAD77_STACK_SIZE      CORE1_TASK77_STACK_SIZE
#define CORE1_THREAD77_CALL_DEPTH      CORE1_TASK77_CALL_DEPTH
#endif
#if (CORE1_THREAD78_SWITCH == ON)
#define CORE1_THREAD78_TYPE            CORE1_TASK78_TYPE             
#define CORE1_THREAD78_PERIOD          CORE1_TASK78_PERIOD
#define CORE1_THREAD78_ACTIVED         CORE1_TASK78_ACTIVED
#define CORE1_THREAD78_ACTIVED_COREID  CORE1_TASK78_ACTIVED_COREID
#define CORE1_THREAD78_PRIORITY        CORE1_TASK78_PRIORITY
#define CORE1_THREAD78_MODE            CORE1_TASK78_MODE
#define CORE1_THREAD78_STACK_SIZE      CORE1_TASK78_STACK_SIZE
#define CORE1_THREAD78_CALL_DEPTH      CORE1_TASK78_CALL_DEPTH
#endif
#if (CORE1_THREAD79_SWITCH == ON)
#define CORE1_THREAD79_TYPE            CORE1_TASK79_TYPE             
#define CORE1_THREAD79_PERIOD          CORE1_TASK79_PERIOD
#define CORE1_THREAD79_ACTIVED         CORE1_TASK79_ACTIVED
#define CORE1_THREAD79_ACTIVED_COREID  CORE1_TASK79_ACTIVED_COREID
#define CORE1_THREAD79_PRIORITY        CORE1_TASK79_PRIORITY
#define CORE1_THREAD79_MODE            CORE1_TASK79_MODE
#define CORE1_THREAD79_STACK_SIZE      CORE1_TASK79_STACK_SIZE
#define CORE1_THREAD79_CALL_DEPTH      CORE1_TASK79_CALL_DEPTH
#endif
#if (CORE1_THREAD80_SWITCH == ON)
#define CORE1_THREAD80_TYPE            CORE1_TASK80_TYPE             
#define CORE1_THREAD80_PERIOD          CORE1_TASK80_PERIOD
#define CORE1_THREAD80_ACTIVED         CORE1_TASK80_ACTIVED
#define CORE1_THREAD80_ACTIVED_COREID  CORE1_TASK80_ACTIVED_COREID
#define CORE1_THREAD80_PRIORITY        CORE1_TASK80_PRIORITY
#define CORE1_THREAD80_MODE            CORE1_TASK80_MODE
#define CORE1_THREAD80_STACK_SIZE      CORE1_TASK80_STACK_SIZE
#define CORE1_THREAD80_CALL_DEPTH      CORE1_TASK80_CALL_DEPTH
#endif
#if (CORE1_THREAD81_SWITCH == ON)
#define CORE1_THREAD81_TYPE            CORE1_TASK81_TYPE             
#define CORE1_THREAD81_PERIOD          CORE1_TASK81_PERIOD
#define CORE1_THREAD81_ACTIVED         CORE1_TASK81_ACTIVED
#define CORE1_THREAD81_ACTIVED_COREID  CORE1_TASK81_ACTIVED_COREID
#define CORE1_THREAD81_PRIORITY        CORE1_TASK81_PRIORITY
#define CORE1_THREAD81_MODE            CORE1_TASK81_MODE
#define CORE1_THREAD81_STACK_SIZE      CORE1_TASK81_STACK_SIZE
#define CORE1_THREAD81_CALL_DEPTH      CORE1_TASK81_CALL_DEPTH  
#endif
#if (CORE1_THREAD82_SWITCH == ON)
#define CORE1_THREAD82_TYPE            CORE1_TASK82_TYPE             
#define CORE1_THREAD82_PERIOD          CORE1_TASK82_PERIOD
#define CORE1_THREAD82_ACTIVED         CORE1_TASK82_ACTIVED
#define CORE1_THREAD82_ACTIVED_COREID  CORE1_TASK82_ACTIVED_COREID
#define CORE1_THREAD82_PRIORITY        CORE1_TASK82_PRIORITY
#define CORE1_THREAD82_MODE            CORE1_TASK82_MODE
#define CORE1_THREAD82_STACK_SIZE      CORE1_TASK82_STACK_SIZE
#define CORE1_THREAD82_CALL_DEPTH      CORE1_TASK82_CALL_DEPTH 
#endif
#if (CORE1_THREAD83_SWITCH == ON)
#define CORE1_THREAD83_TYPE            CORE1_TASK83_TYPE             
#define CORE1_THREAD83_PERIOD          CORE1_TASK83_PERIOD
#define CORE1_THREAD83_ACTIVED         CORE1_TASK83_ACTIVED
#define CORE1_THREAD83_ACTIVED_COREID  CORE1_TASK83_ACTIVED_COREID
#define CORE1_THREAD83_PRIORITY        CORE1_TASK83_PRIORITY
#define CORE1_THREAD83_MODE            CORE1_TASK83_MODE
#define CORE1_THREAD83_STACK_SIZE      CORE1_TASK83_STACK_SIZE
#define CORE1_THREAD83_CALL_DEPTH      CORE1_TASK83_CALL_DEPTH 
#endif
#if (CORE1_THREAD84_SWITCH == ON)
#define CORE1_THREAD84_TYPE            CORE1_TASK84_TYPE             
#define CORE1_THREAD84_PERIOD          CORE1_TASK84_PERIOD
#define CORE1_THREAD84_ACTIVED         CORE1_TASK84_ACTIVED
#define CORE1_THREAD84_ACTIVED_COREID  CORE1_TASK84_ACTIVED_COREID
#define CORE1_THREAD84_PRIORITY        CORE1_TASK84_PRIORITY
#define CORE1_THREAD84_MODE            CORE1_TASK84_MODE
#define CORE1_THREAD84_STACK_SIZE      CORE1_TASK84_STACK_SIZE
#define CORE1_THREAD84_CALL_DEPTH      CORE1_TASK84_CALL_DEPTH 
#endif
#if (CORE1_THREAD85_SWITCH == ON)
#define CORE1_THREAD85_TYPE            CORE1_TASK85_TYPE             
#define CORE1_THREAD85_PERIOD          CORE1_TASK85_PERIOD
#define CORE1_THREAD85_ACTIVED         CORE1_TASK85_ACTIVED
#define CORE1_THREAD85_ACTIVED_COREID  CORE1_TASK85_ACTIVED_COREID
#define CORE1_THREAD85_PRIORITY        CORE1_TASK85_PRIORITY
#define CORE1_THREAD85_MODE            CORE1_TASK85_MODE
#define CORE1_THREAD85_STACK_SIZE      CORE1_TASK85_STACK_SIZE
#define CORE1_THREAD85_CALL_DEPTH      CORE1_TASK85_CALL_DEPTH 
#endif
#if (CORE1_THREAD86_SWITCH == ON)
#define CORE1_THREAD86_TYPE            CORE1_TASK86_TYPE             
#define CORE1_THREAD86_PERIOD          CORE1_TASK86_PERIOD
#define CORE1_THREAD86_ACTIVED         CORE1_TASK86_ACTIVED
#define CORE1_THREAD86_ACTIVED_COREID  CORE1_TASK86_ACTIVED_COREID
#define CORE1_THREAD86_PRIORITY        CORE1_TASK86_PRIORITY
#define CORE1_THREAD86_MODE            CORE1_TASK86_MODE
#define CORE1_THREAD86_STACK_SIZE      CORE1_TASK86_STACK_SIZE
#define CORE1_THREAD86_CALL_DEPTH      CORE1_TASK86_CALL_DEPTH 
#endif
#if (CORE1_THREAD87_SWITCH == ON)
#define CORE1_THREAD87_TYPE            CORE1_TASK87_TYPE             
#define CORE1_THREAD87_PERIOD          CORE1_TASK87_PERIOD
#define CORE1_THREAD87_ACTIVED         CORE1_TASK87_ACTIVED
#define CORE1_THREAD87_ACTIVED_COREID  CORE1_TASK87_ACTIVED_COREID
#define CORE1_THREAD87_PRIORITY        CORE1_TASK87_PRIORITY
#define CORE1_THREAD87_MODE            CORE1_TASK87_MODE
#define CORE1_THREAD87_STACK_SIZE      CORE1_TASK87_STACK_SIZE
#define CORE1_THREAD87_CALL_DEPTH      CORE1_TASK87_CALL_DEPTH
#endif
#if (CORE1_THREAD88_SWITCH == ON)
#define CORE1_THREAD88_TYPE            CORE1_TASK88_TYPE             
#define CORE1_THREAD88_PERIOD          CORE1_TASK88_PERIOD
#define CORE1_THREAD88_ACTIVED         CORE1_TASK88_ACTIVED
#define CORE1_THREAD88_ACTIVED_COREID  CORE1_TASK88_ACTIVED_COREID
#define CORE1_THREAD88_PRIORITY        CORE1_TASK88_PRIORITY
#define CORE1_THREAD88_MODE            CORE1_TASK88_MODE
#define CORE1_THREAD88_STACK_SIZE      CORE1_TASK88_STACK_SIZE
#define CORE1_THREAD88_CALL_DEPTH      CORE1_TASK88_CALL_DEPTH
#endif
#if (CORE1_THREAD89_SWITCH == ON)
#define CORE1_THREAD89_TYPE            CORE1_TASK89_TYPE             
#define CORE1_THREAD89_PERIOD          CORE1_TASK89_PERIOD
#define CORE1_THREAD89_ACTIVED         CORE1_TASK89_ACTIVED
#define CORE1_THREAD89_ACTIVED_COREID  CORE1_TASK89_ACTIVED_COREID
#define CORE1_THREAD89_PRIORITY        CORE1_TASK89_PRIORITY
#define CORE1_THREAD89_MODE            CORE1_TASK89_MODE
#define CORE1_THREAD89_STACK_SIZE      CORE1_TASK89_STACK_SIZE
#define CORE1_THREAD89_CALL_DEPTH      CORE1_TASK89_CALL_DEPTH
#endif
#if (CORE1_THREAD90_SWITCH == ON)
#define CORE1_THREAD90_TYPE            CORE1_TASK90_TYPE             
#define CORE1_THREAD90_PERIOD          CORE1_TASK90_PERIOD
#define CORE1_THREAD90_ACTIVED         CORE1_TASK90_ACTIVED
#define CORE1_THREAD90_ACTIVED_COREID  CORE1_TASK90_ACTIVED_COREID
#define CORE1_THREAD90_PRIORITY        CORE1_TASK90_PRIORITY
#define CORE1_THREAD90_MODE            CORE1_TASK90_MODE
#define CORE1_THREAD90_STACK_SIZE      CORE1_TASK90_STACK_SIZE
#define CORE1_THREAD90_CALL_DEPTH      CORE1_TASK90_CALL_DEPTH
#endif
#if (CORE1_THREAD91_SWITCH == ON)
#define CORE1_THREAD91_TYPE            CORE1_TASK91_TYPE             
#define CORE1_THREAD91_PERIOD          CORE1_TASK91_PERIOD
#define CORE1_THREAD91_ACTIVED         CORE1_TASK91_ACTIVED
#define CORE1_THREAD91_ACTIVED_COREID  CORE1_TASK91_ACTIVED_COREID
#define CORE1_THREAD91_PRIORITY        CORE1_TASK91_PRIORITY
#define CORE1_THREAD91_MODE            CORE1_TASK91_MODE
#define CORE1_THREAD91_STACK_SIZE      CORE1_TASK91_STACK_SIZE
#define CORE1_THREAD91_CALL_DEPTH      CORE1_TASK91_CALL_DEPTH  
#endif
#if (CORE1_THREAD92_SWITCH == ON)
#define CORE1_THREAD92_TYPE            CORE1_TASK92_TYPE             
#define CORE1_THREAD92_PERIOD          CORE1_TASK92_PERIOD
#define CORE1_THREAD92_ACTIVED         CORE1_TASK92_ACTIVED
#define CORE1_THREAD92_ACTIVED_COREID  CORE1_TASK92_ACTIVED_COREID
#define CORE1_THREAD92_PRIORITY        CORE1_TASK92_PRIORITY
#define CORE1_THREAD92_MODE            CORE1_TASK92_MODE
#define CORE1_THREAD92_STACK_SIZE      CORE1_TASK92_STACK_SIZE
#define CORE1_THREAD92_CALL_DEPTH      CORE1_TASK92_CALL_DEPTH 
#endif
#if (CORE1_THREAD93_SWITCH == ON)
#define CORE1_THREAD93_TYPE            CORE1_TASK93_TYPE             
#define CORE1_THREAD93_PERIOD          CORE1_TASK93_PERIOD
#define CORE1_THREAD93_ACTIVED         CORE1_TASK93_ACTIVED
#define CORE1_THREAD93_ACTIVED_COREID  CORE1_TASK93_ACTIVED_COREID
#define CORE1_THREAD93_PRIORITY        CORE1_TASK93_PRIORITY
#define CORE1_THREAD93_MODE            CORE1_TASK93_MODE
#define CORE1_THREAD93_STACK_SIZE      CORE1_TASK93_STACK_SIZE
#define CORE1_THREAD93_CALL_DEPTH      CORE1_TASK93_CALL_DEPTH 
#endif
#if (CORE1_THREAD94_SWITCH == ON)
#define CORE1_THREAD94_TYPE            CORE1_TASK94_TYPE             
#define CORE1_THREAD94_PERIOD          CORE1_TASK94_PERIOD
#define CORE1_THREAD94_ACTIVED         CORE1_TASK94_ACTIVED
#define CORE1_THREAD94_ACTIVED_COREID  CORE1_TASK94_ACTIVED_COREID
#define CORE1_THREAD94_PRIORITY        CORE1_TASK94_PRIORITY
#define CORE1_THREAD94_MODE            CORE1_TASK94_MODE
#define CORE1_THREAD94_STACK_SIZE      CORE1_TASK94_STACK_SIZE
#define CORE1_THREAD94_CALL_DEPTH      CORE1_TASK94_CALL_DEPTH 
#endif
#if (CORE1_THREAD95_SWITCH == ON)
#define CORE1_THREAD95_TYPE            CORE1_TASK95_TYPE             
#define CORE1_THREAD95_PERIOD          CORE1_TASK95_PERIOD
#define CORE1_THREAD95_ACTIVED         CORE1_TASK95_ACTIVED
#define CORE1_THREAD95_ACTIVED_COREID  CORE1_TASK95_ACTIVED_COREID
#define CORE1_THREAD95_PRIORITY        CORE1_TASK95_PRIORITY
#define CORE1_THREAD95_MODE            CORE1_TASK95_MODE
#define CORE1_THREAD95_STACK_SIZE      CORE1_TASK95_STACK_SIZE
#define CORE1_THREAD95_CALL_DEPTH      CORE1_TASK95_CALL_DEPTH 
#endif
#if (CORE1_THREAD96_SWITCH == ON)
#define CORE1_THREAD96_TYPE            CORE1_TASK96_TYPE             
#define CORE1_THREAD96_PERIOD          CORE1_TASK96_PERIOD
#define CORE1_THREAD96_ACTIVED         CORE1_TASK96_ACTIVED
#define CORE1_THREAD96_ACTIVED_COREID  CORE1_TASK96_ACTIVED_COREID
#define CORE1_THREAD96_PRIORITY        CORE1_TASK96_PRIORITY
#define CORE1_THREAD96_MODE            CORE1_TASK96_MODE
#define CORE1_THREAD96_STACK_SIZE      CORE1_TASK96_STACK_SIZE
#define CORE1_THREAD96_CALL_DEPTH      CORE1_TASK96_CALL_DEPTH 
#endif
#if (CORE1_THREAD97_SWITCH == ON)
#define CORE1_THREAD97_TYPE            CORE1_TASK97_TYPE             
#define CORE1_THREAD97_PERIOD          CORE1_TASK97_PERIOD
#define CORE1_THREAD97_ACTIVED         CORE1_TASK97_ACTIVED
#define CORE1_THREAD97_ACTIVED_COREID  CORE1_TASK97_ACTIVED_COREID
#define CORE1_THREAD97_PRIORITY        CORE1_TASK97_PRIORITY
#define CORE1_THREAD97_MODE            CORE1_TASK97_MODE
#define CORE1_THREAD97_STACK_SIZE      CORE1_TASK97_STACK_SIZE
#define CORE1_THREAD97_CALL_DEPTH      CORE1_TASK97_CALL_DEPTH
#endif
#if (CORE1_THREAD98_SWITCH == ON)
#define CORE1_THREAD98_TYPE            CORE1_TASK98_TYPE             
#define CORE1_THREAD98_PERIOD          CORE1_TASK98_PERIOD
#define CORE1_THREAD98_ACTIVED         CORE1_TASK98_ACTIVED
#define CORE1_THREAD98_ACTIVED_COREID  CORE1_TASK98_ACTIVED_COREID
#define CORE1_THREAD98_PRIORITY        CORE1_TASK98_PRIORITY
#define CORE1_THREAD98_MODE            CORE1_TASK98_MODE
#define CORE1_THREAD98_STACK_SIZE      CORE1_TASK98_STACK_SIZE
#define CORE1_THREAD98_CALL_DEPTH      CORE1_TASK98_CALL_DEPTH
#endif
#if (CORE1_THREAD99_SWITCH == ON)
#define CORE1_THREAD99_TYPE            CORE1_TASK99_TYPE             
#define CORE1_THREAD99_PERIOD          CORE1_TASK99_PERIOD
#define CORE1_THREAD99_ACTIVED         CORE1_TASK99_ACTIVED
#define CORE1_THREAD99_ACTIVED_COREID  CORE1_TASK99_ACTIVED_COREID
#define CORE1_THREAD99_PRIORITY        CORE1_TASK99_PRIORITY
#define CORE1_THREAD99_MODE            CORE1_TASK99_MODE
#define CORE1_THREAD99_STACK_SIZE      CORE1_TASK99_STACK_SIZE
#define CORE1_THREAD99_CALL_DEPTH      CORE1_TASK99_CALL_DEPTH
#endif
#if (CORE1_THREAD100_SWITCH == ON)
#define CORE1_THREAD100_TYPE            CORE1_TASK100_TYPE             
#define CORE1_THREAD100_PERIOD          CORE1_TASK100_PERIOD
#define CORE1_THREAD100_ACTIVED         CORE1_TASK100_ACTIVED
#define CORE1_THREAD100_ACTIVED_COREID  CORE1_TASK100_ACTIVED_COREID
#define CORE1_THREAD100_PRIORITY        CORE1_TASK100_PRIORITY
#define CORE1_THREAD100_MODE            CORE1_TASK100_MODE
#define CORE1_THREAD100_STACK_SIZE      CORE1_TASK100_STACK_SIZE
#define CORE1_THREAD100_CALL_DEPTH      CORE1_TASK100_CALL_DEPTH
#endif


#include "os.h"

#define CORE1_PTHREAD_INIT_CONFIG(thread_id) \
    {CORE_ID1 ,\
	 CORE1_THREAD_ID##thread_id, \
	 CORE1_THREAD##thread_id##_TYPE,\
	 CORE1_THREAD##thread_id##_PERIOD, \
	 CORE1_THREAD##thread_id##_ACTIVED, \
	 CORE1_THREAD##thread_id##_ACTIVED_COREID  },

#define CORE1_PTHREAD_ATTR_CONFIG(thread_id) \
	{CORE1_THREAD##thread_id##_MODE,\
	 CORE1_THREAD##thread_id##_CALL_DEPTH},
	 
OS_CONST pthread_config_t core1_pthread_init_config_database[CORE1_THREAD_MAX_ID_NUM] =
{
#if (CORE1_THREAD0_SWITCH == ON) 	
    CORE1_PTHREAD_INIT_CONFIG(0)
#endif
#if (CORE1_THREAD1_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(1)
#endif
#if (CORE1_THREAD2_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(2)
#endif
#if (CORE1_THREAD3_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(3)
#endif
#if (CORE1_THREAD4_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(4)
#endif
#if (CORE1_THREAD5_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(5)
#endif
#if (CORE1_THREAD6_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(6)
#endif
#if (CORE1_THREAD7_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(7)
#endif
#if (CORE1_THREAD8_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(8)
#endif
#if (CORE1_THREAD9_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(9)
#endif
#if (CORE1_THREAD10_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(10)
#endif
#if (CORE1_THREAD11_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(11)
#endif
#if (CORE1_THREAD12_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(12)
#endif
#if (CORE1_THREAD13_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(13)
#endif
#if (CORE1_THREAD14_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(14)
#endif
#if (CORE1_THREAD15_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(15)
#endif
#if (CORE1_THREAD16_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(16)
#endif
#if (CORE1_THREAD17_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(17)
#endif
#if (CORE1_THREAD18_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(18)
#endif
#if (CORE1_THREAD19_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(19)
#endif
#if (CORE1_THREAD20_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(20)
#endif
#if (CORE1_THREAD21_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(21)
#endif
#if (CORE1_THREAD22_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(22)
#endif
#if (CORE1_THREAD23_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(23)
#endif
#if (CORE1_THREAD24_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(24)
#endif
#if (CORE1_THREAD25_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(25)
#endif
#if (CORE1_THREAD26_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(26)
#endif
#if (CORE1_THREAD27_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(27)
#endif
#if (CORE1_THREAD28_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(28)
#endif
#if (CORE1_THREAD29_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(29)
#endif
#if (CORE1_THREAD30_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(30)
#endif
#if (CORE1_THREAD31_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(31)
#endif
#if (CORE1_THREAD32_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(32)
#endif
#if (CORE1_THREAD33_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(33)
#endif
#if (CORE1_THREAD34_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(34)
#endif
#if (CORE1_THREAD35_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(35)
#endif
#if (CORE1_THREAD36_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(36)
#endif
#if (CORE1_THREAD37_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(37)
#endif
#if (CORE1_THREAD38_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(38)
#endif
#if (CORE1_THREAD39_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(39)
#endif
#if (CORE1_THREAD40_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(40)
#endif
#if (CORE1_THREAD41_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(41)
#endif
#if (CORE1_THREAD42_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(42)
#endif
#if (CORE1_THREAD43_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(43)
#endif
#if (CORE1_THREAD44_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(44)
#endif
#if (CORE1_THREAD45_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(45)
#endif
#if (CORE1_THREAD46_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(46)
#endif
#if (CORE1_THREAD47_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(47)
#endif
#if (CORE1_THREAD48_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(48)
#endif
#if (CORE1_THREAD49_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(49)
#endif
#if (CORE1_THREAD50_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(50)
#endif
#if (CORE1_THREAD51_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(51)
#endif
#if (CORE1_THREAD52_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(52)
#endif
#if (CORE1_THREAD53_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(53)
#endif
#if (CORE1_THREAD54_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(54)
#endif
#if (CORE1_THREAD55_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(55)
#endif
#if (CORE1_THREAD56_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(56)
#endif
#if (CORE1_THREAD57_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(57)
#endif
#if (CORE1_THREAD58_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(58)
#endif
#if (CORE1_THREAD59_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(59)
#endif
#if (CORE1_THREAD60_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(60)
#endif
#if (CORE1_THREAD61_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(61)
#endif
#if (CORE1_THREAD62_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(62)
#endif
#if (CORE1_THREAD63_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(63)
#endif
#if (CORE1_THREAD64_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(64)
#endif
#if (CORE1_THREAD65_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(65)
#endif
#if (CORE1_THREAD66_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(66)
#endif
#if (CORE1_THREAD67_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(67)
#endif
#if (CORE1_THREAD68_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(68)
#endif
#if (CORE1_THREAD69_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(69)
#endif
#if (CORE1_THREAD70_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(70)
#endif
#if (CORE1_THREAD71_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(71)
#endif
#if (CORE1_THREAD72_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(72)
#endif
#if (CORE1_THREAD73_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(73)
#endif
#if (CORE1_THREAD74_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(74)
#endif
#if (CORE1_THREAD75_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(75)
#endif
#if (CORE1_THREAD76_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(76)
#endif
#if (CORE1_THREAD77_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(77)
#endif
#if (CORE1_THREAD78_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(78)
#endif
#if (CORE1_THREAD79_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(79)
#endif
#if (CORE1_THREAD80_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(80)
#endif
#if (CORE1_THREAD81_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(81)
#endif
#if (CORE1_THREAD82_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(82)
#endif
#if (CORE1_THREAD83_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(83)
#endif
#if (CORE1_THREAD84_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(84)
#endif
#if (CORE1_THREAD85_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(85)
#endif
#if (CORE1_THREAD86_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(86)
#endif
#if (CORE1_THREAD87_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(87)
#endif
#if (CORE1_THREAD88_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(88)
#endif
#if (CORE1_THREAD89_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(89)
#endif
#if (CORE1_THREAD90_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(90)
#endif
#if (CORE1_THREAD91_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(91)
#endif
#if (CORE1_THREAD92_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(92)
#endif
#if (CORE1_THREAD93_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(93)
#endif
#if (CORE1_THREAD94_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(94)
#endif
#if (CORE1_THREAD95_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(95)
#endif
#if (CORE1_THREAD96_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(96)
#endif
#if (CORE1_THREAD97_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(97)
#endif
#if (CORE1_THREAD98_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(98)
#endif
#if (CORE1_THREAD99_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(99)
#endif
#if (CORE1_THREAD100_SWITCH == ON) 
    CORE1_PTHREAD_INIT_CONFIG(100)
#endif
  };

#include "os_kernel.h"

pthread_cond_t core1_pthread_cond[CORE1_THREAD_MAX_ID_NUM] =
 {
 	
#if (CORE1_THREAD0_SWITCH == ON) 	
    CORE1_PTHREAD_COND_INIT_CONFIG(0)
#endif
#if (CORE1_THREAD1_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(1)
#endif
#if (CORE1_THREAD2_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(2)
#endif
#if (CORE1_THREAD3_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(3)
#endif
#if (CORE1_THREAD4_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(4)
#endif
#if (CORE1_THREAD5_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(5)
#endif
#if (CORE1_THREAD6_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(6)
#endif
#if (CORE1_THREAD7_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(7)
#endif
#if (CORE1_THREAD8_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(8)
#endif
#if (CORE1_THREAD9_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(9)
#endif
#if (CORE1_THREAD10_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(10)
#endif
#if (CORE1_THREAD11_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(11)
#endif
#if (CORE1_THREAD12_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(12)
#endif
#if (CORE1_THREAD13_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(13)
#endif
#if (CORE1_THREAD14_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(14)
#endif
#if (CORE1_THREAD15_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(15)
#endif
#if (CORE1_THREAD16_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(16)
#endif
#if (CORE1_THREAD17_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(17)
#endif
#if (CORE1_THREAD18_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(18)
#endif
#if (CORE1_THREAD19_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(19)
#endif
#if (CORE1_THREAD20_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(20)
#endif
#if (CORE1_THREAD21_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(21)
#endif
#if (CORE1_THREAD22_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(22)
#endif
#if (CORE1_THREAD23_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(23)
#endif
#if (CORE1_THREAD24_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(24)
#endif
#if (CORE1_THREAD25_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(25)
#endif
#if (CORE1_THREAD26_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(26)
#endif
#if (CORE1_THREAD27_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(27)
#endif
#if (CORE1_THREAD28_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(28)
#endif
#if (CORE1_THREAD29_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(29)
#endif
#if (CORE1_THREAD30_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(30)
#endif
#if (CORE1_THREAD31_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(31)
#endif
#if (CORE1_THREAD32_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(32)
#endif
#if (CORE1_THREAD33_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(33)
#endif
#if (CORE1_THREAD34_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(34)
#endif
#if (CORE1_THREAD35_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(35)
#endif
#if (CORE1_THREAD36_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(36)
#endif
#if (CORE1_THREAD37_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(37)
#endif
#if (CORE1_THREAD38_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(38)
#endif
#if (CORE1_THREAD39_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(39)
#endif
#if (CORE1_THREAD40_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(40)
#endif
#if (CORE1_THREAD41_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(41)
#endif
#if (CORE1_THREAD42_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(42)
#endif
#if (CORE1_THREAD43_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(43)
#endif
#if (CORE1_THREAD44_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(44)
#endif
#if (CORE1_THREAD45_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(45)
#endif
#if (CORE1_THREAD46_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(46)
#endif
#if (CORE1_THREAD47_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(47)
#endif
#if (CORE1_THREAD48_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(48)
#endif
#if (CORE1_THREAD49_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(49)
#endif
#if (CORE1_THREAD50_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(50)
#endif
#if (CORE1_THREAD51_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(51)
#endif
#if (CORE1_THREAD52_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(52)
#endif
#if (CORE1_THREAD53_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(53)
#endif
#if (CORE1_THREAD54_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(54)
#endif
#if (CORE1_THREAD55_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(55)
#endif
#if (CORE1_THREAD56_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(56)
#endif
#if (CORE1_THREAD57_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(57)
#endif
#if (CORE1_THREAD58_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(58)
#endif
#if (CORE1_THREAD59_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(59)
#endif
#if (CORE1_THREAD60_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(60)
#endif
#if (CORE1_THREAD61_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(61)
#endif
#if (CORE1_THREAD62_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(62)
#endif
#if (CORE1_THREAD63_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(63)
#endif
#if (CORE1_THREAD64_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(64)
#endif
#if (CORE1_THREAD65_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(65)
#endif
#if (CORE1_THREAD66_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(66)
#endif
#if (CORE1_THREAD67_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(67)
#endif
#if (CORE1_THREAD68_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(68)
#endif
#if (CORE1_THREAD69_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(69)
#endif
#if (CORE1_THREAD70_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(70)
#endif
#if (CORE1_THREAD71_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(71)
#endif
#if (CORE1_THREAD72_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(72)
#endif
#if (CORE1_THREAD73_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(73)
#endif
#if (CORE1_THREAD74_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(74)
#endif
#if (CORE1_THREAD75_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(75)
#endif
#if (CORE1_THREAD76_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(76)
#endif
#if (CORE1_THREAD77_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(77)
#endif
#if (CORE1_THREAD78_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(78)
#endif
#if (CORE1_THREAD79_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(79)
#endif
#if (CORE1_THREAD80_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(80)
#endif
#if (CORE1_THREAD81_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(81)
#endif
#if (CORE1_THREAD82_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(82)
#endif
#if (CORE1_THREAD83_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(83)
#endif
#if (CORE1_THREAD84_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(84)
#endif
#if (CORE1_THREAD85_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(85)
#endif
#if (CORE1_THREAD86_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(86)
#endif
#if (CORE1_THREAD87_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(87)
#endif
#if (CORE1_THREAD88_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(88)
#endif
#if (CORE1_THREAD89_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(89)
#endif
#if (CORE1_THREAD90_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(90)
#endif
#if (CORE1_THREAD91_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(91)
#endif
#if (CORE1_THREAD92_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(92)
#endif
#if (CORE1_THREAD93_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(93)
#endif
#if (CORE1_THREAD94_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(94)
#endif
#if (CORE1_THREAD95_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(95)
#endif
#if (CORE1_THREAD96_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(96)
#endif
#if (CORE1_THREAD97_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(97)
#endif
#if (CORE1_THREAD98_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(98)
#endif
#if (CORE1_THREAD99_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(99)
#endif
#if (CORE1_THREAD100_SWITCH == ON) 
    CORE1_PTHREAD_COND_INIT_CONFIG(100)
#endif
  };

OS_CONST pthread_attr_t core1_thread_attr[CORE1_THREAD_MAX_ID_NUM] =
{ 
#if (CORE1_THREAD0_SWITCH == ON) 	
    CORE1_PTHREAD_ATTR_CONFIG(0)
#endif
#if (CORE1_THREAD1_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(1)
#endif
#if (CORE1_THREAD2_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(2)
#endif
#if (CORE1_THREAD3_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(3)
#endif
#if (CORE1_THREAD4_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(4)
#endif
#if (CORE1_THREAD5_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(5)
#endif
#if (CORE1_THREAD6_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(6)
#endif
#if (CORE1_THREAD7_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(7)
#endif
#if (CORE1_THREAD8_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(8)
#endif
#if (CORE1_THREAD9_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(9)
#endif
#if (CORE1_THREAD10_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(10)
#endif
#if (CORE1_THREAD11_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(11)
#endif
#if (CORE1_THREAD12_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(12)
#endif
#if (CORE1_THREAD13_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(13)
#endif
#if (CORE1_THREAD14_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(14)
#endif
#if (CORE1_THREAD15_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(15)
#endif
#if (CORE1_THREAD16_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(16)
#endif
#if (CORE1_THREAD17_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(17)
#endif
#if (CORE1_THREAD18_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(18)
#endif
#if (CORE1_THREAD19_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(19)
#endif
#if (CORE1_THREAD20_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(20)
#endif
#if (CORE1_THREAD21_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(21)
#endif
#if (CORE1_THREAD22_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(22)
#endif
#if (CORE1_THREAD23_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(23)
#endif
#if (CORE1_THREAD24_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(24)
#endif
#if (CORE1_THREAD25_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(25)
#endif
#if (CORE1_THREAD26_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(26)
#endif
#if (CORE1_THREAD27_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(27)
#endif
#if (CORE1_THREAD28_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(28)
#endif
#if (CORE1_THREAD29_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(29)
#endif
#if (CORE1_THREAD30_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(30)
#endif
#if (CORE1_THREAD31_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(31)
#endif
#if (CORE1_THREAD32_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(32)
#endif
#if (CORE1_THREAD33_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(33)
#endif
#if (CORE1_THREAD34_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(34)
#endif
#if (CORE1_THREAD35_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(35)
#endif
#if (CORE1_THREAD36_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(36)
#endif
#if (CORE1_THREAD37_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(37)
#endif
#if (CORE1_THREAD38_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(38)
#endif
#if (CORE1_THREAD39_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(39)
#endif
#if (CORE1_THREAD40_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(40)
#endif
#if (CORE1_THREAD41_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(41)
#endif
#if (CORE1_THREAD42_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(42)
#endif
#if (CORE1_THREAD43_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(43)
#endif
#if (CORE1_THREAD44_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(44)
#endif
#if (CORE1_THREAD45_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(45)
#endif
#if (CORE1_THREAD46_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(46)
#endif
#if (CORE1_THREAD47_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(47)
#endif
#if (CORE1_THREAD48_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(48)
#endif
#if (CORE1_THREAD49_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(49)
#endif
#if (CORE1_THREAD50_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(50)
#endif
#if (CORE1_THREAD51_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(51)
#endif
#if (CORE1_THREAD52_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(52)
#endif
#if (CORE1_THREAD53_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(53)
#endif
#if (CORE1_THREAD54_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(54)
#endif
#if (CORE1_THREAD55_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(55)
#endif
#if (CORE1_THREAD56_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(56)
#endif
#if (CORE1_THREAD57_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(57)
#endif
#if (CORE1_THREAD58_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(58)
#endif
#if (CORE1_THREAD59_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(59)
#endif
#if (CORE1_THREAD60_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(60)
#endif
#if (CORE1_THREAD61_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(61)
#endif
#if (CORE1_THREAD62_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(62)
#endif
#if (CORE1_THREAD63_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(63)
#endif
#if (CORE1_THREAD64_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(64)
#endif
#if (CORE1_THREAD65_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(65)
#endif
#if (CORE1_THREAD66_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(66)
#endif
#if (CORE1_THREAD67_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(67)
#endif
#if (CORE1_THREAD68_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(68)
#endif
#if (CORE1_THREAD69_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(69)
#endif
#if (CORE1_THREAD70_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(70)
#endif
#if (CORE1_THREAD71_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(71)
#endif
#if (CORE1_THREAD72_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(72)
#endif
#if (CORE1_THREAD73_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(73)
#endif
#if (CORE1_THREAD74_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(74)
#endif
#if (CORE1_THREAD75_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(75)
#endif
#if (CORE1_THREAD76_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(76)
#endif
#if (CORE1_THREAD77_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(77)
#endif
#if (CORE1_THREAD78_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(78)
#endif
#if (CORE1_THREAD79_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(79)
#endif
#if (CORE1_THREAD80_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(80)
#endif
#if (CORE1_THREAD81_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(81)
#endif
#if (CORE1_THREAD82_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(82)
#endif
#if (CORE1_THREAD83_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(83)
#endif
#if (CORE1_THREAD84_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(84)
#endif
#if (CORE1_THREAD85_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(85)
#endif
#if (CORE1_THREAD86_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(86)
#endif
#if (CORE1_THREAD87_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(87)
#endif
#if (CORE1_THREAD88_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(88)
#endif
#if (CORE1_THREAD89_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(89)
#endif
#if (CORE1_THREAD90_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(90)
#endif
#if (CORE1_THREAD91_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(91)
#endif
#if (CORE1_THREAD92_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(92)
#endif
#if (CORE1_THREAD93_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(93)
#endif
#if (CORE1_THREAD94_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(94)
#endif
#if (CORE1_THREAD95_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(95)
#endif
#if (CORE1_THREAD96_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(96)
#endif
#if (CORE1_THREAD97_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(97)
#endif
#if (CORE1_THREAD98_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(98)
#endif
#if (CORE1_THREAD99_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(99)
#endif
#if (CORE1_THREAD100_SWITCH == ON) 
    CORE1_PTHREAD_ATTR_CONFIG(100)
#endif
};

#include "os_kernel.h"
#include "os_trace.h"

extern pthread_cond_t core0_pthread_cond[CORE0_TASK_MAX_ID_NUM];
//extern pthread_cond_t core1_pthread_cond[CORE1_TASK_MAX_ID_NUM];
extern pthread_cond_t core2_pthread_cond[CORE2_TASK_MAX_ID_NUM];

void core1_pthread_done_after_task(pthread_config_t *pthread_config)
{ 	
  /* Trace */
  os_trace_task_time_end(pthread_config->current_task_core_id,pthread_config->task_id);

  if(pthread_config->actived_task_id != NO_ACTIVED_THREAD)
  { 
  	 if(pthread_config->actived_task_core_id == CORE_ID0)
	 {
		  pthread_cond_broadcast(&core0_pthread_cond[pthread_config->actived_task_id]);
	 }
	 else if(pthread_config->actived_task_core_id == CORE_ID1)
	 {
		  pthread_cond_broadcast(&core1_pthread_cond[pthread_config->actived_task_id]);
	 }
	 else if(pthread_config->actived_task_core_id == CORE_ID2)
	 {
		  pthread_cond_broadcast(&core2_pthread_cond[pthread_config->actived_task_id]);
	 }
  }
  else if((pthread_config->type == PERIODIC)||
  	      (pthread_config->type == NO_DEFINITION))
  {
      /* Do nothing */
  }
}

void core1_pthread_done_before_task(pthread_config_t *pthread_config)
{ 
  if(pthread_config->type == EVENT)
  {
      pthread_cond_wait(&core1_pthread_cond[pthread_config->task_id]);
  }
  else if(pthread_config->type == PERIODIC)
  {
	  pthread_cond_timedwait_np((osu16_t)(pthread_config->period));
  }
  else if(pthread_config->type == NO_DEFINITION)
  {
     /* Do nothing. */
  }
  /* trace */
  os_trace_task_time_begin(pthread_config->current_task_core_id,pthread_config->task_id);
}
#endif

