 
#ifndef TASK_CFG_H_
#define TASK_CFG_H_

#define	 CORE2_TASK0_SWITCH	    ON
#define	 CORE2_TASK1_SWITCH 	ON
#define	 CORE2_TASK2_SWITCH 	ON
#define	 CORE2_TASK3_SWITCH	    ON
#define	 CORE2_TASK4_SWITCH	    ON
#define	 CORE2_TASK5_SWITCH	    ON
#define	 CORE2_TASK6_SWITCH	    ON
#define	 CORE2_TASK7_SWITCH	    ON
#define	 CORE2_TASK8_SWITCH	    ON
#define	 CORE2_TASK9_SWITCH	    ON
#define	 CORE2_TASK10_SWITCH	ON
#define	 CORE2_TASK11_SWITCH 	OFF
#define	 CORE2_TASK12_SWITCH 	OFF
#define	 CORE2_TASK13_SWITCH	OFF
#define	 CORE2_TASK14_SWITCH	OFF
#define	 CORE2_TASK15_SWITCH	OFF
#define	 CORE2_TASK16_SWITCH	OFF
#define	 CORE2_TASK17_SWITCH	OFF
#define	 CORE2_TASK18_SWITCH	OFF
#define	 CORE2_TASK19_SWITCH	OFF
#define	 CORE2_TASK20_SWITCH	OFF
#define	 CORE2_TASK21_SWITCH 	OFF
#define	 CORE2_TASK22_SWITCH 	OFF
#define	 CORE2_TASK23_SWITCH	OFF
#define	 CORE2_TASK24_SWITCH	OFF
#define	 CORE2_TASK25_SWITCH	OFF
#define	 CORE2_TASK26_SWITCH	OFF
#define	 CORE2_TASK27_SWITCH	OFF
#define	 CORE2_TASK28_SWITCH	OFF
#define	 CORE2_TASK29_SWITCH	OFF
#define	 CORE2_TASK30_SWITCH	OFF
#define	 CORE2_TASK31_SWITCH 	OFF
#define	 CORE2_TASK32_SWITCH 	OFF
#define	 CORE2_TASK33_SWITCH	OFF
#define	 CORE2_TASK34_SWITCH	OFF
#define	 CORE2_TASK35_SWITCH	OFF
#define	 CORE2_TASK36_SWITCH	OFF
#define	 CORE2_TASK37_SWITCH	OFF
#define	 CORE2_TASK38_SWITCH	OFF
#define	 CORE2_TASK39_SWITCH	OFF
#define	 CORE2_TASK40_SWITCH	OFF
#define	 CORE2_TASK41_SWITCH 	OFF
#define	 CORE2_TASK42_SWITCH 	OFF
#define	 CORE2_TASK43_SWITCH	OFF
#define	 CORE2_TASK44_SWITCH	OFF
#define	 CORE2_TASK45_SWITCH	OFF
#define	 CORE2_TASK46_SWITCH	OFF
#define	 CORE2_TASK47_SWITCH	OFF
#define	 CORE2_TASK48_SWITCH	OFF
#define	 CORE2_TASK49_SWITCH	OFF
#define	 CORE2_TASK50_SWITCH	OFF
#define	 CORE2_TASK51_SWITCH 	OFF
#define	 CORE2_TASK52_SWITCH 	OFF
#define	 CORE2_TASK53_SWITCH	OFF
#define	 CORE2_TASK54_SWITCH	OFF
#define	 CORE2_TASK55_SWITCH	OFF
#define	 CORE2_TASK56_SWITCH	OFF
#define	 CORE2_TASK57_SWITCH	OFF
#define	 CORE2_TASK58_SWITCH	OFF
#define	 CORE2_TASK59_SWITCH	OFF
#define	 CORE2_TASK60_SWITCH	OFF
#define	 CORE2_TASK61_SWITCH 	OFF
#define	 CORE2_TASK62_SWITCH 	OFF
#define	 CORE2_TASK63_SWITCH	OFF
#define	 CORE2_TASK64_SWITCH	OFF
#define	 CORE2_TASK65_SWITCH	OFF
#define	 CORE2_TASK66_SWITCH	OFF
#define	 CORE2_TASK67_SWITCH	OFF
#define	 CORE2_TASK68_SWITCH	OFF
#define	 CORE2_TASK69_SWITCH	OFF
#define	 CORE2_TASK70_SWITCH	OFF
#define	 CORE2_TASK71_SWITCH 	OFF
#define	 CORE2_TASK72_SWITCH 	OFF
#define	 CORE2_TASK73_SWITCH	OFF
#define	 CORE2_TASK74_SWITCH	OFF
#define	 CORE2_TASK75_SWITCH	OFF
#define	 CORE2_TASK76_SWITCH	OFF
#define	 CORE2_TASK77_SWITCH	OFF
#define	 CORE2_TASK78_SWITCH	OFF
#define	 CORE2_TASK79_SWITCH	OFF
#define	 CORE2_TASK80_SWITCH	OFF
#define	 CORE2_TASK81_SWITCH 	OFF
#define	 CORE2_TASK82_SWITCH 	OFF
#define	 CORE2_TASK83_SWITCH	OFF
#define	 CORE2_TASK84_SWITCH	OFF
#define	 CORE2_TASK85_SWITCH	OFF
#define	 CORE2_TASK86_SWITCH	OFF
#define	 CORE2_TASK87_SWITCH	OFF
#define	 CORE2_TASK88_SWITCH	OFF
#define	 CORE2_TASK89_SWITCH	OFF
#define	 CORE2_TASK99_SWITCH	OFF
#define	 CORE2_TASK90_SWITCH	OFF
#define	 CORE2_TASK91_SWITCH 	OFF
#define	 CORE2_TASK92_SWITCH 	OFF
#define	 CORE2_TASK93_SWITCH	OFF
#define	 CORE2_TASK94_SWITCH	OFF
#define	 CORE2_TASK95_SWITCH	OFF
#define	 CORE2_TASK96_SWITCH	OFF
#define	 CORE2_TASK97_SWITCH	OFF
#define	 CORE2_TASK98_SWITCH	OFF
#define	 CORE2_TASK99_SWITCH	OFF
#define	 CORE2_TASK100_SWITCH	OFF

typedef enum  {

#if (CORE2_TASK0_SWITCH == ON) 
	 CORE2_TASK_ID0,
#endif
#if (CORE2_TASK1_SWITCH == ON) 
	 CORE2_TASK_ID1,
#endif
#if (CORE2_TASK2_SWITCH == ON) 
	 CORE2_TASK_ID2,
#endif
#if (CORE2_TASK3_SWITCH == ON) 
	 CORE2_TASK_ID3,
#endif
#if (CORE2_TASK4_SWITCH == ON) 
	 CORE2_TASK_ID4,
#endif	 
#if (CORE2_TASK5_SWITCH == ON) 
	 CORE2_TASK_ID5,
#endif	 
#if (CORE2_TASK6_SWITCH == ON) 	
	 CORE2_TASK_ID6,
#endif	 
#if (CORE2_TASK7_SWITCH == ON) 	 
	 CORE2_TASK_ID7,
#endif	 
#if (CORE2_TASK8_SWITCH == ON) 	
	 CORE2_TASK_ID8,
#endif	 
#if (CORE2_TASK9_SWITCH == ON) 	
	 CORE2_TASK_ID9,
#endif	 
#if (CORE2_TASK10_SWITCH == ON) 		 
	 CORE2_TASK_ID10,
#endif	 
#if (CORE2_TASK11_SWITCH == ON) 	
	 CORE2_TASK_ID11,
#endif	 
#if (CORE2_TASK12_SWITCH == ON) 	
	 CORE2_TASK_ID12,
#endif	 
#if (CORE2_TASK13_SWITCH == ON) 	
	 CORE2_TASK_ID13,
#endif	 
#if (CORE2_TASK14_SWITCH == ON) 	
	 CORE2_TASK_ID14,
#endif	 
#if (CORE2_TASK15_SWITCH == ON) 	
	 CORE2_TASK_ID15,
#endif	 
#if (CORE2_TASK16_SWITCH == ON) 	
	 CORE2_TASK_ID16,
#endif	 
#if (CORE2_TASK17_SWITCH == ON) 	
	 CORE2_TASK_ID17,
#endif	 
#if (CORE2_TASK18_SWITCH == ON) 	
	 CORE2_TASK_ID18,
#endif	 
#if (CORE2_TASK19_SWITCH == ON) 	
	 CORE2_TASK_ID19,
#endif	 
#if (CORE2_TASK20_SWITCH == ON) 	
	 CORE2_TASK_ID20,
#endif	 
#if (CORE2_TASK21_SWITCH == ON) 	
	 CORE2_TASK_ID21,
#endif	 
#if (CORE2_TASK22_SWITCH == ON) 	
	 CORE2_TASK_ID22,
#endif	 
#if (CORE2_TASK23_SWITCH == ON) 	
	 CORE2_TASK_ID23,
#endif	 
#if (CORE2_TASK24_SWITCH == ON) 	
	 CORE2_TASK_ID24,
#endif	 
#if (CORE2_TASK25_SWITCH == ON) 	
	 CORE2_TASK_ID25,
#endif	 
#if (CORE2_TASK26_SWITCH == ON) 	
	 CORE2_TASK_ID26,
#endif	 
#if (CORE2_TASK27_SWITCH == ON) 	
	 CORE2_TASK_ID27,
#endif	 
#if (CORE2_TASK28_SWITCH == ON) 	
	 CORE2_TASK_ID28,
#endif	 
#if (CORE2_TASK29_SWITCH == ON) 	
	 CORE2_TASK_ID29,
#endif	 
#if (CORE2_TASK30_SWITCH == ON) 	
	 CORE2_TASK_ID30,
#endif	 
#if (CORE2_TASK31_SWITCH == ON) 	
	 CORE2_TASK_ID31,
#endif	 
#if (CORE2_TASK32_SWITCH == ON) 		 
	 CORE2_TASK_ID32,
#endif	 
#if (CORE2_TASK33_SWITCH == ON) 	
	 CORE2_TASK_ID33,
#endif	 
#if (CORE2_TASK34_SWITCH == ON) 	
	 CORE2_TASK_ID34,
#endif	 
#if (CORE2_TASK35_SWITCH == ON) 	
	 CORE2_TASK_ID35,
#endif	 
#if (CORE2_TASK36_SWITCH == ON) 	
	 CORE2_TASK_ID36,
#endif	 
#if (CORE2_TASK37_SWITCH == ON) 	
	 CORE2_TASK_ID37,
#endif	 
#if (CORE2_TASK38_SWITCH == ON) 	
	 CORE2_TASK_ID38,
#endif	 
#if (CORE2_TASK39_SWITCH == ON) 	
	 CORE2_TASK_ID39,
#endif	 
#if (CORE2_TASK40_SWITCH == ON) 	
	 CORE2_TASK_ID40,
#endif	 
#if (CORE2_TASK41_SWITCH == ON) 	
	 CORE2_TASK_ID41,
#endif	 
#if (CORE2_TASK42_SWITCH == ON) 	
	 CORE2_TASK_ID42,
#endif	 
#if (CORE2_TASK43_SWITCH == ON) 	
	 CORE2_TASK_ID43,
#endif	 
#if (CORE2_TASK44_SWITCH == ON) 	
	 CORE2_TASK_ID44,
#endif	 
#if (CORE2_TASK45_SWITCH == ON) 	
	 CORE2_TASK_ID45,
#endif	 
#if (CORE2_TASK46_SWITCH == ON) 	
	 CORE2_TASK_ID46,
#endif	 
#if (CORE2_TASK47_SWITCH == ON) 	
	 CORE2_TASK_ID47,
#endif	 
#if (CORE2_TASK48_SWITCH == ON) 	
	 CORE2_TASK_ID48,
#endif	 
#if (CORE2_TASK49_SWITCH == ON) 	
	 CORE2_TASK_ID49,
#endif	 
#if (CORE2_TASK50_SWITCH == ON) 	
	 CORE2_TASK_ID50,
#endif	 
#if (CORE2_TASK51_SWITCH == ON) 	
	 CORE2_TASK_ID51,
#endif	 
#if (CORE2_TASK52_SWITCH == ON) 	
	 CORE2_TASK_ID52,
#endif	 
#if (CORE2_TASK53_SWITCH == ON) 	
	 CORE2_TASK_ID53,
#endif	 
#if (CORE2_TASK54_SWITCH == ON) 	
	 CORE2_TASK_ID54,
#endif	 
#if (CORE2_TASK55_SWITCH == ON) 	
	 CORE2_TASK_ID55,
#endif	 
#if (CORE2_TASK56_SWITCH == ON) 	
	 CORE2_TASK_ID56,
#endif	 
#if (CORE2_TASK57_SWITCH == ON) 	
	 CORE2_TASK_ID57,
#endif	 
#if (CORE2_TASK58_SWITCH == ON) 	
	 CORE2_TASK_ID58,
#endif	 
#if (CORE2_TASK59_SWITCH == ON) 	
	 CORE2_TASK_ID59,
#endif	 
#if (CORE2_TASK60_SWITCH == ON) 	
	 CORE2_TASK_ID60,
#endif	 
#if (CORE2_TASK61_SWITCH == ON) 	
	 CORE2_TASK_ID61,
#endif	 
#if (CORE2_TASK62_SWITCH == ON) 	
	 CORE2_TASK_ID62,
#endif	 
#if (CORE2_TASK63_SWITCH == ON) 	
	 CORE2_TASK_ID63,
#endif	 
#if (CORE2_TASK64_SWITCH == ON) 	
	 CORE2_TASK_ID64,
#endif	 
#if (CORE2_TASK65_SWITCH == ON) 	
	 CORE2_TASK_ID65,
#endif	 
#if (CORE2_TASK66_SWITCH == ON) 	
	 CORE2_TASK_ID66,
#endif	 
#if (CORE2_TASK67_SWITCH == ON) 	
	 CORE2_TASK_ID67,
#endif	 
#if (CORE2_TASK68_SWITCH == ON) 	
	 CORE2_TASK_ID68,
#endif	 
#if (CORE2_TASK69_SWITCH == ON) 	
	 CORE2_TASK_ID69,
#endif	 
#if (CORE2_TASK70_SWITCH == ON) 	
	 CORE2_TASK_ID70,
#endif	 
#if (CORE2_TASK71_SWITCH == ON) 	
	 CORE2_TASK_ID71,
#endif	 
#if (CORE2_TASK72_SWITCH == ON) 	
	 CORE2_TASK_ID72,
#endif	 
#if (CORE2_TASK73_SWITCH == ON) 	
	 CORE2_TASK_ID73,
#endif	 
#if (CORE2_TASK74_SWITCH == ON) 	
	 CORE2_TASK_ID74,
#endif	 
#if (CORE2_TASK75_SWITCH == ON) 	
	 CORE2_TASK_ID75,
#endif	 
#if (CORE2_TASK76_SWITCH == ON) 	
	 CORE2_TASK_ID76,
#endif	 
#if (CORE2_TASK77_SWITCH == ON) 	
	 CORE2_TASK_ID77,
#endif	 
#if (CORE2_TASK78_SWITCH == ON) 	
	 CORE2_TASK_ID78,
#endif	 
#if (CORE2_TASK79_SWITCH == ON) 	
	 CORE2_TASK_ID79,
#endif	 
#if (CORE2_TASK80_SWITCH == ON) 	
	 CORE2_TASK_ID80,
#endif	 
#if (CORE2_TASK81_SWITCH == ON) 	
	 CORE2_TASK_ID81,
#endif	 
#if (CORE2_TASK82_SWITCH == ON) 	
	 CORE2_TASK_ID82,
#endif	 
#if (CORE2_TASK83_SWITCH == ON) 	
	 CORE2_TASK_ID83,
#endif	 
#if (CORE2_TASK84_SWITCH == ON) 	
	 CORE2_TASK_ID84,
#endif	 
#if (CORE2_TASK85_SWITCH == ON) 	
	 CORE2_TASK_ID85,
#endif	 
#if (CORE2_TASK86_SWITCH == ON) 	
	 CORE2_TASK_ID86,
#endif	 
#if (CORE2_TASK87_SWITCH == ON) 	
	 CORE2_TASK_ID87,
#endif	 
#if (CORE2_TASK88_SWITCH == ON) 	
	 CORE2_TASK_ID88,
#endif	 
#if (CORE2_TASK89_SWITCH == ON) 	
	 CORE2_TASK_ID89,
#endif	 
#if (CORE2_TASK90_SWITCH == ON) 	
	 CORE2_TASK_ID90,
#endif	 
#if (CORE2_TASK91_SWITCH == ON) 	
	 CORE2_TASK_ID91,
#endif	 
#if (CORE2_TASK92_SWITCH == ON) 	
	 CORE2_TASK_ID92,
#endif	 
#if (CORE2_TASK93_SWITCH == ON) 	
	 CORE2_TASK_ID93,
#endif	 
#if (CORE2_TASK94_SWITCH == ON) 	
	 CORE2_TASK_ID94,	
#endif	 
#if (CORE2_TASK95_SWITCH == ON) 	
	 CORE2_TASK_ID95,
#endif	 
#if (CORE2_TASK96_SWITCH == ON) 	
	 CORE2_TASK_ID96,
#endif	 
#if (CORE2_TASK97_SWITCH == ON) 	
	 CORE2_TASK_ID97,
#endif	 
#if (CORE2_TASK98_SWITCH == ON) 	
	 CORE2_TASK_ID98,
#endif	 
#if (CORE2_TASK99_SWITCH == ON) 	
	 CORE2_TASK_ID99,
#endif	 
#if (CORE2_TASK100_SWITCH == ON) 	
	 CORE2_TASK_ID100,
#endif	
	 CORE2_TASK_MAX_ID_NUM,
	 CORE2_NO_ACTIVED_TASK
}CORE2_TASK_ID_t;

/* core 0 */
/* 0 thread config initialization */ 
#if (CORE2_TASK0_SWITCH == ON) 
#define CORE2_TASK0_TYPE           NO_DEFINITION             
#define CORE2_TASK0_PERIOD         (0)  /* unit:ms */
#define CORE2_TASK0_ACTIVED        NO_ACTIVED_TASK
#define CORE2_TASK0_PRIORITY       LEVEL_0
#define CORE2_TASK0_MODE           SUPER
#define CORE2_TASK0_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK0_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64  
#endif	
#if (CORE2_TASK1_SWITCH == ON)
#define CORE2_TASK1_TYPE           PERIODIC
#define CORE2_TASK1_PERIOD         (300)  /* unit:ms */
#define CORE2_TASK1_ACTIVED        NO_ACTIVED_TASK
#define CORE2_TASK1_PRIORITY       LEVEL_1
#define CORE2_TASK1_MODE           SUPER
#define CORE2_TASK1_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK1_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK2_SWITCH == ON)
#define CORE2_TASK2_TYPE           PERIODIC
#define CORE2_TASK2_PERIOD         (500)  /* unit:ms */
#define CORE2_TASK2_ACTIVED        NO_ACTIVED_TASK
#define CORE2_TASK2_PRIORITY       LEVEL_2
#define CORE2_TASK2_MODE           SUPER
#define CORE2_TASK2_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK2_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK3_SWITCH == ON)
#define CORE2_TASK3_TYPE           EVENT
#define CORE2_TASK3_PERIOD         (0)
#define CORE2_TASK3_ACTIVED        CORE2_TASK_ID4
#define CORE2_TASK3_PRIORITY       LEVEL_3
#define CORE2_TASK3_MODE           SUPER
#define CORE2_TASK3_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK3_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK4_SWITCH == ON)
#define CORE2_TASK4_TYPE           EVENT
#define CORE2_TASK4_PERIOD         (0)
#define CORE2_TASK4_ACTIVED        CORE2_TASK_ID5
#define CORE2_TASK4_PRIORITY       LEVEL_4
#define CORE2_TASK4_MODE           SUPER
#define CORE2_TASK4_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK4_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK5_SWITCH == ON)
#define CORE2_TASK5_TYPE           EVENT
#define CORE2_TASK5_PERIOD         (0)
#define CORE2_TASK5_ACTIVED        CORE2_TASK_ID6
#define CORE2_TASK5_PRIORITY       LEVEL_5
#define CORE2_TASK5_MODE           SUPER
#define CORE2_TASK5_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK5_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK6_SWITCH == ON)
#define CORE2_TASK6_TYPE           EVENT
#define CORE2_TASK6_PERIOD         (0)
#define CORE2_TASK6_ACTIVED        CORE2_TASK_ID7
#define CORE2_TASK6_PRIORITY       LEVEL_6
#define CORE2_TASK6_MODE           SUPER
#define CORE2_TASK6_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK6_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK7_SWITCH == ON)
#define CORE2_TASK7_TYPE           EVENT
#define CORE2_TASK7_PERIOD         (0)
#define CORE2_TASK7_ACTIVED        CORE2_TASK_ID8
#define CORE2_TASK7_PRIORITY       LEVEL_7
#define CORE2_TASK7_MODE           SUPER
#define CORE2_TASK7_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK7_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK8_SWITCH == ON)
#define CORE2_TASK8_TYPE           EVENT
#define CORE2_TASK8_PERIOD         (0)
#define CORE2_TASK8_ACTIVED        CORE2_TASK_ID9
#define CORE2_TASK8_PRIORITY       LEVEL_8
#define CORE2_TASK8_MODE           SUPER
#define CORE2_TASK8_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK8_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK9_SWITCH == ON)
#define CORE2_TASK9_TYPE           EVENT
#define CORE2_TASK9_PERIOD         (0)
#define CORE2_TASK9_ACTIVED        NO_ACTIVED_TASK
#define CORE2_TASK9_PRIORITY       LEVEL_9
#define CORE2_TASK9_MODE           SUPER
#define CORE2_TASK9_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK9_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK10_SWITCH == ON)
#define CORE2_TASK10_TYPE          PERIODIC
#define CORE2_TASK10_PERIOD        (1000)  /* unit:ms */
#define CORE2_TASK10_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK10_PRIORITY      LEVEL_10
#define CORE2_TASK10_MODE          SUPER
#define CORE2_TASK10_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK10_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK11_SWITCH == ON)
#define CORE2_TASK11_TYPE          PERIODIC
#define CORE2_TASK11_PERIOD        (300)  /* unit:ms */
#define CORE2_TASK11_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK11_PRIORITY      LEVEL_1
#define CORE2_TASK11_MODE          SUPER
#define CORE2_TASK11_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK11_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK12_SWITCH == ON)
#define CORE2_TASK12_TYPE          PERIODIC
#define CORE2_TASK12_PERIOD        (500)  /* unit:ms */
#define CORE2_TASK12_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK12_PRIORITY      LEVEL_2
#define CORE2_TASK12_MODE          SUPER
#define CORE2_TASK12_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK12_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK13_SWITCH == ON)
#define CORE2_TASK13_TYPE          EVENT
#define CORE2_TASK13_PERIOD        (0)
#define CORE2_TASK13_ACTIVED       CORE2_TASK_ID4
#define CORE2_TASK13_PRIORITY      LEVEL_3
#define CORE2_TASK13_MODE          SUPER
#define CORE2_TASK13_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK13_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK14_SWITCH == ON)
#define CORE2_TASK14_TYPE          EVENT
#define CORE2_TASK14_PERIOD        (0)
#define CORE2_TASK14_ACTIVED       CORE2_TASK_ID5
#define CORE2_TASK14_PRIORITY      LEVEL_4
#define CORE2_TASK14_MODE          SUPER
#define CORE2_TASK14_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK14_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK15_SWITCH == ON)
#define CORE2_TASK15_TYPE          EVENT
#define CORE2_TASK15_PERIOD        (0)
#define CORE2_TASK15_ACTIVED       CORE2_TASK_ID6
#define CORE2_TASK15_PRIORITY      LEVEL_5
#define CORE2_TASK15_MODE          SUPER
#define CORE2_TASK15_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK15_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK16_SWITCH == ON)
#define CORE2_TASK16_TYPE          EVENT
#define CORE2_TASK16_PERIOD        (0)
#define CORE2_TASK16_ACTIVED       CORE2_TASK_ID7
#define CORE2_TASK16_PRIORITY      LEVEL_6
#define CORE2_TASK16_MODE          SUPER
#define CORE2_TASK16_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK16_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK17_SWITCH == ON)
#define CORE2_TASK17_TYPE          EVENT
#define CORE2_TASK17_PERIOD        (0)
#define CORE2_TASK17_ACTIVED       CORE2_TASK_ID8
#define CORE2_TASK17_PRIORITY      LEVEL_7
#define CORE2_TASK17_MODE          SUPER
#define CORE2_TASK17_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK17_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK18_SWITCH == ON)
#define CORE2_TASK18_TYPE          EVENT
#define CORE2_TASK18_PERIOD        (0)
#define CORE2_TASK18_ACTIVED       CORE2_TASK_ID9
#define CORE2_TASK18_PRIORITY      LEVEL_8
#define CORE2_TASK18_MODE          SUPER
#define CORE2_TASK18_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK18_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK19_SWITCH == ON)
#define CORE2_TASK19_TYPE          EVENT
#define CORE2_TASK19_PERIOD        (0)
#define CORE2_TASK19_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK19_PRIORITY      LEVEL_9
#define CORE2_TASK19_MODE          SUPER
#define CORE2_TASK19_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK19_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK20_SWITCH == ON)
#define CORE2_TASK20_TYPE          PERIODIC
#define CORE2_TASK20_PERIOD        (1000)  /* unit:ms */
#define CORE2_TASK20_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK20_PRIORITY      LEVEL_10
#define CORE2_TASK20_MODE          SUPER
#define CORE2_TASK20_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK20_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK21_SWITCH == ON)
#define CORE2_TASK21_TYPE          PERIODIC
#define CORE2_TASK21_PERIOD        (300)  /* unit:ms */
#define CORE2_TASK21_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK21_PRIORITY      LEVEL_1
#define CORE2_TASK21_MODE          SUPER
#define CORE2_TASK21_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK21_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK22_SWITCH == ON)
#define CORE2_TASK22_TYPE          PERIODIC
#define CORE2_TASK22_PERIOD        (500)  /* unit:ms */
#define CORE2_TASK22_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK22_PRIORITY      LEVEL_2
#define CORE2_TASK22_MODE          SUPER
#define CORE2_TASK22_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK22_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK23_SWITCH == ON)
#define CORE2_TASK23_TYPE          EVENT
#define CORE2_TASK23_PERIOD        (0)
#define CORE2_TASK23_ACTIVED       CORE2_TASK_ID4
#define CORE2_TASK23_PRIORITY      LEVEL_3
#define CORE2_TASK23_MODE          SUPER
#define CORE2_TASK23_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK23_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK24_SWITCH == ON)
#define CORE2_TASK24_TYPE          EVENT
#define CORE2_TASK24_PERIOD        (0)
#define CORE2_TASK24_ACTIVED       CORE2_TASK_ID5
#define CORE2_TASK24_PRIORITY      LEVEL_4
#define CORE2_TASK24_MODE          SUPER
#define CORE2_TASK24_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK24_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK25_SWITCH == ON)
#define CORE2_TASK25_TYPE          EVENT
#define CORE2_TASK25_PERIOD        (0)
#define CORE2_TASK25_ACTIVED       CORE2_TASK_ID6
#define CORE2_TASK25_PRIORITY      LEVEL_5
#define CORE2_TASK25_MODE          SUPER
#define CORE2_TASK25_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK25_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK26_SWITCH == ON)
#define CORE2_TASK26_TYPE          EVENT
#define CORE2_TASK26_PERIOD        (0)
#define CORE2_TASK26_ACTIVED       CORE2_TASK_ID7
#define CORE2_TASK26_PRIORITY      LEVEL_6
#define CORE2_TASK26_MODE          SUPER
#define CORE2_TASK26_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK26_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK27_SWITCH == ON)
#define CORE2_TASK27_TYPE          EVENT
#define CORE2_TASK27_PERIOD        (0)
#define CORE2_TASK27_ACTIVED       CORE2_TASK_ID8
#define CORE2_TASK27_PRIORITY      LEVEL_7
#define CORE2_TASK27_MODE          SUPER
#define CORE2_TASK27_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK27_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK28_SWITCH == ON)
#define CORE2_TASK28_TYPE          EVENT
#define CORE2_TASK28_PERIOD        (0)
#define CORE2_TASK28_ACTIVED       CORE2_TASK_ID9
#define CORE2_TASK28_PRIORITY      LEVEL_8
#define CORE2_TASK28_MODE          SUPER
#define CORE2_TASK28_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK28_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK29_SWITCH == ON)
#define CORE2_TASK29_TYPE          EVENT
#define CORE2_TASK29_PERIOD        (0)
#define CORE2_TASK29_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK29_PRIORITY      LEVEL_9
#define CORE2_TASK29_MODE          SUPER
#define CORE2_TASK29_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK29_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK30_SWITCH == ON)
#define CORE2_TASK30_TYPE          PERIODIC
#define CORE2_TASK30_PERIOD        (1000)  /* unit:ms */
#define CORE2_TASK30_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK30_PRIORITY      LEVEL_10
#define CORE2_TASK30_MODE          SUPER
#define CORE2_TASK30_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK30_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK31_SWITCH == ON)
#define CORE2_TASK31_TYPE          PERIODIC
#define CORE2_TASK31_PERIOD        (300)  /* unit:ms */
#define CORE2_TASK31_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK31_PRIORITY      LEVEL_1
#define CORE2_TASK31_MODE          SUPER
#define CORE2_TASK31_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK31_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK32_SWITCH == ON)
#define CORE2_TASK32_TYPE          PERIODIC
#define CORE2_TASK32_PERIOD        (500)  /* unit:ms */
#define CORE2_TASK32_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK32_PRIORITY      LEVEL_2
#define CORE2_TASK32_MODE          SUPER
#define CORE2_TASK32_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK32_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK33_SWITCH == ON)
#define CORE2_TASK33_TYPE          EVENT
#define CORE2_TASK33_PERIOD        (0)
#define CORE2_TASK33_ACTIVED       CORE2_TASK_ID4
#define CORE2_TASK33_PRIORITY      LEVEL_3
#define CORE2_TASK33_MODE          SUPER
#define CORE2_TASK33_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK33_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK34_SWITCH == ON)
#define CORE2_TASK34_TYPE          EVENT
#define CORE2_TASK34_PERIOD        (0)
#define CORE2_TASK34_ACTIVED       CORE2_TASK_ID5
#define CORE2_TASK34_PRIORITY      LEVEL_4
#define CORE2_TASK34_MODE          SUPER
#define CORE2_TASK34_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK34_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK35_SWITCH == ON)
#define CORE2_TASK35_TYPE          EVENT
#define CORE2_TASK35_PERIOD        (0)
#define CORE2_TASK35_ACTIVED       CORE2_TASK_ID6
#define CORE2_TASK35_PRIORITY      LEVEL_5
#define CORE2_TASK35_MODE          SUPER
#define CORE2_TASK35_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK35_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK36_SWITCH == ON)
#define CORE2_TASK36_TYPE          EVENT
#define CORE2_TASK36_PERIOD        (0)
#define CORE2_TASK36_ACTIVED       CORE2_TASK_ID7
#define CORE2_TASK36_PRIORITY      LEVEL_6
#define CORE2_TASK36_MODE          SUPER
#define CORE2_TASK36_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK36_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK37_SWITCH == ON)
#define CORE2_TASK37_TYPE          EVENT
#define CORE2_TASK37_PERIOD        (0)
#define CORE2_TASK37_ACTIVED       CORE2_TASK_ID8
#define CORE2_TASK37_PRIORITY      LEVEL_7
#define CORE2_TASK37_MODE          SUPER
#define CORE2_TASK37_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK37_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK38_SWITCH == ON)
#define CORE2_TASK38_TYPE          EVENT
#define CORE2_TASK38_PERIOD        (0)
#define CORE2_TASK38_ACTIVED       CORE2_TASK_ID9
#define CORE2_TASK38_PRIORITY      LEVEL_8
#define CORE2_TASK38_MODE          SUPER
#define CORE2_TASK38_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK38_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK39_SWITCH == ON)
#define CORE2_TASK39_TYPE          EVENT
#define CORE2_TASK39_PERIOD        (0)
#define CORE2_TASK39_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK39_PRIORITY      LEVEL_9
#define CORE2_TASK39_MODE          SUPER
#define CORE2_TASK39_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK39_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK40_SWITCH == ON)
#define CORE2_TASK40_TYPE          PERIODIC
#define CORE2_TASK40_PERIOD        (1000)  /* unit:ms */
#define CORE2_TASK40_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK40_PRIORITY      LEVEL_10
#define CORE2_TASK40_MODE          SUPER
#define CORE2_TASK40_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK40_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK41_SWITCH == ON)
#define CORE2_TASK41_TYPE          PERIODIC
#define CORE2_TASK41_PERIOD        (300)  /* unit:ms */
#define CORE2_TASK41_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK41_PRIORITY      LEVEL_1
#define CORE2_TASK41_MODE          SUPER
#define CORE2_TASK41_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK41_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK42_SWITCH == ON)
#define CORE2_TASK42_TYPE          PERIODIC
#define CORE2_TASK42_PERIOD        (500)  /* unit:ms */
#define CORE2_TASK42_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK42_PRIORITY      LEVEL_2
#define CORE2_TASK42_MODE          SUPER
#define CORE2_TASK42_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK42_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK43_SWITCH == ON)
#define CORE2_TASK43_TYPE          EVENT
#define CORE2_TASK43_PERIOD        (0)
#define CORE2_TASK43_ACTIVED       CORE2_TASK_ID4
#define CORE2_TASK43_PRIORITY      LEVEL_3
#define CORE2_TASK43_MODE          SUPER
#define CORE2_TASK43_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK43_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK44_SWITCH == ON)
#define CORE2_TASK44_TYPE          EVENT
#define CORE2_TASK44_PERIOD        (0)
#define CORE2_TASK44_ACTIVED       CORE2_TASK_ID5
#define CORE2_TASK44_PRIORITY      LEVEL_4
#define CORE2_TASK44_MODE          SUPER
#define CORE2_TASK44_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK44_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK45_SWITCH == ON)
#define CORE2_TASK45_TYPE          EVENT
#define CORE2_TASK45_PERIOD        (0)
#define CORE2_TASK45_ACTIVED       CORE2_TASK_ID6
#define CORE2_TASK45_PRIORITY      LEVEL_5
#define CORE2_TASK45_MODE          SUPER
#define CORE2_TASK45_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK45_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK46_SWITCH == ON)
#define CORE2_TASK46_TYPE          EVENT
#define CORE2_TASK46_PERIOD        (0)
#define CORE2_TASK46_ACTIVED       CORE2_TASK_ID7
#define CORE2_TASK46_PRIORITY      LEVEL_6
#define CORE2_TASK46_MODE          SUPER
#define CORE2_TASK46_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK46_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK47_SWITCH == ON)
#define CORE2_TASK47_TYPE          EVENT
#define CORE2_TASK47_PERIOD        (0)
#define CORE2_TASK47_ACTIVED       CORE2_TASK_ID8
#define CORE2_TASK47_PRIORITY      LEVEL_7
#define CORE2_TASK47_MODE          SUPER
#define CORE2_TASK47_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK47_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK48_SWITCH == ON)
#define CORE2_TASK48_TYPE          EVENT
#define CORE2_TASK48_PERIOD        (0)
#define CORE2_TASK48_ACTIVED       CORE2_TASK_ID9
#define CORE2_TASK48_PRIORITY      LEVEL_8
#define CORE2_TASK48_MODE          SUPER
#define CORE2_TASK48_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK48_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK49_SWITCH == ON)
#define CORE2_TASK49_TYPE          EVENT
#define CORE2_TASK49_PERIOD        (0)
#define CORE2_TASK49_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK49_PRIORITY      LEVEL_9
#define CORE2_TASK49_MODE          SUPER
#define CORE2_TASK49_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK49_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK50_SWITCH == ON)
#define CORE2_TASK50_TYPE          PERIODIC
#define CORE2_TASK50_PERIOD        (1000)  /* unit:ms */
#define CORE2_TASK50_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK50_PRIORITY      LEVEL_10
#define CORE2_TASK50_MODE          SUPER
#define CORE2_TASK50_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK50_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK51_SWITCH == ON)
#define CORE2_TASK51_TYPE          PERIODIC
#define CORE2_TASK51_PERIOD        (300)  /* unit:ms */
#define CORE2_TASK51_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK51_PRIORITY      LEVEL_1
#define CORE2_TASK51_MODE          SUPER
#define CORE2_TASK51_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK51_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK52_SWITCH == ON)
#define CORE2_TASK52_TYPE          PERIODIC
#define CORE2_TASK52_PERIOD        (500)  /* unit:ms */
#define CORE2_TASK52_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK52_PRIORITY      LEVEL_2
#define CORE2_TASK52_MODE          SUPER
#define CORE2_TASK52_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK52_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK53_SWITCH == ON)
#define CORE2_TASK53_TYPE          EVENT
#define CORE2_TASK53_PERIOD        (0)
#define CORE2_TASK53_ACTIVED       CORE2_TASK_ID4
#define CORE2_TASK53_PRIORITY      LEVEL_3
#define CORE2_TASK53_MODE          SUPER
#define CORE2_TASK53_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK53_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK54_SWITCH == ON)
#define CORE2_TASK54_TYPE          EVENT
#define CORE2_TASK54_PERIOD        (0)
#define CORE2_TASK54_ACTIVED       CORE2_TASK_ID5
#define CORE2_TASK54_PRIORITY      LEVEL_4
#define CORE2_TASK54_MODE          SUPER
#define CORE2_TASK54_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK54_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK55_SWITCH == ON)
#define CORE2_TASK55_TYPE          EVENT
#define CORE2_TASK55_PERIOD        (0)
#define CORE2_TASK55_ACTIVED       CORE2_TASK_ID6
#define CORE2_TASK55_PRIORITY      LEVEL_5
#define CORE2_TASK55_MODE          SUPER
#define CORE2_TASK55_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK55_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK56_SWITCH == ON)
#define CORE2_TASK56_TYPE          EVENT
#define CORE2_TASK56_PERIOD        (0)
#define CORE2_TASK56_ACTIVED       CORE2_TASK_ID7
#define CORE2_TASK56_PRIORITY      LEVEL_6
#define CORE2_TASK56_MODE          SUPER
#define CORE2_TASK56_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK56_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK57_SWITCH == ON)
#define CORE2_TASK57_TYPE          EVENT
#define CORE2_TASK57_PERIOD        (0)
#define CORE2_TASK57_ACTIVED       CORE2_TASK_ID8
#define CORE2_TASK57_PRIORITY      LEVEL_7
#define CORE2_TASK57_MODE          SUPER
#define CORE2_TASK57_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK57_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK58_SWITCH == ON)
#define CORE2_TASK58_TYPE          EVENT
#define CORE2_TASK58_PERIOD        (0)
#define CORE2_TASK58_ACTIVED       CORE2_TASK_ID9
#define CORE2_TASK58_PRIORITY      LEVEL_8
#define CORE2_TASK58_MODE          SUPER
#define CORE2_TASK58_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK58_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK59_SWITCH == ON)
#define CORE2_TASK59_TYPE          EVENT
#define CORE2_TASK59_PERIOD        (0)
#define CORE2_TASK59_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK59_PRIORITY      LEVEL_9
#define CORE2_TASK59_MODE          SUPER
#define CORE2_TASK59_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK59_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK60_SWITCH == ON)
#define CORE2_TASK60_TYPE          PERIODIC
#define CORE2_TASK60_PERIOD        (1000)  /* unit:ms */
#define CORE2_TASK60_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK60_PRIORITY      LEVEL_10
#define CORE2_TASK60_MODE          SUPER
#define CORE2_TASK60_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK60_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK61_SWITCH == ON)
#define CORE2_TASK61_TYPE          PERIODIC
#define CORE2_TASK61_PERIOD        (300)  /* unit:ms */
#define CORE2_TASK61_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK61_PRIORITY      LEVEL_1
#define CORE2_TASK61_MODE          SUPER
#define CORE2_TASK61_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK61_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK62_SWITCH == ON)
#define CORE2_TASK62_TYPE          PERIODIC
#define CORE2_TASK62_PERIOD        (500)  /* unit:ms */
#define CORE2_TASK62_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK62_PRIORITY      LEVEL_2
#define CORE2_TASK62_MODE          SUPER
#define CORE2_TASK62_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK62_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK63_SWITCH == ON)
#define CORE2_TASK63_TYPE          EVENT
#define CORE2_TASK63_PERIOD        (0)
#define CORE2_TASK63_ACTIVED       CORE2_TASK_ID4
#define CORE2_TASK63_PRIORITY      LEVEL_3
#define CORE2_TASK63_MODE          SUPER
#define CORE2_TASK63_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK63_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK64_SWITCH == ON)
#define CORE2_TASK64_TYPE          EVENT
#define CORE2_TASK64_PERIOD        (0)
#define CORE2_TASK64_ACTIVED       CORE2_TASK_ID5
#define CORE2_TASK64_PRIORITY      LEVEL_4
#define CORE2_TASK64_MODE          SUPER
#define CORE2_TASK64_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK64_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK65_SWITCH == ON)
#define CORE2_TASK65_TYPE          EVENT
#define CORE2_TASK65_PERIOD        (0)
#define CORE2_TASK65_ACTIVED       CORE2_TASK_ID6
#define CORE2_TASK65_PRIORITY      LEVEL_5
#define CORE2_TASK65_MODE          SUPER
#define CORE2_TASK65_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK65_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK66_SWITCH == ON)
#define CORE2_TASK66_TYPE          EVENT
#define CORE2_TASK66_PERIOD        (0)
#define CORE2_TASK66_ACTIVED       CORE2_TASK_ID7
#define CORE2_TASK66_PRIORITY      LEVEL_6
#define CORE2_TASK66_MODE          SUPER
#define CORE2_TASK66_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK66_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK67_SWITCH == ON)
#define CORE2_TASK67_TYPE          EVENT
#define CORE2_TASK67_PERIOD        (0)
#define CORE2_TASK67_ACTIVED       CORE2_TASK_ID8
#define CORE2_TASK67_PRIORITY      LEVEL_7
#define CORE2_TASK67_MODE          SUPER
#define CORE2_TASK67_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK67_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK68_SWITCH == ON)
#define CORE2_TASK68_TYPE          EVENT
#define CORE2_TASK68_PERIOD        (0)
#define CORE2_TASK68_ACTIVED       CORE2_TASK_ID9
#define CORE2_TASK68_PRIORITY      LEVEL_8
#define CORE2_TASK68_MODE          SUPER
#define CORE2_TASK68_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK68_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK69_SWITCH == ON)
#define CORE2_TASK69_TYPE          EVENT
#define CORE2_TASK69_PERIOD        (0)
#define CORE2_TASK69_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK69_PRIORITY      LEVEL_9
#define CORE2_TASK69_MODE          SUPER
#define CORE2_TASK69_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK69_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK70_SWITCH == ON)
#define CORE2_TASK70_TYPE          PERIODIC
#define CORE2_TASK70_PERIOD        (1000)  /* unit:ms */
#define CORE2_TASK70_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK70_PRIORITY      LEVEL_10
#define CORE2_TASK70_MODE          SUPER
#define CORE2_TASK70_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK70_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK71_SWITCH == ON)
#define CORE2_TASK71_TYPE          PERIODIC
#define CORE2_TASK71_PERIOD        (300)  /* unit:ms */
#define CORE2_TASK71_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK71_PRIORITY      LEVEL_1
#define CORE2_TASK71_MODE          SUPER
#define CORE2_TASK71_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK71_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK72_SWITCH == ON)
#define CORE2_TASK72_TYPE          PERIODIC
#define CORE2_TASK72_PERIOD        (500)  /* unit:ms */
#define CORE2_TASK72_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK72_PRIORITY      LEVEL_2
#define CORE2_TASK72_MODE          SUPER
#define CORE2_TASK72_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK72_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK73_SWITCH == ON)
#define CORE2_TASK73_TYPE          EVENT
#define CORE2_TASK73_PERIOD        (0)
#define CORE2_TASK73_ACTIVED       CORE2_TASK_ID4
#define CORE2_TASK73_PRIORITY      LEVEL_3
#define CORE2_TASK73_MODE          SUPER
#define CORE2_TASK73_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK73_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK74_SWITCH == ON)
#define CORE2_TASK74_TYPE          EVENT
#define CORE2_TASK74_PERIOD        (0)
#define CORE2_TASK74_ACTIVED       CORE2_TASK_ID5
#define CORE2_TASK74_PRIORITY      LEVEL_4
#define CORE2_TASK74_MODE          SUPER
#define CORE2_TASK74_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK74_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK75_SWITCH == ON)
#define CORE2_TASK75_TYPE          EVENT
#define CORE2_TASK75_PERIOD        (0)
#define CORE2_TASK75_ACTIVED       CORE2_TASK_ID6
#define CORE2_TASK75_PRIORITY      LEVEL_5
#define CORE2_TASK75_MODE          SUPER
#define CORE2_TASK75_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK75_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK76_SWITCH == ON)
#define CORE2_TASK76_TYPE          EVENT
#define CORE2_TASK76_PERIOD        (0)
#define CORE2_TASK76_ACTIVED       CORE2_TASK_ID7
#define CORE2_TASK76_PRIORITY      LEVEL_6
#define CORE2_TASK76_MODE          SUPER
#define CORE2_TASK76_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK76_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK77_SWITCH == ON)
#define CORE2_TASK77_TYPE          EVENT
#define CORE2_TASK77_PERIOD        (0)
#define CORE2_TASK77_ACTIVED       CORE2_TASK_ID8
#define CORE2_TASK77_PRIORITY      LEVEL_7
#define CORE2_TASK77_MODE          SUPER
#define CORE2_TASK77_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK77_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK78_SWITCH == ON)
#define CORE2_TASK78_TYPE          EVENT
#define CORE2_TASK78_PERIOD        (0)
#define CORE2_TASK78_ACTIVED       CORE2_TASK_ID9
#define CORE2_TASK78_PRIORITY      LEVEL_8
#define CORE2_TASK78_MODE          SUPER
#define CORE2_TASK78_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK78_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK79_SWITCH == ON)
#define CORE2_TASK79_TYPE          EVENT
#define CORE2_TASK79_PERIOD        (0)
#define CORE2_TASK79_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK79_PRIORITY      LEVEL_9
#define CORE2_TASK79_MODE          SUPER
#define CORE2_TASK79_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK79_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK80_SWITCH == ON)
#define CORE2_TASK80_TYPE          PERIODIC
#define CORE2_TASK80_PERIOD        (1000)  /* unit:ms */
#define CORE2_TASK80_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK80_PRIORITY      LEVEL_10
#define CORE2_TASK80_MODE          SUPER
#define CORE2_TASK80_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK80_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK81_SWITCH == ON)
#define CORE2_TASK81_TYPE          PERIODIC
#define CORE2_TASK81_PERIOD        (300)  /* unit:ms */
#define CORE2_TASK81_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK81_PRIORITY      LEVEL_1
#define CORE2_TASK81_MODE          SUPER
#define CORE2_TASK81_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK81_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK82_SWITCH == ON)
#define CORE2_TASK82_TYPE          PERIODIC
#define CORE2_TASK82_PERIOD        (500)  /* unit:ms */
#define CORE2_TASK82_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK82_PRIORITY      LEVEL_2
#define CORE2_TASK82_MODE          SUPER
#define CORE2_TASK82_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK82_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK83_SWITCH == ON)
#define CORE2_TASK83_TYPE          EVENT
#define CORE2_TASK83_PERIOD        (0)
#define CORE2_TASK83_ACTIVED       CORE2_TASK_ID4
#define CORE2_TASK83_PRIORITY      LEVEL_3
#define CORE2_TASK83_MODE          SUPER
#define CORE2_TASK83_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK83_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK84_SWITCH == ON)
#define CORE2_TASK84_TYPE          EVENT
#define CORE2_TASK84_PERIOD        (0)
#define CORE2_TASK84_ACTIVED       CORE2_TASK_ID5
#define CORE2_TASK84_PRIORITY      LEVEL_4
#define CORE2_TASK84_MODE          SUPER
#define CORE2_TASK84_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK84_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK85_SWITCH == ON)
#define CORE2_TASK85_TYPE          EVENT
#define CORE2_TASK85_PERIOD        (0)
#define CORE2_TASK85_ACTIVED       CORE2_TASK_ID6
#define CORE2_TASK85_PRIORITY      LEVEL_5
#define CORE2_TASK85_MODE          SUPER
#define CORE2_TASK85_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK85_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK86_SWITCH == ON)
#define CORE2_TASK86_TYPE          EVENT
#define CORE2_TASK86_PERIOD        (0)
#define CORE2_TASK86_ACTIVED       CORE2_TASK_ID7
#define CORE2_TASK86_PRIORITY      LEVEL_6
#define CORE2_TASK86_MODE          SUPER
#define CORE2_TASK86_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK86_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK87_SWITCH == ON)
#define CORE2_TASK87_TYPE          EVENT
#define CORE2_TASK87_PERIOD        (0)
#define CORE2_TASK87_ACTIVED       CORE2_TASK_ID8
#define CORE2_TASK87_PRIORITY      LEVEL_7
#define CORE2_TASK87_MODE          SUPER
#define CORE2_TASK87_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK87_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK88_SWITCH == ON)
#define CORE2_TASK88_TYPE          EVENT
#define CORE2_TASK88_PERIOD        (0)
#define CORE2_TASK88_ACTIVED       CORE2_TASK_ID9
#define CORE2_TASK88_PRIORITY      LEVEL_8
#define CORE2_TASK88_MODE          SUPER
#define CORE2_TASK88_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK88_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK89_SWITCH == ON)
#define CORE2_TASK89_TYPE          EVENT
#define CORE2_TASK89_PERIOD        (0)
#define CORE2_TASK89_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK89_PRIORITY      LEVEL_9
#define CORE2_TASK89_MODE          SUPER
#define CORE2_TASK89_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK89_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK90_SWITCH == ON)
#define CORE2_TASK90_TYPE          PERIODIC
#define CORE2_TASK90_PERIOD        (1000)  /* unit:ms */
#define CORE2_TASK90_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK90_PRIORITY      LEVEL_10
#define CORE2_TASK90_MODE          SUPER
#define CORE2_TASK90_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK90_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK91_SWITCH == ON)
#define CORE2_TASK91_TYPE          PERIODIC
#define CORE2_TASK91_PERIOD        (300)  /* unit:ms */
#define CORE2_TASK91_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK91_PRIORITY      LEVEL_1
#define CORE2_TASK91_MODE          SUPER
#define CORE2_TASK91_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK91_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK92_SWITCH == ON)
#define CORE2_TASK92_TYPE          PERIODIC
#define CORE2_TASK92_PERIOD        (500)  /* unit:ms */
#define CORE2_TASK92_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK92_PRIORITY      LEVEL_2
#define CORE2_TASK92_MODE          SUPER
#define CORE2_TASK92_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK92_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK93_SWITCH == ON)
#define CORE2_TASK93_TYPE          EVENT
#define CORE2_TASK93_PERIOD        (0)
#define CORE2_TASK93_ACTIVED       CORE2_TASK_ID4
#define CORE2_TASK93_PRIORITY      LEVEL_3
#define CORE2_TASK93_MODE          SUPER
#define CORE2_TASK93_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK93_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK94_SWITCH == ON)
#define CORE2_TASK94_TYPE          EVENT
#define CORE2_TASK94_PERIOD        (0)
#define CORE2_TASK94_ACTIVED       CORE2_TASK_ID5
#define CORE2_TASK94_PRIORITY      LEVEL_4
#define CORE2_TASK94_MODE          SUPER
#define CORE2_TASK94_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK94_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK95_SWITCH == ON)
#define CORE2_TASK95_TYPE          EVENT
#define CORE2_TASK95_PERIOD        (0)
#define CORE2_TASK95_ACTIVED       CORE2_TASK_ID6
#define CORE2_TASK95_PRIORITY      LEVEL_5
#define CORE2_TASK95_MODE          SUPER
#define CORE2_TASK95_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK95_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK96_SWITCH == ON)
#define CORE2_TASK96_TYPE          EVENT
#define CORE2_TASK96_PERIOD        (0)
#define CORE2_TASK96_ACTIVED       CORE2_TASK_ID7
#define CORE2_TASK96_PRIORITY      LEVEL_6
#define CORE2_TASK96_MODE          SUPER
#define CORE2_TASK96_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK96_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK97_SWITCH == ON)
#define CORE2_TASK97_TYPE          EVENT
#define CORE2_TASK97_PERIOD        (0)
#define CORE2_TASK97_ACTIVED       CORE2_TASK_ID8
#define CORE2_TASK97_PRIORITY      LEVEL_7
#define CORE2_TASK97_MODE          SUPER
#define CORE2_TASK97_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK97_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK98_SWITCH == ON)
#define CORE2_TASK98_TYPE          EVENT
#define CORE2_TASK98_PERIOD        (0)
#define CORE2_TASK98_ACTIVED       CORE2_TASK_ID9
#define CORE2_TASK98_PRIORITY      LEVEL_8
#define CORE2_TASK98_MODE          SUPER
#define CORE2_TASK98_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK98_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK99_SWITCH == ON)
#define CORE2_TASK99_TYPE          EVENT
#define CORE2_TASK99_PERIOD        (0)
#define CORE2_TASK99_ACTIVED       NO_ACTIVED_TASK
#define CORE2_TASK99_PRIORITY      LEVEL_9
#define CORE2_TASK99_MODE          SUPER
#define CORE2_TASK99_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK99_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE2_TASK100_SWITCH == ON)
#define CORE2_TASK100_TYPE         PERIODIC
#define CORE2_TASK100_PERIOD       (1000)  /* unit:ms */
#define CORE2_TASK100_ACTIVED      NO_ACTIVED_TASK
#define CORE2_TASK100_PRIORITY     LEVEL_10
#define CORE2_TASK100_MODE         SUPER
#define CORE2_TASK100_STACK_SIZE   PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK100_CALL_DEPTH   CALL_DEPTH_OVERFLOW_AT_64 
#endif	

#endif	

