
#ifndef TASK_CFG_H_
#define TASK_CFG_H_

/* core 0*/
/* 0 thread config initialization */ 
#define CORE0_TASK0_TYPE           NO_DEFINITION             
#define CORE0_TASK0_PERIOD         (0)  /* unit:ms */
#define CORE0_TASK0_ACTIVED        NO_THREAD
#define CORE0_TASK0_PRIORITY       LEVEL_0
#define CORE0_TASK0_MODE           SUPER
#define CORE0_TASK0_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE0_TASK0_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64  

#define CORE0_TASK1_TYPE           PERIODIC
#define CORE0_TASK1_PERIOD         (300)  /* unit:ms */
#define CORE0_TASK1_ACTIVED        NO_THREAD
#define CORE0_TASK1_PRIORITY       LEVEL_1
#define CORE0_TASK1_MODE           SUPER
#define CORE0_TASK1_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE0_TASK1_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 

#define CORE0_TASK2_TYPE           PERIODIC
#define CORE0_TASK2_PERIOD         (500)  /* unit:ms */
#define CORE0_TASK2_ACTIVED        NO_THREAD
#define CORE0_TASK2_PRIORITY       LEVEL_2
#define CORE0_TASK2_MODE           SUPER
#define CORE0_TASK2_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE0_TASK2_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 

#define CORE0_TASK3_TYPE           EVENT
#define CORE0_TASK3_PERIOD         (0)
#define CORE0_TASK3_ACTIVED        THREAD_ID4
#define CORE0_TASK3_PRIORITY       LEVEL_3
#define CORE0_TASK3_MODE           SUPER
#define CORE0_TASK3_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE0_TASK3_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 

#define CORE0_TASK4_TYPE           EVENT
#define CORE0_TASK4_PERIOD         (0)
#define CORE0_TASK4_ACTIVED        THREAD_ID5
#define CORE0_TASK4_PRIORITY       LEVEL_4
#define CORE0_TASK4_MODE           SUPER
#define CORE0_TASK4_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE0_TASK4_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 

#define CORE0_TASK5_TYPE           EVENT
#define CORE0_TASK5_PERIOD         (0)
#define CORE0_TASK5_ACTIVED        THREAD_ID6
#define CORE0_TASK5_PRIORITY       LEVEL_5
#define CORE0_TASK5_MODE           SUPER
#define CORE0_TASK5_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE0_TASK5_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 

#define CORE0_TASK6_TYPE           EVENT
#define CORE0_TASK6_PERIOD         (0)
#define CORE0_TASK6_ACTIVED        THREAD_ID7
#define CORE0_TASK6_PRIORITY       LEVEL_6
#define CORE0_TASK6_MODE           SUPER
#define CORE0_TASK6_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE0_TASK6_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 

#define CORE0_TASK7_TYPE           EVENT
#define CORE0_TASK7_PERIOD         (0)
#define CORE0_TASK7_ACTIVED        THREAD_ID8
#define CORE0_TASK7_PRIORITY       LEVEL_7
#define CORE0_TASK7_MODE           SUPER
#define CORE0_TASK7_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE0_TASK7_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 

#define CORE0_TASK8_TYPE           EVENT
#define CORE0_TASK8_PERIOD         (0)
#define CORE0_TASK8_ACTIVED        THREAD_ID9
#define CORE0_TASK8_PRIORITY       LEVEL_8
#define CORE0_TASK8_MODE           SUPER
#define CORE0_TASK8_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE0_TASK8_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 

#define CORE0_TASK9_TYPE           EVENT
#define CORE0_TASK9_PERIOD         (0)
#define CORE0_TASK9_ACTIVED        NO_THREAD
#define CORE0_TASK9_PRIORITY       LEVEL_9
#define CORE0_TASK9_MODE           SUPER
#define CORE0_TASK9_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE0_TASK9_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 

#define CORE0_TASK10_TYPE          PERIODIC
#define CORE0_TASK10_PERIOD        (1000)  /* unit:ms */
#define CORE0_TASK10_ACTIVED       NO_THREAD
#define CORE0_TASK10_PRIORITY      LEVEL_10
#define CORE0_TASK10_MODE          SUPER
#define CORE0_TASK10_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE0_TASK10_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 

/* core 1                      */
#define CORE1_TASK0_TYPE           NO_DEFINITION             
#define CORE1_TASK0_PERIOD         (0)  /* unit:ms */
#define CORE1_TASK0_ACTIVED        NO_THREAD
#define CORE1_TASK0_PRIORITY       LEVEL_0
#define CORE1_TASK0_MODE           SUPER
#define CORE1_TASK0_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK0_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 

#define CORE1_TASK1_TYPE           PERIODIC
#define CORE1_TASK1_PERIOD         (1000)  /* unit:ms */
#define CORE1_TASK1_ACTIVED        NO_THREAD
#define CORE1_TASK1_PRIORITY       LEVEL_1
#define CORE1_TASK1_MODE           SUPER
#define CORE1_TASK1_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK1_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 

#define CORE1_TASK2_TYPE           PERIODIC
#define CORE1_TASK2_PERIOD         (1000)
#define CORE1_TASK2_ACTIVED        NO_THREAD
#define CORE1_TASK2_PRIORITY       LEVEL_2
#define CORE1_TASK2_MODE           SUPER
#define CORE1_TASK2_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK2_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 

#define CORE1_TASK3_TYPE           EVENT
#define CORE1_TASK3_PERIOD         (0)
#define CORE1_TASK3_ACTIVED        THREAD_ID4
#define CORE1_TASK3_PRIORITY       LEVEL_3
#define CORE1_TASK3_MODE           SUPER
#define CORE1_TASK3_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK3_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 

#define CORE1_TASK4_TYPE           EVENT
#define CORE1_TASK4_PERIOD         (0)
#define CORE1_TASK4_ACTIVED        THREAD_ID5
#define CORE1_TASK4_PRIORITY       LEVEL_4
#define CORE1_TASK4_MODE           SUPER
#define CORE1_TASK4_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK4_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 

#define CORE1_TASK5_TYPE           EVENT
#define CORE1_TASK5_PERIOD         (0)
#define CORE1_TASK5_ACTIVED        THREAD_ID6
#define CORE1_TASK5_PRIORITY       LEVEL_5
#define CORE1_TASK5_MODE           SUPER
#define CORE1_TASK5_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK5_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 

#define CORE1_TASK6_TYPE           EVENT
#define CORE1_TASK6_PERIOD         (0)
#define CORE1_TASK6_ACTIVED        THREAD_ID7
#define CORE1_TASK6_PRIORITY       LEVEL_6
#define CORE1_TASK6_MODE           SUPER
#define CORE1_TASK6_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK6_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 

#define CORE1_TASK7_TYPE           EVENT
#define CORE1_TASK7_PERIOD         (0)
#define CORE1_TASK7_ACTIVED        THREAD_ID8
#define CORE1_TASK7_PRIORITY       LEVEL_7
#define CORE1_TASK7_MODE           SUPER
#define CORE1_TASK7_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK7_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 

#define CORE1_TASK8_TYPE           EVENT
#define CORE1_TASK8_PERIOD         (0)
#define CORE1_TASK8_ACTIVED        THREAD_ID9
#define CORE1_TASK8_PRIORITY       LEVEL_8
#define CORE1_TASK8_MODE           SUPER
#define CORE1_TASK8_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK8_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 

#define CORE1_TASK9_TYPE           EVENT
#define CORE1_TASK9_PERIOD         (0)
#define CORE1_TASK9_ACTIVED        NO_THREAD
#define CORE1_TASK9_PRIORITY       LEVEL_9
#define CORE1_TASK9_MODE           SUPER
#define CORE1_TASK9_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK9_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 

#define CORE1_TASK10_TYPE          PERIODIC
#define CORE1_TASK10_PERIOD        (1000)
#define CORE1_TASK10_ACTIVED       NO_THREAD
#define CORE1_TASK10_PRIORITY      LEVEL_10
#define CORE1_TASK10_MODE          SUPER
#define CORE1_TASK10_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK10_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 

/* core 2 */
#define CORE2_TASK0_TYPE           NO_DEFINITION             
#define CORE2_TASK0_PERIOD         (0)  /* unit:ms */
#define CORE2_TASK0_ACTIVED        NO_THREAD
#define CORE2_TASK0_PRIORITY       LEVEL_0
#define CORE2_TASK0_MODE           SUPER
#define CORE2_TASK0_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK0_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 

#define CORE2_TASK1_TYPE           PERIODIC
#define CORE2_TASK1_PERIOD         (1000)  /* unit:ms */
#define CORE2_TASK1_ACTIVED        NO_THREAD
#define CORE2_TASK1_PRIORITY       LEVEL_1
#define CORE2_TASK1_MODE           SUPER
#define CORE2_TASK1_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK1_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 

#define CORE2_TASK2_TYPE           PERIODIC
#define CORE2_TASK2_PERIOD         (1000)
#define CORE2_TASK2_ACTIVED        NO_THREAD
#define CORE2_TASK2_PRIORITY       LEVEL_2
#define CORE2_TASK2_MODE           SUPER
#define CORE2_TASK2_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK2_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 

#define CORE2_TASK3_TYPE           EVENT
#define CORE2_TASK3_PERIOD         (0)
#define CORE2_TASK3_ACTIVED        THREAD_ID4
#define CORE2_TASK3_PRIORITY       LEVEL_3
#define CORE2_TASK3_MODE           SUPER
#define CORE2_TASK3_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK3_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 

#define CORE2_TASK4_TYPE           EVENT
#define CORE2_TASK4_PERIOD         (0)
#define CORE2_TASK4_ACTIVED        THREAD_ID5
#define CORE2_TASK4_PRIORITY       LEVEL_4
#define CORE2_TASK4_MODE           SUPER
#define CORE2_TASK4_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK4_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 

#define CORE2_TASK5_TYPE           EVENT
#define CORE2_TASK5_PERIOD         (0)
#define CORE2_TASK5_ACTIVED        THREAD_ID6
#define CORE2_TASK5_PRIORITY       LEVEL_5
#define CORE2_TASK5_MODE           SUPER
#define CORE2_TASK5_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK5_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 

#define CORE2_TASK6_TYPE           EVENT
#define CORE2_TASK6_PERIOD         (0)
#define CORE2_TASK6_ACTIVED        THREAD_ID7
#define CORE2_TASK6_PRIORITY       LEVEL_6
#define CORE2_TASK6_MODE           SUPER
#define CORE2_TASK6_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK6_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 

#define CORE2_TASK7_TYPE           EVENT
#define CORE2_TASK7_PERIOD         (0)
#define CORE2_TASK7_ACTIVED        THREAD_ID8
#define CORE2_TASK7_PRIORITY       LEVEL_7
#define CORE2_TASK7_MODE           SUPER
#define CORE2_TASK7_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK7_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 

#define CORE2_TASK8_TYPE           EVENT
#define CORE2_TASK8_PERIOD         (0)
#define CORE2_TASK8_ACTIVED        THREAD_ID9
#define CORE2_TASK8_PRIORITY       LEVEL_8
#define CORE2_TASK8_MODE           SUPER
#define CORE2_TASK8_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK8_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 

#define CORE2_TASK9_TYPE           EVENT
#define CORE2_TASK9_PERIOD         (0)
#define CORE2_TASK9_ACTIVED        NO_THREAD
#define CORE2_TASK9_PRIORITY       LEVEL_9
#define CORE2_TASK9_MODE           SUPER
#define CORE2_TASK9_STACK_SIZE     PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK9_CALL_DEPTH     CALL_DEPTH_OVERFLOW_AT_64 

#define CORE2_TASK10_TYPE          PERIODIC
#define CORE2_TASK10_PERIOD        (1000)
#define CORE2_TASK10_ACTIVED       NO_THREAD
#define CORE2_TASK10_PRIORITY      LEVEL_10
#define CORE2_TASK10_MODE          SUPER
#define CORE2_TASK10_STACK_SIZE    PTHREAD_DEFAULT_STACK_SIZE
#define CORE2_TASK10_CALL_DEPTH    CALL_DEPTH_OVERFLOW_AT_64 

#endif
