

#ifndef THREAD_CONFIG_H_
#define THREAD_CONFIG_H_

#define THREAD_NO_DEFINITION (0)
#define THREAD_PERIODIC      (1)
#define THREAD_EVENT         (2)

typedef enum  {

	 CORE_ID0,
	 CORE_ID1,
	 CORE_ID2,
	 CORE_MAX_ID_NUM

}OS_CORE_ID_t;

typedef enum  {

	 THREAD_ID0,
	 THREAD_ID1,
	 THREAD_ID2,
	 THREAD_ID3,
	 THREAD_ID4,
	 THREAD_ID5,
	 THREAD_ID6,
	 THREAD_ID7,
	 THREAD_ID8,
	 THREAD_ID9,
	 THREAD_ID10,
	 THREAD_MAX_ID_NUM,
	 NO_THREAD
 
}OS_THREAD_ID_t;

/* core 0*/
/* 0 thread config initialization */ 
#define CORE0_TASK0_TYPE       THREAD_NO_DEFINITION             
#define CORE0_TASK0_PERIOD     (0)  /* unit:ms */
#define CORE0_TASK0_ACTIVED    NO_THREAD

#define CORE0_TASK1_TYPE       THREAD_PERIODIC
#define CORE0_TASK1_PERIOD     (300)  /* unit:ms */
#define CORE0_TASK1_ACTIVED    NO_THREAD

#define CORE0_TASK2_TYPE       THREAD_PERIODIC
#define CORE0_TASK2_PERIOD     (500)  /* unit:ms */
#define CORE0_TASK2_ACTIVED    NO_THREAD

#define CORE0_TASK3_TYPE       THREAD_EVENT
#define CORE0_TASK3_PERIOD     (0)
#define CORE0_TASK3_ACTIVED    THREAD_ID4

#define CORE0_TASK4_TYPE       THREAD_EVENT
#define CORE0_TASK4_PERIOD     (0)
#define CORE0_TASK4_ACTIVED    THREAD_ID5

#define CORE0_TASK5_TYPE       THREAD_EVENT
#define CORE0_TASK5_PERIOD     (0)
#define CORE0_TASK5_ACTIVED    THREAD_ID6

#define CORE0_TASK6_TYPE       THREAD_EVENT
#define CORE0_TASK6_PERIOD     (0)
#define CORE0_TASK6_ACTIVED    THREAD_ID7

#define CORE0_TASK7_TYPE       THREAD_EVENT
#define CORE0_TASK7_PERIOD     (0)
#define CORE0_TASK7_ACTIVED    THREAD_ID8

#define CORE0_TASK8_TYPE       THREAD_EVENT
#define CORE0_TASK8_PERIOD     (0)
#define CORE0_TASK8_ACTIVED    THREAD_ID9

#define CORE0_TASK9_TYPE       THREAD_EVENT
#define CORE0_TASK9_PERIOD     (0)
#define CORE0_TASK9_ACTIVED    NO_THREAD

#define CORE0_TASK10_TYPE      THREAD_PERIODIC
#define CORE0_TASK10_PERIOD    (1000)  /* unit:ms */
#define CORE0_TASK10_ACTIVED   NO_THREAD


/* core 1                      */

#define CORE1_TASK0_TYPE       THREAD_NO_DEFINITION             
#define CORE1_TASK0_PERIOD     (0)  /* unit:ms */
#define CORE1_TASK0_ACTIVED    NO_THREAD

#define CORE1_TASK1_TYPE       THREAD_PERIODIC
#define CORE1_TASK1_PERIOD     (1000)  /* unit:ms */
#define CORE1_TASK1_ACTIVED    NO_THREAD

#define CORE1_TASK2_TYPE       THREAD_PERIODIC
#define CORE1_TASK2_PERIOD     (1000)
#define CORE1_TASK2_ACTIVED    NO_THREAD

#define CORE1_TASK3_TYPE       THREAD_EVENT
#define CORE1_TASK3_PERIOD     (0)
#define CORE1_TASK3_ACTIVED    THREAD_ID4

#define CORE1_TASK4_TYPE       THREAD_EVENT
#define CORE1_TASK4_PERIOD     (0)
#define CORE1_TASK4_ACTIVED    THREAD_ID5

#define CORE1_TASK5_TYPE       THREAD_EVENT
#define CORE1_TASK5_PERIOD     (0)
#define CORE1_TASK5_ACTIVED    THREAD_ID6

#define CORE1_TASK6_TYPE       THREAD_EVENT
#define CORE1_TASK6_PERIOD     (0)
#define CORE1_TASK6_ACTIVED    THREAD_ID7

#define CORE1_TASK7_TYPE       THREAD_EVENT
#define CORE1_TASK7_PERIOD     (0)
#define CORE1_TASK7_ACTIVED    THREAD_ID8

#define CORE1_TASK8_TYPE       THREAD_EVENT
#define CORE1_TASK8_PERIOD     (0)
#define CORE1_TASK8_ACTIVED    THREAD_ID9

#define CORE1_TASK9_TYPE       THREAD_EVENT
#define CORE1_TASK9_PERIOD     (0)
#define CORE1_TASK9_ACTIVED    NO_THREAD

#define CORE1_TASK10_TYPE      THREAD_PERIODIC
#define CORE1_TASK10_PERIOD    (1000)
#define CORE1_TASK10_ACTIVED   NO_THREAD


/* core 2 */
#define CORE2_TASK0_TYPE       THREAD_NO_DEFINITION             
#define CORE2_TASK0_PERIOD     (0)  /* unit:ms */
#define CORE2_TASK0_ACTIVED    NO_THREAD

#define CORE2_TASK1_TYPE       THREAD_PERIODIC
#define CORE2_TASK1_PERIOD     (1000)  /* unit:ms */
#define CORE2_TASK1_ACTIVED    NO_THREAD

#define CORE2_TASK2_TYPE       THREAD_PERIODIC
#define CORE2_TASK2_PERIOD     (1000)
#define CORE2_TASK2_ACTIVED    NO_THREAD

#define CORE2_TASK3_TYPE       THREAD_EVENT
#define CORE2_TASK3_PERIOD     (0)
#define CORE2_TASK3_ACTIVED    THREAD_ID4

#define CORE2_TASK4_TYPE       THREAD_EVENT
#define CORE2_TASK4_PERIOD     (0)
#define CORE2_TASK4_ACTIVED    THREAD_ID5

#define CORE2_TASK5_TYPE       THREAD_EVENT
#define CORE2_TASK5_PERIOD     (0)
#define CORE2_TASK5_ACTIVED    THREAD_ID6

#define CORE2_TASK6_TYPE       THREAD_EVENT
#define CORE2_TASK6_PERIOD     (0)
#define CORE2_TASK6_ACTIVED    THREAD_ID7

#define CORE2_TASK7_TYPE       THREAD_EVENT
#define CORE2_TASK7_PERIOD     (0)
#define CORE2_TASK7_ACTIVED    THREAD_ID8

#define CORE2_TASK8_TYPE       THREAD_EVENT
#define CORE2_TASK8_PERIOD     (0)
#define CORE2_TASK8_ACTIVED    THREAD_ID9

#define CORE2_TASK9_TYPE       THREAD_EVENT
#define CORE2_TASK9_PERIOD     (0)
#define CORE2_TASK9_ACTIVED    NO_THREAD

#define CORE2_TASK10_TYPE      THREAD_PERIODIC
#define CORE2_TASK10_PERIOD    (1000)
#define CORE2_TASK10_ACTIVED   NO_THREAD

#endif

