

#ifndef THREAD_CONFIG_H_
#define THREAD_CONFIG_H_

#include "os_thread_type.h"
#include "task_cfg.h"

/* core 0*/
/* 0 thread config initialization */ 

#define CORE0_THREAD0_SWITCH   CORE0_TASK0_SWITCH
#define CORE0_THREAD1_SWITCH   CORE0_TASK1_SWITCH
#define CORE0_THREAD2_SWITCH   CORE0_TASK2_SWITCH
#define CORE0_THREAD3_SWITCH   CORE0_TASK3_SWITCH
#define CORE0_THREAD4_SWITCH   CORE0_TASK4_SWITCH
#define CORE0_THREAD5_SWITCH   CORE0_TASK5_SWITCH
#define CORE0_THREAD6_SWITCH   CORE0_TASK6_SWITCH
#define CORE0_THREAD7_SWITCH   CORE0_TASK7_SWITCH
#define CORE0_THREAD8_SWITCH   CORE0_TASK8_SWITCH
#define CORE0_THREAD9_SWITCH   CORE0_TASK9_SWITCH
#define CORE0_THREAD10_SWITCH  CORE0_TASK10_SWITCH
#define CORE0_THREAD11_SWITCH  CORE0_TASK11_SWITCH
#define CORE0_THREAD12_SWITCH  CORE0_TASK12_SWITCH
#define CORE0_THREAD13_SWITCH  CORE0_TASK13_SWITCH
#define CORE0_THREAD14_SWITCH  CORE0_TASK14_SWITCH
#define CORE0_THREAD15_SWITCH  CORE0_TASK15_SWITCH
#define CORE0_THREAD16_SWITCH  CORE0_TASK16_SWITCH
#define CORE0_THREAD17_SWITCH  CORE0_TASK17_SWITCH
#define CORE0_THREAD18_SWITCH  CORE0_TASK18_SWITCH
#define CORE0_THREAD19_SWITCH  CORE0_TASK19_SWITCH
#define CORE0_THREAD20_SWITCH  CORE0_TASK20_SWITCH
#define CORE0_THREAD21_SWITCH  CORE0_TASK21_SWITCH
#define CORE0_THREAD22_SWITCH  CORE0_TASK22_SWITCH
#define CORE0_THREAD23_SWITCH  CORE0_TASK23_SWITCH
#define CORE0_THREAD24_SWITCH  CORE0_TASK24_SWITCH
#define CORE0_THREAD25_SWITCH  CORE0_TASK25_SWITCH
#define CORE0_THREAD26_SWITCH  CORE0_TASK26_SWITCH
#define CORE0_THREAD27_SWITCH  CORE0_TASK27_SWITCH
#define CORE0_THREAD28_SWITCH  CORE0_TASK28_SWITCH
#define CORE0_THREAD29_SWITCH  CORE0_TASK29_SWITCH
#define CORE0_THREAD30_SWITCH  CORE0_TASK30_SWITCH
#define CORE0_THREAD31_SWITCH  CORE0_TASK31_SWITCH
#define CORE0_THREAD32_SWITCH  CORE0_TASK32_SWITCH
#define CORE0_THREAD33_SWITCH  CORE0_TASK33_SWITCH
#define CORE0_THREAD34_SWITCH  CORE0_TASK34_SWITCH
#define CORE0_THREAD35_SWITCH  CORE0_TASK35_SWITCH
#define CORE0_THREAD36_SWITCH  CORE0_TASK36_SWITCH
#define CORE0_THREAD37_SWITCH  CORE0_TASK37_SWITCH
#define CORE0_THREAD38_SWITCH  CORE0_TASK38_SWITCH
#define CORE0_THREAD39_SWITCH  CORE0_TASK39_SWITCH
#define CORE0_THREAD40_SWITCH  CORE0_TASK40_SWITCH
#define CORE0_THREAD41_SWITCH  CORE0_TASK41_SWITCH
#define CORE0_THREAD42_SWITCH  CORE0_TASK42_SWITCH
#define CORE0_THREAD43_SWITCH  CORE0_TASK43_SWITCH
#define CORE0_THREAD44_SWITCH  CORE0_TASK44_SWITCH
#define CORE0_THREAD45_SWITCH  CORE0_TASK45_SWITCH
#define CORE0_THREAD46_SWITCH  CORE0_TASK46_SWITCH
#define CORE0_THREAD47_SWITCH  CORE0_TASK47_SWITCH
#define CORE0_THREAD48_SWITCH  CORE0_TASK48_SWITCH
#define CORE0_THREAD49_SWITCH  CORE0_TASK49_SWITCH
#define CORE0_THREAD50_SWITCH  CORE0_TASK50_SWITCH
#define CORE0_THREAD51_SWITCH  CORE0_TASK51_SWITCH
#define CORE0_THREAD52_SWITCH  CORE0_TASK52_SWITCH
#define CORE0_THREAD53_SWITCH  CORE0_TASK53_SWITCH
#define CORE0_THREAD54_SWITCH  CORE0_TASK54_SWITCH
#define CORE0_THREAD55_SWITCH  CORE0_TASK55_SWITCH
#define CORE0_THREAD56_SWITCH  CORE0_TASK56_SWITCH
#define CORE0_THREAD57_SWITCH  CORE0_TASK57_SWITCH
#define CORE0_THREAD58_SWITCH  CORE0_TASK58_SWITCH
#define CORE0_THREAD59_SWITCH  CORE0_TASK59_SWITCH
#define CORE0_THREAD60_SWITCH  CORE0_TASK60_SWITCH
#define CORE0_THREAD61_SWITCH  CORE0_TASK61_SWITCH
#define CORE0_THREAD62_SWITCH  CORE0_TASK62_SWITCH
#define CORE0_THREAD63_SWITCH  CORE0_TASK63_SWITCH
#define CORE0_THREAD64_SWITCH  CORE0_TASK64_SWITCH
#define CORE0_THREAD65_SWITCH  CORE0_TASK65_SWITCH
#define CORE0_THREAD66_SWITCH  CORE0_TASK66_SWITCH
#define CORE0_THREAD67_SWITCH  CORE0_TASK67_SWITCH
#define CORE0_THREAD68_SWITCH  CORE0_TASK68_SWITCH
#define CORE0_THREAD69_SWITCH  CORE0_TASK69_SWITCH
#define CORE0_THREAD70_SWITCH  CORE0_TASK70_SWITCH
#define CORE0_THREAD71_SWITCH  CORE0_TASK71_SWITCH
#define CORE0_THREAD72_SWITCH  CORE0_TASK72_SWITCH
#define CORE0_THREAD73_SWITCH  CORE0_TASK73_SWITCH
#define CORE0_THREAD74_SWITCH  CORE0_TASK74_SWITCH
#define CORE0_THREAD75_SWITCH  CORE0_TASK75_SWITCH
#define CORE0_THREAD76_SWITCH  CORE0_TASK76_SWITCH
#define CORE0_THREAD77_SWITCH  CORE0_TASK77_SWITCH
#define CORE0_THREAD78_SWITCH  CORE0_TASK78_SWITCH
#define CORE0_THREAD79_SWITCH  CORE0_TASK79_SWITCH
#define CORE0_THREAD80_SWITCH  CORE0_TASK80_SWITCH
#define CORE0_THREAD81_SWITCH  CORE0_TASK81_SWITCH
#define CORE0_THREAD82_SWITCH  CORE0_TASK82_SWITCH
#define CORE0_THREAD83_SWITCH  CORE0_TASK83_SWITCH
#define CORE0_THREAD84_SWITCH  CORE0_TASK84_SWITCH
#define CORE0_THREAD85_SWITCH  CORE0_TASK85_SWITCH
#define CORE0_THREAD86_SWITCH  CORE0_TASK86_SWITCH
#define CORE0_THREAD87_SWITCH  CORE0_TASK87_SWITCH
#define CORE0_THREAD88_SWITCH  CORE0_TASK88_SWITCH
#define CORE0_THREAD89_SWITCH  CORE0_TASK89_SWITCH
#define CORE0_THREAD90_SWITCH  CORE0_TASK90_SWITCH
#define CORE0_THREAD91_SWITCH  CORE0_TASK91_SWITCH
#define CORE0_THREAD92_SWITCH  CORE0_TASK92_SWITCH
#define CORE0_THREAD93_SWITCH  CORE0_TASK93_SWITCH
#define CORE0_THREAD94_SWITCH  CORE0_TASK94_SWITCH
#define CORE0_THREAD95_SWITCH  CORE0_TASK95_SWITCH
#define CORE0_THREAD96_SWITCH  CORE0_TASK96_SWITCH
#define CORE0_THREAD97_SWITCH  CORE0_TASK97_SWITCH
#define CORE0_THREAD98_SWITCH  CORE0_TASK98_SWITCH
#define CORE0_THREAD99_SWITCH  CORE0_TASK99_SWITCH
#define CORE0_THREAD100_SWITCH CORE0_TASK100_SWITCH

#define CORE1_THREAD0_SWITCH   CORE1_TASK0_SWITCH
#define CORE1_THREAD1_SWITCH   CORE1_TASK1_SWITCH
#define CORE1_THREAD2_SWITCH   CORE1_TASK2_SWITCH
#define CORE1_THREAD3_SWITCH   CORE1_TASK3_SWITCH
#define CORE1_THREAD4_SWITCH   CORE1_TASK4_SWITCH
#define CORE1_THREAD5_SWITCH   CORE1_TASK5_SWITCH
#define CORE1_THREAD6_SWITCH   CORE1_TASK6_SWITCH
#define CORE1_THREAD7_SWITCH   CORE1_TASK7_SWITCH
#define CORE1_THREAD8_SWITCH   CORE1_TASK8_SWITCH
#define CORE1_THREAD9_SWITCH   CORE1_TASK9_SWITCH
#define CORE1_THREAD10_SWITCH  CORE1_TASK10_SWITCH
#define CORE1_THREAD11_SWITCH  CORE1_TASK11_SWITCH
#define CORE1_THREAD12_SWITCH  CORE1_TASK12_SWITCH
#define CORE1_THREAD13_SWITCH  CORE1_TASK13_SWITCH
#define CORE1_THREAD14_SWITCH  CORE1_TASK14_SWITCH
#define CORE1_THREAD15_SWITCH  CORE1_TASK15_SWITCH
#define CORE1_THREAD16_SWITCH  CORE1_TASK16_SWITCH
#define CORE1_THREAD17_SWITCH  CORE1_TASK17_SWITCH
#define CORE1_THREAD18_SWITCH  CORE1_TASK18_SWITCH
#define CORE1_THREAD19_SWITCH  CORE1_TASK19_SWITCH
#define CORE1_THREAD20_SWITCH  CORE1_TASK20_SWITCH
#define CORE1_THREAD21_SWITCH  CORE1_TASK21_SWITCH
#define CORE1_THREAD22_SWITCH  CORE1_TASK22_SWITCH
#define CORE1_THREAD23_SWITCH  CORE1_TASK23_SWITCH
#define CORE1_THREAD24_SWITCH  CORE1_TASK24_SWITCH
#define CORE1_THREAD25_SWITCH  CORE1_TASK25_SWITCH
#define CORE1_THREAD26_SWITCH  CORE1_TASK26_SWITCH
#define CORE1_THREAD27_SWITCH  CORE1_TASK27_SWITCH
#define CORE1_THREAD28_SWITCH  CORE1_TASK28_SWITCH
#define CORE1_THREAD29_SWITCH  CORE1_TASK29_SWITCH
#define CORE1_THREAD30_SWITCH  CORE1_TASK30_SWITCH
#define CORE1_THREAD31_SWITCH  CORE1_TASK31_SWITCH
#define CORE1_THREAD32_SWITCH  CORE1_TASK32_SWITCH
#define CORE1_THREAD33_SWITCH  CORE1_TASK33_SWITCH
#define CORE1_THREAD34_SWITCH  CORE1_TASK34_SWITCH
#define CORE1_THREAD35_SWITCH  CORE1_TASK35_SWITCH
#define CORE1_THREAD36_SWITCH  CORE1_TASK36_SWITCH
#define CORE1_THREAD37_SWITCH  CORE1_TASK37_SWITCH
#define CORE1_THREAD38_SWITCH  CORE1_TASK38_SWITCH
#define CORE1_THREAD39_SWITCH  CORE1_TASK39_SWITCH
#define CORE1_THREAD40_SWITCH  CORE1_TASK40_SWITCH
#define CORE1_THREAD41_SWITCH  CORE1_TASK41_SWITCH
#define CORE1_THREAD42_SWITCH  CORE1_TASK42_SWITCH
#define CORE1_THREAD43_SWITCH  CORE1_TASK43_SWITCH
#define CORE1_THREAD44_SWITCH  CORE1_TASK44_SWITCH
#define CORE1_THREAD45_SWITCH  CORE1_TASK45_SWITCH
#define CORE1_THREAD46_SWITCH  CORE1_TASK46_SWITCH
#define CORE1_THREAD47_SWITCH  CORE1_TASK47_SWITCH
#define CORE1_THREAD48_SWITCH  CORE1_TASK48_SWITCH
#define CORE1_THREAD49_SWITCH  CORE1_TASK49_SWITCH
#define CORE1_THREAD50_SWITCH  CORE1_TASK50_SWITCH
#define CORE1_THREAD51_SWITCH  CORE1_TASK51_SWITCH
#define CORE1_THREAD52_SWITCH  CORE1_TASK52_SWITCH
#define CORE1_THREAD53_SWITCH  CORE1_TASK53_SWITCH
#define CORE1_THREAD54_SWITCH  CORE1_TASK54_SWITCH
#define CORE1_THREAD55_SWITCH  CORE1_TASK55_SWITCH
#define CORE1_THREAD56_SWITCH  CORE1_TASK56_SWITCH
#define CORE1_THREAD57_SWITCH  CORE1_TASK57_SWITCH
#define CORE1_THREAD58_SWITCH  CORE1_TASK58_SWITCH
#define CORE1_THREAD59_SWITCH  CORE1_TASK59_SWITCH
#define CORE1_THREAD60_SWITCH  CORE1_TASK60_SWITCH
#define CORE1_THREAD61_SWITCH  CORE1_TASK61_SWITCH
#define CORE1_THREAD62_SWITCH  CORE1_TASK62_SWITCH
#define CORE1_THREAD63_SWITCH  CORE1_TASK63_SWITCH
#define CORE1_THREAD64_SWITCH  CORE1_TASK64_SWITCH
#define CORE1_THREAD65_SWITCH  CORE1_TASK65_SWITCH
#define CORE1_THREAD66_SWITCH  CORE1_TASK66_SWITCH
#define CORE1_THREAD67_SWITCH  CORE1_TASK67_SWITCH
#define CORE1_THREAD68_SWITCH  CORE1_TASK68_SWITCH
#define CORE1_THREAD69_SWITCH  CORE1_TASK69_SWITCH
#define CORE1_THREAD70_SWITCH  CORE1_TASK70_SWITCH
#define CORE1_THREAD71_SWITCH  CORE1_TASK71_SWITCH
#define CORE1_THREAD72_SWITCH  CORE1_TASK72_SWITCH
#define CORE1_THREAD73_SWITCH  CORE1_TASK73_SWITCH
#define CORE1_THREAD74_SWITCH  CORE1_TASK74_SWITCH
#define CORE1_THREAD75_SWITCH  CORE1_TASK75_SWITCH
#define CORE1_THREAD76_SWITCH  CORE1_TASK76_SWITCH
#define CORE1_THREAD77_SWITCH  CORE1_TASK77_SWITCH
#define CORE1_THREAD78_SWITCH  CORE1_TASK78_SWITCH
#define CORE1_THREAD79_SWITCH  CORE1_TASK79_SWITCH
#define CORE1_THREAD80_SWITCH  CORE1_TASK80_SWITCH
#define CORE1_THREAD81_SWITCH  CORE1_TASK81_SWITCH
#define CORE1_THREAD82_SWITCH  CORE1_TASK82_SWITCH
#define CORE1_THREAD83_SWITCH  CORE1_TASK83_SWITCH
#define CORE1_THREAD84_SWITCH  CORE1_TASK84_SWITCH
#define CORE1_THREAD85_SWITCH  CORE1_TASK85_SWITCH
#define CORE1_THREAD86_SWITCH  CORE1_TASK86_SWITCH
#define CORE1_THREAD87_SWITCH  CORE1_TASK87_SWITCH
#define CORE1_THREAD88_SWITCH  CORE1_TASK88_SWITCH
#define CORE1_THREAD89_SWITCH  CORE1_TASK89_SWITCH
#define CORE1_THREAD90_SWITCH  CORE1_TASK90_SWITCH
#define CORE1_THREAD91_SWITCH  CORE1_TASK91_SWITCH
#define CORE1_THREAD92_SWITCH  CORE1_TASK92_SWITCH
#define CORE1_THREAD93_SWITCH  CORE1_TASK93_SWITCH
#define CORE1_THREAD94_SWITCH  CORE1_TASK94_SWITCH
#define CORE1_THREAD95_SWITCH  CORE1_TASK95_SWITCH
#define CORE1_THREAD96_SWITCH  CORE1_TASK96_SWITCH
#define CORE1_THREAD97_SWITCH  CORE1_TASK97_SWITCH
#define CORE1_THREAD98_SWITCH  CORE1_TASK98_SWITCH
#define CORE1_THREAD99_SWITCH  CORE1_TASK99_SWITCH
#define CORE1_THREAD100_SWITCH CORE1_TASK100_SWITCH
#if (CORE0_TASK0_SWITCH == ON)
#define CORE0_THREAD0_TYPE           CORE0_TASK0_TYPE             
#define CORE0_THREAD0_PERIOD         CORE0_TASK0_PERIOD
#define CORE0_THREAD0_ACTIVED        CORE0_TASK0_ACTIVED
#define CORE0_THREAD0_PRIORITY       CORE0_TASK0_PRIORITY
#define CORE0_THREAD0_MODE           CORE0_TASK0_MODE
#define CORE0_THREAD0_STACK_SIZE     CORE0_TASK0_STACK_SIZE
#define CORE0_THREAD0_CALL_DEPTH     CORE0_TASK0_CALL_DEPTH 
#endif

#define CORE0_THREAD1_TYPE           CORE0_TASK1_TYPE             
#define CORE0_THREAD1_PERIOD         CORE0_TASK1_PERIOD
#define CORE0_THREAD1_ACTIVED        CORE0_TASK1_ACTIVED
#define CORE0_THREAD1_PRIORITY       CORE0_TASK1_PRIORITY
#define CORE0_THREAD1_MODE           CORE0_TASK1_MODE
#define CORE0_THREAD1_STACK_SIZE     CORE0_TASK1_STACK_SIZE
#define CORE0_THREAD1_CALL_DEPTH     CORE0_TASK1_CALL_DEPTH  

#define CORE0_THREAD2_TYPE           CORE0_TASK2_TYPE             
#define CORE0_THREAD2_PERIOD         CORE0_TASK2_PERIOD
#define CORE0_THREAD2_ACTIVED        CORE0_TASK2_ACTIVED
#define CORE0_THREAD2_PRIORITY       CORE0_TASK2_PRIORITY
#define CORE0_THREAD2_MODE           CORE0_TASK2_MODE
#define CORE0_THREAD2_STACK_SIZE     CORE0_TASK2_STACK_SIZE
#define CORE0_THREAD2_CALL_DEPTH     CORE0_TASK2_CALL_DEPTH 

#define CORE0_THREAD3_TYPE           CORE0_TASK3_TYPE             
#define CORE0_THREAD3_PERIOD         CORE0_TASK3_PERIOD
#define CORE0_THREAD3_ACTIVED        CORE0_TASK3_ACTIVED
#define CORE0_THREAD3_PRIORITY       CORE0_TASK3_PRIORITY
#define CORE0_THREAD3_MODE           CORE0_TASK3_MODE
#define CORE0_THREAD3_STACK_SIZE     CORE0_TASK3_STACK_SIZE
#define CORE0_THREAD3_CALL_DEPTH     CORE0_TASK3_CALL_DEPTH 

#define CORE0_THREAD4_TYPE           CORE0_TASK4_TYPE             
#define CORE0_THREAD4_PERIOD         CORE0_TASK4_PERIOD
#define CORE0_THREAD4_ACTIVED        CORE0_TASK4_ACTIVED
#define CORE0_THREAD4_PRIORITY       CORE0_TASK4_PRIORITY
#define CORE0_THREAD4_MODE           CORE0_TASK4_MODE
#define CORE0_THREAD4_STACK_SIZE     CORE0_TASK4_STACK_SIZE
#define CORE0_THREAD4_CALL_DEPTH     CORE0_TASK4_CALL_DEPTH 

#define CORE0_THREAD5_TYPE           CORE0_TASK5_TYPE             
#define CORE0_THREAD5_PERIOD         CORE0_TASK5_PERIOD
#define CORE0_THREAD5_ACTIVED        CORE0_TASK5_ACTIVED
#define CORE0_THREAD5_PRIORITY       CORE0_TASK5_PRIORITY
#define CORE0_THREAD5_MODE           CORE0_TASK5_MODE
#define CORE0_THREAD5_STACK_SIZE     CORE0_TASK5_STACK_SIZE
#define CORE0_THREAD5_CALL_DEPTH     CORE0_TASK5_CALL_DEPTH 

#define CORE0_THREAD6_TYPE           CORE0_TASK6_TYPE             
#define CORE0_THREAD6_PERIOD         CORE0_TASK6_PERIOD
#define CORE0_THREAD6_ACTIVED        CORE0_TASK6_ACTIVED
#define CORE0_THREAD6_PRIORITY       CORE0_TASK6_PRIORITY
#define CORE0_THREAD6_MODE           CORE0_TASK6_MODE
#define CORE0_THREAD6_STACK_SIZE     CORE0_TASK6_STACK_SIZE
#define CORE0_THREAD6_CALL_DEPTH     CORE0_TASK6_CALL_DEPTH 

#define CORE0_THREAD7_TYPE           CORE0_TASK7_TYPE             
#define CORE0_THREAD7_PERIOD         CORE0_TASK7_PERIOD
#define CORE0_THREAD7_ACTIVED        CORE0_TASK7_ACTIVED
#define CORE0_THREAD7_PRIORITY       CORE0_TASK7_PRIORITY
#define CORE0_THREAD7_MODE           CORE0_TASK7_MODE
#define CORE0_THREAD7_STACK_SIZE     CORE0_TASK7_STACK_SIZE
#define CORE0_THREAD7_CALL_DEPTH     CORE0_TASK7_CALL_DEPTH

#define CORE0_THREAD8_TYPE           CORE0_TASK8_TYPE             
#define CORE0_THREAD8_PERIOD         CORE0_TASK8_PERIOD
#define CORE0_THREAD8_ACTIVED        CORE0_TASK8_ACTIVED
#define CORE0_THREAD8_PRIORITY       CORE0_TASK8_PRIORITY
#define CORE0_THREAD8_MODE           CORE0_TASK8_MODE
#define CORE0_THREAD8_STACK_SIZE     CORE0_TASK8_STACK_SIZE
#define CORE0_THREAD8_CALL_DEPTH     CORE0_TASK8_CALL_DEPTH

#define CORE0_THREAD9_TYPE           CORE0_TASK9_TYPE             
#define CORE0_THREAD9_PERIOD         CORE0_TASK9_PERIOD
#define CORE0_THREAD9_ACTIVED        CORE0_TASK9_ACTIVED
#define CORE0_THREAD9_PRIORITY       CORE0_TASK9_PRIORITY
#define CORE0_THREAD9_MODE           CORE0_TASK9_MODE
#define CORE0_THREAD9_STACK_SIZE     CORE0_TASK9_STACK_SIZE
#define CORE0_THREAD9_CALL_DEPTH     CORE0_TASK9_CALL_DEPTH

#define CORE0_THREAD10_TYPE          CORE0_TASK10_TYPE             
#define CORE0_THREAD10_PERIOD        CORE0_TASK10_PERIOD
#define CORE0_THREAD10_ACTIVED       CORE0_TASK10_ACTIVED
#define CORE0_THREAD10_PRIORITY      CORE0_TASK10_PRIORITY
#define CORE0_THREAD10_MODE          CORE0_TASK10_MODE
#define CORE0_THREAD10_STACK_SIZE    CORE0_TASK10_STACK_SIZE
#define CORE0_THREAD10_CALL_DEPTH    CORE0_TASK10_CALL_DEPTH

/* core 1*/
/* 1 thread config initialization */ 
#define CORE1_THREAD0_TYPE           CORE1_TASK0_TYPE             
#define CORE1_THREAD0_PERIOD         CORE1_TASK0_PERIOD
#define CORE1_THREAD0_ACTIVED        CORE1_TASK0_ACTIVED
#define CORE1_THREAD0_PRIORITY       CORE1_TASK0_PRIORITY
#define CORE1_THREAD0_MODE           CORE1_TASK0_MODE
#define CORE1_THREAD0_STACK_SIZE     CORE1_TASK0_STACK_SIZE
#define CORE1_THREAD0_CALL_DEPTH     CORE1_TASK0_CALL_DEPTH  

#define CORE1_THREAD1_TYPE           CORE1_TASK1_TYPE             
#define CORE1_THREAD1_PERIOD         CORE1_TASK1_PERIOD
#define CORE1_THREAD1_ACTIVED        CORE1_TASK1_ACTIVED
#define CORE1_THREAD1_PRIORITY       CORE1_TASK1_PRIORITY
#define CORE1_THREAD1_MODE           CORE1_TASK1_MODE
#define CORE1_THREAD1_STACK_SIZE     CORE1_TASK1_STACK_SIZE
#define CORE1_THREAD1_CALL_DEPTH     CORE1_TASK1_CALL_DEPTH  

#define CORE1_THREAD2_TYPE           CORE1_TASK2_TYPE             
#define CORE1_THREAD2_PERIOD         CORE1_TASK2_PERIOD
#define CORE1_THREAD2_ACTIVED        CORE1_TASK2_ACTIVED
#define CORE1_THREAD2_PRIORITY       CORE1_TASK2_PRIORITY
#define CORE1_THREAD2_MODE           CORE1_TASK2_MODE
#define CORE1_THREAD2_STACK_SIZE     CORE1_TASK2_STACK_SIZE
#define CORE1_THREAD2_CALL_DEPTH     CORE1_TASK2_CALL_DEPTH 

#define CORE1_THREAD3_TYPE           CORE1_TASK3_TYPE             
#define CORE1_THREAD3_PERIOD         CORE1_TASK3_PERIOD
#define CORE1_THREAD3_ACTIVED        CORE1_TASK3_ACTIVED
#define CORE1_THREAD3_PRIORITY       CORE1_TASK3_PRIORITY
#define CORE1_THREAD3_MODE           CORE1_TASK3_MODE
#define CORE1_THREAD3_STACK_SIZE     CORE1_TASK3_STACK_SIZE
#define CORE1_THREAD3_CALL_DEPTH     CORE1_TASK3_CALL_DEPTH 

#define CORE1_THREAD4_TYPE           CORE1_TASK4_TYPE             
#define CORE1_THREAD4_PERIOD         CORE1_TASK4_PERIOD
#define CORE1_THREAD4_ACTIVED        CORE1_TASK4_ACTIVED
#define CORE1_THREAD4_PRIORITY       CORE1_TASK4_PRIORITY
#define CORE1_THREAD4_MODE           CORE1_TASK4_MODE
#define CORE1_THREAD4_STACK_SIZE     CORE1_TASK4_STACK_SIZE
#define CORE1_THREAD4_CALL_DEPTH     CORE1_TASK4_CALL_DEPTH 

#define CORE1_THREAD5_TYPE           CORE1_TASK5_TYPE             
#define CORE1_THREAD5_PERIOD         CORE1_TASK5_PERIOD
#define CORE1_THREAD5_ACTIVED        CORE1_TASK5_ACTIVED
#define CORE1_THREAD5_PRIORITY       CORE1_TASK5_PRIORITY
#define CORE1_THREAD5_MODE           CORE1_TASK5_MODE
#define CORE1_THREAD5_STACK_SIZE     CORE1_TASK5_STACK_SIZE
#define CORE1_THREAD5_CALL_DEPTH     CORE1_TASK5_CALL_DEPTH 

#define CORE1_THREAD6_TYPE           CORE1_TASK6_TYPE             
#define CORE1_THREAD6_PERIOD         CORE1_TASK6_PERIOD
#define CORE1_THREAD6_ACTIVED        CORE1_TASK6_ACTIVED
#define CORE1_THREAD6_PRIORITY       CORE1_TASK6_PRIORITY
#define CORE1_THREAD6_MODE           CORE1_TASK6_MODE
#define CORE1_THREAD6_STACK_SIZE     CORE1_TASK6_STACK_SIZE
#define CORE1_THREAD6_CALL_DEPTH     CORE1_TASK6_CALL_DEPTH 

#define CORE1_THREAD7_TYPE           CORE1_TASK7_TYPE             
#define CORE1_THREAD7_PERIOD         CORE1_TASK7_PERIOD
#define CORE1_THREAD7_ACTIVED        CORE1_TASK7_ACTIVED
#define CORE1_THREAD7_PRIORITY       CORE1_TASK7_PRIORITY
#define CORE1_THREAD7_MODE           CORE1_TASK7_MODE
#define CORE1_THREAD7_STACK_SIZE     CORE1_TASK7_STACK_SIZE
#define CORE1_THREAD7_CALL_DEPTH     CORE1_TASK7_CALL_DEPTH

#define CORE1_THREAD8_TYPE           CORE1_TASK8_TYPE             
#define CORE1_THREAD8_PERIOD         CORE1_TASK8_PERIOD
#define CORE1_THREAD8_ACTIVED        CORE1_TASK8_ACTIVED
#define CORE1_THREAD8_PRIORITY       CORE1_TASK8_PRIORITY
#define CORE1_THREAD8_MODE           CORE1_TASK8_MODE
#define CORE1_THREAD8_STACK_SIZE     CORE1_TASK8_STACK_SIZE
#define CORE1_THREAD8_CALL_DEPTH     CORE1_TASK8_CALL_DEPTH

#define CORE1_THREAD9_TYPE           CORE1_TASK9_TYPE             
#define CORE1_THREAD9_PERIOD         CORE1_TASK9_PERIOD
#define CORE1_THREAD9_ACTIVED        CORE1_TASK9_ACTIVED
#define CORE1_THREAD9_PRIORITY       CORE1_TASK9_PRIORITY
#define CORE1_THREAD9_MODE           CORE1_TASK9_MODE
#define CORE1_THREAD9_STACK_SIZE     CORE1_TASK9_STACK_SIZE
#define CORE1_THREAD9_CALL_DEPTH     CORE1_TASK9_CALL_DEPTH

#define CORE1_THREAD10_TYPE          CORE1_TASK10_TYPE             
#define CORE1_THREAD10_PERIOD        CORE1_TASK10_PERIOD
#define CORE1_THREAD10_ACTIVED       CORE1_TASK10_ACTIVED
#define CORE1_THREAD10_PRIORITY      CORE1_TASK10_PRIORITY
#define CORE1_THREAD10_MODE          CORE1_TASK10_MODE
#define CORE1_THREAD10_STACK_SIZE    CORE1_TASK10_STACK_SIZE
#define CORE1_THREAD10_CALL_DEPTH    CORE1_TASK10_CALL_DEPTH

/* core 2*/
/* 2 thread config initialization */ 
#define CORE2_THREAD0_TYPE           CORE2_TASK0_TYPE             
#define CORE2_THREAD0_PERIOD         CORE2_TASK0_PERIOD
#define CORE2_THREAD0_ACTIVED        CORE2_TASK0_ACTIVED
#define CORE2_THREAD0_PRIORITY       CORE2_TASK0_PRIORITY
#define CORE2_THREAD0_MODE           CORE2_TASK0_MODE
#define CORE2_THREAD0_STACK_SIZE     CORE2_TASK0_STACK_SIZE
#define CORE2_THREAD0_CALL_DEPTH     CORE2_TASK0_CALL_DEPTH  

#define CORE2_THREAD1_TYPE           CORE2_TASK1_TYPE             
#define CORE2_THREAD1_PERIOD         CORE2_TASK1_PERIOD
#define CORE2_THREAD1_ACTIVED        CORE2_TASK1_ACTIVED
#define CORE2_THREAD1_PRIORITY       CORE2_TASK1_PRIORITY
#define CORE2_THREAD1_MODE           CORE2_TASK1_MODE
#define CORE2_THREAD1_STACK_SIZE     CORE2_TASK1_STACK_SIZE
#define CORE2_THREAD1_CALL_DEPTH     CORE2_TASK1_CALL_DEPTH  

#define CORE2_THREAD2_TYPE           CORE2_TASK2_TYPE             
#define CORE2_THREAD2_PERIOD         CORE2_TASK2_PERIOD
#define CORE2_THREAD2_ACTIVED        CORE2_TASK2_ACTIVED
#define CORE2_THREAD2_PRIORITY       CORE2_TASK2_PRIORITY
#define CORE2_THREAD2_MODE           CORE2_TASK2_MODE
#define CORE2_THREAD2_STACK_SIZE     CORE2_TASK2_STACK_SIZE
#define CORE2_THREAD2_CALL_DEPTH     CORE2_TASK2_CALL_DEPTH 

#define CORE2_THREAD3_TYPE           CORE2_TASK3_TYPE             
#define CORE2_THREAD3_PERIOD         CORE2_TASK3_PERIOD
#define CORE2_THREAD3_ACTIVED        CORE2_TASK3_ACTIVED
#define CORE2_THREAD3_PRIORITY       CORE2_TASK3_PRIORITY
#define CORE2_THREAD3_MODE           CORE2_TASK3_MODE
#define CORE2_THREAD3_STACK_SIZE     CORE2_TASK3_STACK_SIZE
#define CORE2_THREAD3_CALL_DEPTH     CORE2_TASK3_CALL_DEPTH 

#define CORE2_THREAD4_TYPE           CORE2_TASK4_TYPE             
#define CORE2_THREAD4_PERIOD         CORE2_TASK4_PERIOD
#define CORE2_THREAD4_ACTIVED        CORE2_TASK4_ACTIVED
#define CORE2_THREAD4_PRIORITY       CORE2_TASK4_PRIORITY
#define CORE2_THREAD4_MODE           CORE2_TASK4_MODE
#define CORE2_THREAD4_STACK_SIZE     CORE2_TASK4_STACK_SIZE
#define CORE2_THREAD4_CALL_DEPTH     CORE2_TASK4_CALL_DEPTH 

#define CORE2_THREAD5_TYPE           CORE2_TASK5_TYPE             
#define CORE2_THREAD5_PERIOD         CORE2_TASK5_PERIOD
#define CORE2_THREAD5_ACTIVED        CORE2_TASK5_ACTIVED
#define CORE2_THREAD5_PRIORITY       CORE2_TASK5_PRIORITY
#define CORE2_THREAD5_MODE           CORE2_TASK5_MODE
#define CORE2_THREAD5_STACK_SIZE     CORE2_TASK5_STACK_SIZE
#define CORE2_THREAD5_CALL_DEPTH     CORE2_TASK5_CALL_DEPTH 

#define CORE2_THREAD6_TYPE           CORE2_TASK6_TYPE             
#define CORE2_THREAD6_PERIOD         CORE2_TASK6_PERIOD
#define CORE2_THREAD6_ACTIVED        CORE2_TASK6_ACTIVED
#define CORE2_THREAD6_PRIORITY       CORE2_TASK6_PRIORITY
#define CORE2_THREAD6_MODE           CORE2_TASK6_MODE
#define CORE2_THREAD6_STACK_SIZE     CORE2_TASK6_STACK_SIZE
#define CORE2_THREAD6_CALL_DEPTH     CORE2_TASK6_CALL_DEPTH 

#define CORE2_THREAD7_TYPE           CORE2_TASK7_TYPE             
#define CORE2_THREAD7_PERIOD         CORE2_TASK7_PERIOD
#define CORE2_THREAD7_ACTIVED        CORE2_TASK7_ACTIVED
#define CORE2_THREAD7_PRIORITY       CORE2_TASK7_PRIORITY
#define CORE2_THREAD7_MODE           CORE2_TASK7_MODE
#define CORE2_THREAD7_STACK_SIZE     CORE2_TASK7_STACK_SIZE
#define CORE2_THREAD7_CALL_DEPTH     CORE2_TASK7_CALL_DEPTH

#define CORE2_THREAD8_TYPE           CORE2_TASK8_TYPE             
#define CORE2_THREAD8_PERIOD         CORE2_TASK8_PERIOD
#define CORE2_THREAD8_ACTIVED        CORE2_TASK8_ACTIVED
#define CORE2_THREAD8_PRIORITY       CORE2_TASK8_PRIORITY
#define CORE2_THREAD8_MODE           CORE2_TASK8_MODE
#define CORE2_THREAD8_STACK_SIZE     CORE2_TASK8_STACK_SIZE
#define CORE2_THREAD8_CALL_DEPTH     CORE2_TASK8_CALL_DEPTH

#define CORE2_THREAD9_TYPE           CORE2_TASK9_TYPE             
#define CORE2_THREAD9_PERIOD         CORE2_TASK9_PERIOD
#define CORE2_THREAD9_ACTIVED        CORE2_TASK9_ACTIVED
#define CORE2_THREAD9_PRIORITY       CORE2_TASK9_PRIORITY
#define CORE2_THREAD9_MODE           CORE2_TASK9_MODE
#define CORE2_THREAD9_STACK_SIZE     CORE2_TASK9_STACK_SIZE
#define CORE2_THREAD9_CALL_DEPTH     CORE2_TASK9_CALL_DEPTH

#define CORE2_THREAD10_TYPE          CORE2_TASK10_TYPE             
#define CORE2_THREAD10_PERIOD        CORE2_TASK10_PERIOD
#define CORE2_THREAD10_ACTIVED       CORE2_TASK10_ACTIVED
#define CORE2_THREAD10_PRIORITY      CORE2_TASK10_PRIORITY
#define CORE2_THREAD10_MODE          CORE2_TASK10_MODE
#define CORE2_THREAD10_STACK_SIZE    CORE2_TASK10_STACK_SIZE
#define CORE2_THREAD10_CALL_DEPTH    CORE2_TASK10_CALL_DEPTH

#if (THREAD_GLOBAL_CONFIG_DEFINITION == ENABLE)
#include "os.h"
OS_CONST pthread_config_t os_pthread_init_config_database[CORE_MAX_ID_NUM][THREAD_MAX_ID_NUM] =
{
    {
	  {THREAD_ID0,  CORE0_THREAD0_TYPE,  CORE0_THREAD0_PERIOD,  CORE0_THREAD0_ACTIVED },
	  {THREAD_ID1,  CORE0_THREAD1_TYPE,  CORE0_THREAD1_PERIOD,  CORE0_THREAD1_ACTIVED },
	  {THREAD_ID2,  CORE0_THREAD2_TYPE,  CORE0_THREAD2_PERIOD,  CORE0_THREAD2_ACTIVED },
	  {THREAD_ID3,  CORE0_THREAD3_TYPE,  CORE0_THREAD3_PERIOD,  CORE0_THREAD3_ACTIVED },
	  {THREAD_ID4,  CORE0_THREAD4_TYPE,  CORE0_THREAD4_PERIOD,  CORE0_THREAD4_ACTIVED },
	  {THREAD_ID5,  CORE0_THREAD5_TYPE,  CORE0_THREAD5_PERIOD,  CORE0_THREAD5_ACTIVED },  
	  {THREAD_ID6,  CORE0_THREAD6_TYPE,  CORE0_THREAD6_PERIOD,  CORE0_THREAD6_ACTIVED },
	  {THREAD_ID7,  CORE0_THREAD7_TYPE,  CORE0_THREAD7_PERIOD,  CORE0_THREAD7_ACTIVED },
	  {THREAD_ID8,  CORE0_THREAD8_TYPE,  CORE0_THREAD8_PERIOD,  CORE0_THREAD8_ACTIVED },
	  {THREAD_ID9,  CORE0_THREAD9_TYPE,  CORE0_THREAD9_PERIOD,  CORE0_THREAD9_ACTIVED },
	  {THREAD_ID10, CORE0_THREAD10_TYPE, CORE0_THREAD10_PERIOD, CORE0_THREAD10_ACTIVED}
	},
	{
	  {THREAD_ID0,  CORE1_THREAD0_TYPE,  CORE1_THREAD0_PERIOD,  CORE1_THREAD0_ACTIVED },
	  {THREAD_ID1,  CORE1_THREAD1_TYPE,  CORE1_THREAD1_PERIOD,  CORE1_THREAD1_ACTIVED },
	  {THREAD_ID2,  CORE1_THREAD2_TYPE,  CORE1_THREAD2_PERIOD,  CORE1_THREAD2_ACTIVED },
	  {THREAD_ID3,  CORE1_THREAD3_TYPE,  CORE1_THREAD3_PERIOD,  CORE1_THREAD3_ACTIVED },
	  {THREAD_ID4,  CORE1_THREAD4_TYPE,  CORE1_THREAD4_PERIOD,  CORE1_THREAD4_ACTIVED },
	  {THREAD_ID5,  CORE1_THREAD5_TYPE,  CORE1_THREAD5_PERIOD,  CORE1_THREAD5_ACTIVED },  
	  {THREAD_ID6,  CORE1_THREAD6_TYPE,  CORE1_THREAD6_PERIOD,  CORE1_THREAD6_ACTIVED },
	  {THREAD_ID7,  CORE1_THREAD7_TYPE,  CORE1_THREAD7_PERIOD,  CORE1_THREAD7_ACTIVED },
	  {THREAD_ID8,  CORE1_THREAD8_TYPE,  CORE1_THREAD8_PERIOD,  CORE1_THREAD8_ACTIVED },
	  {THREAD_ID9,  CORE1_THREAD9_TYPE,  CORE1_THREAD9_PERIOD,  CORE1_THREAD9_ACTIVED },
	  {THREAD_ID10, CORE1_THREAD10_TYPE, CORE1_THREAD10_PERIOD, CORE1_THREAD10_ACTIVED}	
	},
	{
	  {THREAD_ID0,  CORE2_THREAD0_TYPE,  CORE2_THREAD0_PERIOD,  CORE2_THREAD0_ACTIVED },
	  {THREAD_ID1,  CORE2_THREAD1_TYPE,  CORE2_THREAD1_PERIOD,  CORE2_THREAD1_ACTIVED },
	  {THREAD_ID2,  CORE2_THREAD2_TYPE,  CORE2_THREAD2_PERIOD,  CORE2_THREAD2_ACTIVED },
	  {THREAD_ID3,  CORE2_THREAD3_TYPE,  CORE2_THREAD3_PERIOD,  CORE2_THREAD3_ACTIVED },
	  {THREAD_ID4,  CORE2_THREAD4_TYPE,  CORE2_THREAD4_PERIOD,  CORE2_THREAD4_ACTIVED },
	  {THREAD_ID5,  CORE2_THREAD5_TYPE,  CORE2_THREAD5_PERIOD,  CORE2_THREAD5_ACTIVED },  
	  {THREAD_ID6,  CORE2_THREAD6_TYPE,  CORE2_THREAD6_PERIOD,  CORE2_THREAD6_ACTIVED },
	  {THREAD_ID7,  CORE2_THREAD7_TYPE,  CORE2_THREAD7_PERIOD,  CORE2_THREAD7_ACTIVED },
	  {THREAD_ID8,  CORE2_THREAD8_TYPE,  CORE2_THREAD8_PERIOD,  CORE2_THREAD8_ACTIVED },
	  {THREAD_ID9,  CORE2_THREAD9_TYPE,  CORE2_THREAD9_PERIOD,  CORE2_THREAD9_ACTIVED },
	  {THREAD_ID10, CORE2_THREAD10_TYPE, CORE2_THREAD10_PERIOD, CORE2_THREAD10_ACTIVED}
	}
  
};
#include "os_kernel.h"
pthread_cond_t os_pthread_cond[CORE_MAX_ID_NUM][THREAD_MAX_ID_NUM] =
  { 
  	 {
      CORE0_PTHREAD_COND_INITIALIZER,CORE0_PTHREAD_COND_INITIALIZER,
	  CORE0_PTHREAD_COND_INITIALIZER,CORE0_PTHREAD_COND_INITIALIZER,
      CORE0_PTHREAD_COND_INITIALIZER,CORE0_PTHREAD_COND_INITIALIZER,
      CORE0_PTHREAD_COND_INITIALIZER,CORE0_PTHREAD_COND_INITIALIZER,
      CORE0_PTHREAD_COND_INITIALIZER,CORE0_PTHREAD_COND_INITIALIZER,
      CORE0_PTHREAD_COND_INITIALIZER
     },
  	 {
      CORE1_PTHREAD_COND_INITIALIZER,CORE1_PTHREAD_COND_INITIALIZER,
	  CORE1_PTHREAD_COND_INITIALIZER,CORE1_PTHREAD_COND_INITIALIZER,
      CORE1_PTHREAD_COND_INITIALIZER,CORE1_PTHREAD_COND_INITIALIZER,
      CORE1_PTHREAD_COND_INITIALIZER,CORE1_PTHREAD_COND_INITIALIZER,
      CORE1_PTHREAD_COND_INITIALIZER,CORE1_PTHREAD_COND_INITIALIZER,
      CORE1_PTHREAD_COND_INITIALIZER
     },
  	 {
      CORE2_PTHREAD_COND_INITIALIZER,CORE2_PTHREAD_COND_INITIALIZER,
	  CORE2_PTHREAD_COND_INITIALIZER,CORE2_PTHREAD_COND_INITIALIZER,
      CORE2_PTHREAD_COND_INITIALIZER,CORE2_PTHREAD_COND_INITIALIZER,
      CORE2_PTHREAD_COND_INITIALIZER,CORE2_PTHREAD_COND_INITIALIZER,
      CORE2_PTHREAD_COND_INITIALIZER,CORE2_PTHREAD_COND_INITIALIZER,
      CORE2_PTHREAD_COND_INITIALIZER
     }	  
  };

OS_CONST pthread_attr_t os_thread_attr[CORE_MAX_ID_NUM][THREAD_MAX_ID_NUM] =
	{
      { { CORE0_THREAD0_MODE, CORE0_THREAD0_CALL_DEPTH},
        { CORE0_THREAD1_MODE, CORE0_THREAD1_CALL_DEPTH},
        { CORE0_THREAD2_MODE, CORE0_THREAD2_CALL_DEPTH},
        { CORE0_THREAD3_MODE, CORE0_THREAD3_CALL_DEPTH},
        { CORE0_THREAD4_MODE, CORE0_THREAD4_CALL_DEPTH},
        { CORE0_THREAD5_MODE, CORE0_THREAD5_CALL_DEPTH},
        { CORE0_THREAD6_MODE, CORE0_THREAD6_CALL_DEPTH},
        { CORE0_THREAD7_MODE, CORE0_THREAD7_CALL_DEPTH},
        { CORE0_THREAD8_MODE, CORE0_THREAD8_CALL_DEPTH},
        { CORE0_THREAD9_MODE, CORE0_THREAD9_CALL_DEPTH},
        { CORE0_THREAD10_MODE,CORE0_THREAD10_CALL_DEPTH}
	  },
      {
	  	{ CORE1_THREAD0_MODE, CORE1_THREAD0_CALL_DEPTH},
        { CORE1_THREAD1_MODE, CORE1_THREAD1_CALL_DEPTH},
        { CORE1_THREAD2_MODE, CORE1_THREAD2_CALL_DEPTH},
        { CORE1_THREAD3_MODE, CORE1_THREAD3_CALL_DEPTH},
        { CORE1_THREAD4_MODE, CORE1_THREAD4_CALL_DEPTH},
        { CORE1_THREAD5_MODE, CORE1_THREAD5_CALL_DEPTH},
        { CORE1_THREAD6_MODE, CORE1_THREAD6_CALL_DEPTH},
        { CORE1_THREAD7_MODE, CORE1_THREAD7_CALL_DEPTH},
        { CORE1_THREAD8_MODE, CORE1_THREAD8_CALL_DEPTH},
        { CORE1_THREAD9_MODE, CORE1_THREAD9_CALL_DEPTH},
        { CORE1_THREAD10_MODE,CORE1_THREAD10_CALL_DEPTH}
	  },
	  {
	  	{ CORE2_THREAD0_MODE, CORE2_THREAD0_CALL_DEPTH},
        { CORE2_THREAD1_MODE, CORE2_THREAD1_CALL_DEPTH},
        { CORE2_THREAD2_MODE, CORE2_THREAD2_CALL_DEPTH},
        { CORE2_THREAD3_MODE, CORE2_THREAD3_CALL_DEPTH},
        { CORE2_THREAD4_MODE, CORE2_THREAD4_CALL_DEPTH},
        { CORE2_THREAD5_MODE, CORE2_THREAD5_CALL_DEPTH},
        { CORE2_THREAD6_MODE, CORE2_THREAD6_CALL_DEPTH},
        { CORE2_THREAD7_MODE, CORE2_THREAD7_CALL_DEPTH},
        { CORE2_THREAD8_MODE, CORE2_THREAD8_CALL_DEPTH},
        { CORE2_THREAD9_MODE, CORE2_THREAD9_CALL_DEPTH},
        { CORE2_THREAD10_MODE,CORE2_THREAD10_CALL_DEPTH}
	  }
	};
#include "os_kernel.h"
#include "os_trace.h"

void thread_done_after_task(pthread_config_t *pthread_config,CORE_ID_t core_id )
{ 	
  /* Trace */
  os_trace_task_time_end(core_id,pthread_config->task_id);

  if(pthread_config->type == EVENT)
  {
      /* Active thread */
	  pthread_cond_broadcast(&os_pthread_cond[core_id][pthread_config->actived_task_id]);
  }
  else if((pthread_config->type == PERIODIC)||
  	      (pthread_config->type == NO_DEFINITION))
  {
      /* Do nothing */
  }
}

void thread_done_before_task(pthread_config_t *pthread_config,CORE_ID_t core_id )
{ 
  if(pthread_config->type == EVENT)
  {
      pthread_cond_wait(&os_pthread_cond[core_id][pthread_config->task_id]);
  }
  else if(pthread_config->type == PERIODIC)
  {
	  pthread_cond_timedwait_np((uint16_t)(pthread_config->period));
  }
  else if(pthread_config->type == NO_DEFINITION)
  {
     /* Do nothing. */
  }
  /* trace */
  os_trace_task_time_begin(core_id,pthread_config->task_id);
}
#endif
#endif

