/****************************************************************************/
/* FILE NAME:    core1_task_cfg.h                                           */
/* CREATE ON:    Aug 26, 2015                                               */
/* AUTHER:       Yanpeng.xi                                                 */
/* DESCRIPTION:  The h file includes the task configuration of AURIX core1  */
/*               os                                                         */
/* COMMENT:      Multicore OS based on Aurix 275C app kit and TASKING 4.3   */
/*               compiler                                                   */
/****************************************************************************/ 
#ifndef CORE1_TASK_CFG_H_
#define CORE1_TASK_CFG_H_ 

/****************************************************************************/
/* Feature Include Files                                                    */
/****************************************************************************/
#include "core0_task_manager.h"
#include "core1_task_manager.h"
#include "core2_task_manager.h"

/****************************************************************************/
/* Macro Definitions                                                        */
/****************************************************************************/

/****************************************************************************/
/* <CORE1> Task Configuration                                               */
/****************************************************************************/
#if (CORE1_TASK0_SWITCH == ON) 
#define CORE1_TASK0_TYPE             NO_DEFINITION             
#define CORE1_TASK0_PERIOD           (0)  /* unit:ms */
#define CORE1_TASK0_ACTIVED          NO_ACTIVED_TASK
#define CORE1_TASK0_ACTIVED_COREID   CORE_ID1
#define CORE1_TASK0_PRIORITY         LEVEL_0
#define CORE1_TASK0_MODE             SUPER
#define CORE1_TASK0_STACK_SIZE       PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK0_CALL_DEPTH       CALL_DEPTH_OVERFLOW_AT_64  
#endif	
#if (CORE1_TASK1_SWITCH == ON)
#define CORE1_TASK1_TYPE             PERIODIC
#define CORE1_TASK1_PERIOD           (300)  /* unit:ms */
#define CORE1_TASK1_ACTIVED          NO_ACTIVED_TASK
#define CORE1_TASK1_ACTIVED_COREID   CORE_ID1
#define CORE1_TASK1_PRIORITY         LEVEL_1
#define CORE1_TASK1_MODE             SUPER
#define CORE1_TASK1_STACK_SIZE       PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK1_CALL_DEPTH       CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK2_SWITCH == ON)
#define CORE1_TASK2_TYPE             PERIODIC
#define CORE1_TASK2_PERIOD           (1000)  /* unit:ms */
#define CORE1_TASK2_ACTIVED          CORE1_TASK_ID3
#define CORE1_TASK2_ACTIVED_COREID   CORE_ID1
#define CORE1_TASK2_PRIORITY         LEVEL_2
#define CORE1_TASK2_MODE             SUPER
#define CORE1_TASK2_STACK_SIZE       PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK2_CALL_DEPTH       CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK3_SWITCH == ON)
#define CORE1_TASK3_TYPE             EVENT
#define CORE1_TASK3_PERIOD           (0)
#define CORE1_TASK3_ACTIVED          CORE1_TASK_ID4
#define CORE1_TASK3_ACTIVED_COREID   CORE_ID1
#define CORE1_TASK3_PRIORITY         LEVEL_3
#define CORE1_TASK3_MODE             SUPER
#define CORE1_TASK3_STACK_SIZE       PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK3_CALL_DEPTH       CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK4_SWITCH == ON)
#define CORE1_TASK4_TYPE             EVENT
#define CORE1_TASK4_PERIOD           (0)
#define CORE1_TASK4_ACTIVED          CORE1_TASK_ID5
#define CORE1_TASK4_ACTIVED_COREID   CORE_ID1
#define CORE1_TASK4_PRIORITY         LEVEL_4
#define CORE1_TASK4_MODE             SUPER
#define CORE1_TASK4_STACK_SIZE       PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK4_CALL_DEPTH       CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK5_SWITCH == ON)
#define CORE1_TASK5_TYPE             EVENT
#define CORE1_TASK5_PERIOD           (0)
#define CORE1_TASK5_ACTIVED          CORE1_TASK_ID6
#define CORE1_TASK5_ACTIVED_COREID   CORE_ID1
#define CORE1_TASK5_PRIORITY         LEVEL_5
#define CORE1_TASK5_MODE             SUPER
#define CORE1_TASK5_STACK_SIZE       PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK5_CALL_DEPTH       CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK6_SWITCH == ON)
#define CORE1_TASK6_TYPE             EVENT
#define CORE1_TASK6_PERIOD           (0)
#define CORE1_TASK6_ACTIVED          CORE1_TASK_ID7
#define CORE1_TASK6_ACTIVED_COREID   CORE_ID1
#define CORE1_TASK6_PRIORITY         LEVEL_6
#define CORE1_TASK6_MODE             SUPER
#define CORE1_TASK6_STACK_SIZE       PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK6_CALL_DEPTH       CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK7_SWITCH == ON)
#define CORE1_TASK7_TYPE             EVENT
#define CORE1_TASK7_PERIOD           (0)
#define CORE1_TASK7_ACTIVED          NO_ACTIVED_TASK
#define CORE1_TASK7_ACTIVED_COREID   CORE_ID1
#define CORE1_TASK7_PRIORITY         LEVEL_7
#define CORE1_TASK7_MODE             SUPER
#define CORE1_TASK7_STACK_SIZE       PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK7_CALL_DEPTH       CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK8_SWITCH == ON)
#define CORE1_TASK8_TYPE             EVENT
#define CORE1_TASK8_PERIOD           (0)
#define CORE1_TASK8_ACTIVED          CORE1_TASK_ID9
#define CORE1_TASK8_ACTIVED_COREID   CORE_ID1
#define CORE1_TASK8_PRIORITY         LEVEL_8
#define CORE1_TASK8_MODE             SUPER
#define CORE1_TASK8_STACK_SIZE       PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK8_CALL_DEPTH       CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK9_SWITCH == ON)
#define CORE1_TASK9_TYPE             EVENT
#define CORE1_TASK9_PERIOD           (0)
#define CORE1_TASK9_ACTIVED          NO_ACTIVED_TASK
#define CORE1_TASK9_ACTIVED_COREID   CORE_ID1
#define CORE1_TASK9_PRIORITY         LEVEL_9
#define CORE1_TASK9_MODE             SUPER
#define CORE1_TASK9_STACK_SIZE       PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK9_CALL_DEPTH       CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK10_SWITCH == ON)
#define CORE1_TASK10_TYPE            PERIODIC
#define CORE1_TASK10_PERIOD          (1000)  /* unit:ms */
#define CORE1_TASK10_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK10_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK10_PRIORITY        LEVEL_10
#define CORE1_TASK10_MODE            SUPER
#define CORE1_TASK10_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK10_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK11_SWITCH == ON)
#define CORE1_TASK11_TYPE            PERIODIC
#define CORE1_TASK11_PERIOD          (300)  /* unit:ms */
#define CORE1_TASK11_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK11_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK11_PRIORITY        LEVEL_1
#define CORE1_TASK11_MODE            SUPER
#define CORE1_TASK11_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK11_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK12_SWITCH == ON)
#define CORE1_TASK12_TYPE            PERIODIC
#define CORE1_TASK12_PERIOD          (500)  /* unit:ms */
#define CORE1_TASK12_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK12_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK12_PRIORITY        LEVEL_2
#define CORE1_TASK12_MODE            SUPER
#define CORE1_TASK12_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK12_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK13_SWITCH == ON)
#define CORE1_TASK13_TYPE            EVENT
#define CORE1_TASK13_PERIOD          (0)
#define CORE1_TASK13_ACTIVED         CORE1_TASK_ID4
#define CORE1_TASK13_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK13_PRIORITY        LEVEL_3
#define CORE1_TASK13_MODE            SUPER
#define CORE1_TASK13_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK13_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK14_SWITCH == ON)
#define CORE1_TASK14_TYPE            EVENT
#define CORE1_TASK14_PERIOD          (0)
#define CORE1_TASK14_ACTIVED         CORE1_TASK_ID5
#define CORE1_TASK14_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK14_PRIORITY        LEVEL_4
#define CORE1_TASK14_MODE            SUPER
#define CORE1_TASK14_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK14_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK15_SWITCH == ON)
#define CORE1_TASK15_TYPE            EVENT
#define CORE1_TASK15_PERIOD          (0)
#define CORE1_TASK15_ACTIVED         CORE1_TASK_ID6
#define CORE1_TASK15_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK15_PRIORITY        LEVEL_5
#define CORE1_TASK15_MODE            SUPER
#define CORE1_TASK15_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK15_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK16_SWITCH == ON)
#define CORE1_TASK16_TYPE            EVENT
#define CORE1_TASK16_PERIOD          (0)
#define CORE1_TASK16_ACTIVED         CORE1_TASK_ID7
#define CORE1_TASK16_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK16_PRIORITY        LEVEL_6
#define CORE1_TASK16_MODE            SUPER
#define CORE1_TASK16_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK16_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK17_SWITCH == ON)
#define CORE1_TASK17_TYPE            EVENT
#define CORE1_TASK17_PERIOD          (0)
#define CORE1_TASK17_ACTIVED         CORE1_TASK_ID8
#define CORE1_TASK17_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK17_PRIORITY        LEVEL_7
#define CORE1_TASK17_MODE            SUPER
#define CORE1_TASK17_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK17_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK18_SWITCH == ON)
#define CORE1_TASK18_TYPE            EVENT
#define CORE1_TASK18_PERIOD          (0)
#define CORE1_TASK18_ACTIVED         CORE1_TASK_ID9
#define CORE1_TASK18_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK18_PRIORITY        LEVEL_8
#define CORE1_TASK18_MODE            SUPER
#define CORE1_TASK18_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK18_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK19_SWITCH == ON)
#define CORE1_TASK19_TYPE            EVENT
#define CORE1_TASK19_PERIOD          (0)
#define CORE1_TASK19_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK19_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK19_PRIORITY        LEVEL_9
#define CORE1_TASK19_MODE            SUPER
#define CORE1_TASK19_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK19_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif
#if (CORE1_TASK20_SWITCH == ON)
#define CORE1_TASK20_TYPE            EVENT
#define CORE1_TASK20_PERIOD          (0)
#define CORE1_TASK20_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK20_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK20_PRIORITY        LEVEL_9
#define CORE1_TASK20_MODE            SUPER
#define CORE1_TASK20_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK20_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif
#if (CORE1_TASK21_SWITCH == ON)
#define CORE1_TASK21_TYPE            PERIODIC
#define CORE1_TASK21_PERIOD          (300)  /* unit:ms */
#define CORE1_TASK21_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK21_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK21_PRIORITY        LEVEL_2
#define CORE1_TASK21_MODE            SUPER
#define CORE1_TASK21_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK21_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK22_SWITCH == ON)
#define CORE1_TASK22_TYPE            PERIODIC
#define CORE1_TASK22_PERIOD          (500)  /* unit:ms */
#define CORE1_TASK22_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK22_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK22_PRIORITY        LEVEL_2
#define CORE1_TASK22_MODE            SUPER
#define CORE1_TASK22_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK22_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK23_SWITCH == ON)
#define CORE1_TASK23_TYPE            EVENT
#define CORE1_TASK23_PERIOD          (0)
#define CORE1_TASK23_ACTIVED         CORE1_TASK_ID4
#define CORE1_TASK23_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK23_PRIORITY        LEVEL_3
#define CORE1_TASK23_MODE            SUPER
#define CORE1_TASK23_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK23_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK24_SWITCH == ON)
#define CORE1_TASK24_TYPE            EVENT
#define CORE1_TASK24_PERIOD          (0)
#define CORE1_TASK24_ACTIVED         CORE1_TASK_ID5
#define CORE1_TASK24_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK24_PRIORITY        LEVEL_4
#define CORE1_TASK24_MODE            SUPER
#define CORE1_TASK24_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK24_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK25_SWITCH == ON)
#define CORE1_TASK25_TYPE            EVENT
#define CORE1_TASK25_PERIOD          (0)
#define CORE1_TASK25_ACTIVED         CORE1_TASK_ID6
#define CORE1_TASK25_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK25_PRIORITY        LEVEL_5
#define CORE1_TASK25_MODE            SUPER
#define CORE1_TASK25_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK25_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK26_SWITCH == ON)
#define CORE1_TASK26_TYPE            EVENT
#define CORE1_TASK26_PERIOD          (0)
#define CORE1_TASK26_ACTIVED         CORE1_TASK_ID7
#define CORE1_TASK26_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK26_PRIORITY        LEVEL_6
#define CORE1_TASK26_MODE            SUPER
#define CORE1_TASK26_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK26_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK27_SWITCH == ON)
#define CORE1_TASK27_TYPE            EVENT
#define CORE1_TASK27_PERIOD          (0)
#define CORE1_TASK27_ACTIVED         CORE1_TASK_ID8
#define CORE1_TASK27_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK27_PRIORITY        LEVEL_7
#define CORE1_TASK27_MODE            SUPER
#define CORE1_TASK27_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK27_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK28_SWITCH == ON)
#define CORE1_TASK28_TYPE            EVENT
#define CORE1_TASK28_PERIOD          (0)
#define CORE1_TASK28_ACTIVED         CORE1_TASK_ID9
#define CORE1_TASK28_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK28_PRIORITY        LEVEL_8
#define CORE1_TASK28_MODE            SUPER
#define CORE1_TASK28_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK28_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK29_SWITCH == ON)
#define CORE1_TASK29_TYPE            EVENT
#define CORE1_TASK29_PERIOD          (0)
#define CORE1_TASK29_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK29_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK29_PRIORITY        LEVEL_9
#define CORE1_TASK29_MODE            SUPER
#define CORE1_TASK29_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK29_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK30_SWITCH == ON)
#define CORE1_TASK30_TYPE            PERIODIC
#define CORE1_TASK30_PERIOD          (300)  /* unit:ms */
#define CORE1_TASK30_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK30_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK30_PRIORITY        LEVEL_3
#define CORE1_TASK30_MODE            SUPER
#define CORE1_TASK30_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK30_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif
#if (CORE1_TASK31_SWITCH == ON)
#define CORE1_TASK31_TYPE            PERIODIC
#define CORE1_TASK31_PERIOD          (300)  /* unit:ms */
#define CORE1_TASK31_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK31_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK31_PRIORITY        LEVEL_3
#define CORE1_TASK31_MODE            SUPER
#define CORE1_TASK31_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK31_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK32_SWITCH == ON)
#define CORE1_TASK32_TYPE            PERIODIC
#define CORE1_TASK32_PERIOD          (500)  /* unit:ms */
#define CORE1_TASK32_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK32_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK32_PRIORITY        LEVEL_2
#define CORE1_TASK32_MODE            SUPER
#define CORE1_TASK32_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK32_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK33_SWITCH == ON)
#define CORE1_TASK33_TYPE            EVENT
#define CORE1_TASK33_PERIOD          (0)
#define CORE1_TASK33_ACTIVED         CORE1_TASK_ID4
#define CORE1_TASK33_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK33_PRIORITY        LEVEL_3
#define CORE1_TASK33_MODE            SUPER
#define CORE1_TASK33_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK33_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK34_SWITCH == ON)
#define CORE1_TASK34_TYPE            EVENT
#define CORE1_TASK34_PERIOD          (0)
#define CORE1_TASK34_ACTIVED         CORE1_TASK_ID5
#define CORE1_TASK34_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK34_PRIORITY        LEVEL_4
#define CORE1_TASK34_MODE            SUPER
#define CORE1_TASK34_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK34_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK35_SWITCH == ON)
#define CORE1_TASK35_TYPE            EVENT
#define CORE1_TASK35_PERIOD          (0)
#define CORE1_TASK35_ACTIVED         CORE1_TASK_ID6
#define CORE1_TASK35_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK35_PRIORITY        LEVEL_5
#define CORE1_TASK35_MODE            SUPER
#define CORE1_TASK35_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK35_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK36_SWITCH == ON)
#define CORE1_TASK36_TYPE            EVENT
#define CORE1_TASK36_PERIOD          (0)
#define CORE1_TASK36_ACTIVED         CORE1_TASK_ID7
#define CORE1_TASK36_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK36_PRIORITY        LEVEL_6
#define CORE1_TASK36_MODE            SUPER
#define CORE1_TASK36_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK36_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK37_SWITCH == ON)
#define CORE1_TASK37_TYPE            EVENT
#define CORE1_TASK37_PERIOD          (0)
#define CORE1_TASK37_ACTIVED         CORE1_TASK_ID8
#define CORE1_TASK37_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK37_PRIORITY        LEVEL_7
#define CORE1_TASK37_MODE            SUPER
#define CORE1_TASK37_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK37_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK38_SWITCH == ON)
#define CORE1_TASK38_TYPE            EVENT
#define CORE1_TASK38_PERIOD          (0)
#define CORE1_TASK38_ACTIVED         CORE1_TASK_ID9
#define CORE1_TASK38_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK38_PRIORITY        LEVEL_8
#define CORE1_TASK38_MODE            SUPER
#define CORE1_TASK38_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK38_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK39_SWITCH == ON)
#define CORE1_TASK39_TYPE            EVENT
#define CORE1_TASK39_PERIOD          (0)
#define CORE1_TASK39_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK39_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK39_PRIORITY        LEVEL_9
#define CORE1_TASK39_MODE            SUPER
#define CORE1_TASK39_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK39_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK40_SWITCH == ON)
#define CORE1_TASK40_TYPE            EVENT
#define CORE1_TASK40_PERIOD          (0)
#define CORE1_TASK40_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK40_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK40_PRIORITY        LEVEL_9
#define CORE1_TASK40_MODE            SUPER
#define CORE1_TASK40_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK40_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif
#if (CORE1_TASK41_SWITCH == ON)
#define CORE1_TASK41_TYPE            PERIODIC
#define CORE1_TASK41_PERIOD          (300)  /* unit:ms */
#define CORE1_TASK41_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK41_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK41_PRIORITY        LEVEL_4
#define CORE1_TASK41_MODE            SUPER
#define CORE1_TASK41_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK41_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK42_SWITCH == ON)
#define CORE1_TASK42_TYPE            PERIODIC
#define CORE1_TASK42_PERIOD          (500)  /* unit:ms */
#define CORE1_TASK42_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK42_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK42_PRIORITY        LEVEL_2
#define CORE1_TASK42_MODE            SUPER
#define CORE1_TASK42_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK42_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK43_SWITCH == ON)
#define CORE1_TASK43_TYPE            EVENT
#define CORE1_TASK43_PERIOD          (0)
#define CORE1_TASK43_ACTIVED         CORE1_TASK_ID4
#define CORE1_TASK43_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK43_PRIORITY        LEVEL_3
#define CORE1_TASK43_MODE            SUPER
#define CORE1_TASK43_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK43_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK44_SWITCH == ON)
#define CORE1_TASK44_TYPE            EVENT
#define CORE1_TASK44_PERIOD          (0)
#define CORE1_TASK44_ACTIVED         CORE1_TASK_ID5
#define CORE1_TASK44_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK44_PRIORITY        LEVEL_4
#define CORE1_TASK44_MODE            SUPER
#define CORE1_TASK44_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK44_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK45_SWITCH == ON)
#define CORE1_TASK45_TYPE            EVENT
#define CORE1_TASK45_PERIOD          (0)
#define CORE1_TASK45_ACTIVED         CORE1_TASK_ID6
#define CORE1_TASK45_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK45_PRIORITY        LEVEL_5
#define CORE1_TASK45_MODE            SUPER
#define CORE1_TASK45_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK45_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK46_SWITCH == ON)
#define CORE1_TASK46_TYPE            EVENT
#define CORE1_TASK46_PERIOD          (0)
#define CORE1_TASK46_ACTIVED         CORE1_TASK_ID7
#define CORE1_TASK46_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK46_PRIORITY        LEVEL_6
#define CORE1_TASK46_MODE            SUPER
#define CORE1_TASK46_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK46_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK47_SWITCH == ON)
#define CORE1_TASK47_TYPE            EVENT
#define CORE1_TASK47_PERIOD          (0)
#define CORE1_TASK47_ACTIVED         CORE1_TASK_ID8
#define CORE1_TASK47_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK47_PRIORITY        LEVEL_7
#define CORE1_TASK47_MODE            SUPER
#define CORE1_TASK47_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK47_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK48_SWITCH == ON)
#define CORE1_TASK48_TYPE            EVENT
#define CORE1_TASK48_PERIOD          (0)
#define CORE1_TASK48_ACTIVED         CORE1_TASK_ID9
#define CORE1_TASK48_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK48_PRIORITY        LEVEL_8
#define CORE1_TASK48_MODE            SUPER
#define CORE1_TASK48_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK48_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK49_SWITCH == ON)
#define CORE1_TASK49_TYPE            EVENT
#define CORE1_TASK49_PERIOD          (0)
#define CORE1_TASK49_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK49_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK49_PRIORITY        LEVEL_9
#define CORE1_TASK49_MODE            SUPER
#define CORE1_TASK49_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK49_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK50_SWITCH == ON)
#define CORE1_TASK50_TYPE            EVENT
#define CORE1_TASK50_PERIOD          (0)
#define CORE1_TASK50_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK50_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK50_PRIORITY        LEVEL_9
#define CORE1_TASK50_MODE            SUPER
#define CORE1_TASK50_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK50_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif
#if (CORE1_TASK51_SWITCH == ON)
#define CORE1_TASK51_TYPE            PERIODIC
#define CORE1_TASK51_PERIOD          (300)  /* unit:ms */
#define CORE1_TASK51_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK51_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK51_PRIORITY        LEVEL_5
#define CORE1_TASK51_MODE            SUPER
#define CORE1_TASK51_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK51_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK52_SWITCH == ON)
#define CORE1_TASK52_TYPE            PERIODIC
#define CORE1_TASK52_PERIOD          (500)  /* unit:ms */
#define CORE1_TASK52_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK52_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK52_PRIORITY        LEVEL_2
#define CORE1_TASK52_MODE            SUPER
#define CORE1_TASK52_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK52_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK53_SWITCH == ON)
#define CORE1_TASK53_TYPE            EVENT
#define CORE1_TASK53_PERIOD          (0)
#define CORE1_TASK53_ACTIVED         CORE1_TASK_ID4
#define CORE1_TASK53_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK53_PRIORITY        LEVEL_3
#define CORE1_TASK53_MODE            SUPER
#define CORE1_TASK53_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK53_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK54_SWITCH == ON)
#define CORE1_TASK54_TYPE            EVENT
#define CORE1_TASK54_PERIOD          (0)
#define CORE1_TASK54_ACTIVED         CORE1_TASK_ID5
#define CORE1_TASK54_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK54_PRIORITY        LEVEL_4
#define CORE1_TASK54_MODE            SUPER
#define CORE1_TASK54_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK54_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK55_SWITCH == ON)
#define CORE1_TASK55_TYPE            EVENT
#define CORE1_TASK55_PERIOD          (0)
#define CORE1_TASK55_ACTIVED         CORE1_TASK_ID6
#define CORE1_TASK55_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK55_PRIORITY        LEVEL_5
#define CORE1_TASK55_MODE            SUPER
#define CORE1_TASK55_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK55_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK56_SWITCH == ON)
#define CORE1_TASK56_TYPE            EVENT
#define CORE1_TASK56_PERIOD          (0)
#define CORE1_TASK56_ACTIVED         CORE1_TASK_ID7
#define CORE1_TASK56_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK56_PRIORITY        LEVEL_6
#define CORE1_TASK56_MODE            SUPER
#define CORE1_TASK56_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK56_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK57_SWITCH == ON)
#define CORE1_TASK57_TYPE            EVENT
#define CORE1_TASK57_PERIOD          (0)
#define CORE1_TASK57_ACTIVED         CORE1_TASK_ID8
#define CORE1_TASK57_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK57_PRIORITY        LEVEL_7
#define CORE1_TASK57_MODE            SUPER
#define CORE1_TASK57_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK57_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK58_SWITCH == ON)
#define CORE1_TASK58_TYPE            EVENT
#define CORE1_TASK58_PERIOD          (0)
#define CORE1_TASK58_ACTIVED         CORE1_TASK_ID9
#define CORE1_TASK58_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK58_PRIORITY        LEVEL_8
#define CORE1_TASK58_MODE            SUPER
#define CORE1_TASK58_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK58_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK59_SWITCH == ON)
#define CORE1_TASK59_TYPE            EVENT
#define CORE1_TASK59_PERIOD          (0)
#define CORE1_TASK59_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK59_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK59_PRIORITY        LEVEL_9
#define CORE1_TASK59_MODE            SUPER
#define CORE1_TASK59_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK59_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK60_SWITCH == ON)
#define CORE1_TASK60_TYPE            EVENT
#define CORE1_TASK60_PERIOD          (0)
#define CORE1_TASK60_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK60_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK60_PRIORITY        LEVEL_9
#define CORE1_TASK60_MODE            SUPER
#define CORE1_TASK60_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK60_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK61_SWITCH == ON)
#define CORE1_TASK61_TYPE            PERIODIC
#define CORE1_TASK61_PERIOD          (300)  /* unit:ms */
#define CORE1_TASK61_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK61_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK61_PRIORITY        LEVEL_6
#define CORE1_TASK61_MODE            SUPER
#define CORE1_TASK61_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK61_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK62_SWITCH == ON)
#define CORE1_TASK62_TYPE            PERIODIC
#define CORE1_TASK62_PERIOD          (500)  /* unit:ms */
#define CORE1_TASK62_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK62_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK62_PRIORITY        LEVEL_2
#define CORE1_TASK62_MODE            SUPER
#define CORE1_TASK62_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK62_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK63_SWITCH == ON)
#define CORE1_TASK63_TYPE            EVENT
#define CORE1_TASK63_PERIOD          (0)
#define CORE1_TASK63_ACTIVED         CORE1_TASK_ID4
#define CORE1_TASK63_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK63_PRIORITY        LEVEL_3
#define CORE1_TASK63_MODE            SUPER
#define CORE1_TASK63_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK63_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK64_SWITCH == ON)
#define CORE1_TASK64_TYPE            EVENT
#define CORE1_TASK64_PERIOD          (0)
#define CORE1_TASK64_ACTIVED         CORE1_TASK_ID5
#define CORE1_TASK64_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK64_PRIORITY        LEVEL_4
#define CORE1_TASK64_MODE            SUPER
#define CORE1_TASK64_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK64_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK65_SWITCH == ON)
#define CORE1_TASK65_TYPE            EVENT
#define CORE1_TASK65_PERIOD          (0)
#define CORE1_TASK65_ACTIVED         CORE1_TASK_ID6
#define CORE1_TASK65_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK65_PRIORITY        LEVEL_5
#define CORE1_TASK65_MODE            SUPER
#define CORE1_TASK65_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK65_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK66_SWITCH == ON)
#define CORE1_TASK66_TYPE            EVENT
#define CORE1_TASK66_PERIOD          (0)
#define CORE1_TASK66_ACTIVED         CORE1_TASK_ID7
#define CORE1_TASK66_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK66_PRIORITY        LEVEL_6
#define CORE1_TASK66_MODE            SUPER
#define CORE1_TASK66_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK66_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK67_SWITCH == ON)
#define CORE1_TASK67_TYPE            EVENT
#define CORE1_TASK67_PERIOD          (0)
#define CORE1_TASK67_ACTIVED         CORE1_TASK_ID8
#define CORE1_TASK67_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK67_PRIORITY        LEVEL_7
#define CORE1_TASK67_MODE            SUPER
#define CORE1_TASK67_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK67_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK68_SWITCH == ON)
#define CORE1_TASK68_TYPE            EVENT
#define CORE1_TASK68_PERIOD          (0)
#define CORE1_TASK68_ACTIVED         CORE1_TASK_ID9
#define CORE1_TASK68_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK68_PRIORITY        LEVEL_8
#define CORE1_TASK68_MODE            SUPER
#define CORE1_TASK68_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK68_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK69_SWITCH == ON)
#define CORE1_TASK69_TYPE            EVENT
#define CORE1_TASK69_PERIOD          (0)
#define CORE1_TASK69_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK69_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK69_PRIORITY        LEVEL_9
#define CORE1_TASK69_MODE            SUPER
#define CORE1_TASK69_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK69_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK70_SWITCH == ON)
#define CORE1_TASK70_TYPE            PERIODIC
#define CORE1_TASK70_PERIOD          (300)  /* unit:ms */
#define CORE1_TASK70_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK70_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK70_PRIORITY        LEVEL_7
#define CORE1_TASK70_MODE            SUPER
#define CORE1_TASK70_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK70_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif
#if (CORE1_TASK71_SWITCH == ON)
#define CORE1_TASK71_TYPE            PERIODIC
#define CORE1_TASK71_PERIOD          (300)  /* unit:ms */
#define CORE1_TASK71_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK71_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK71_PRIORITY        LEVEL_7
#define CORE1_TASK71_MODE            SUPER
#define CORE1_TASK71_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK71_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK72_SWITCH == ON)
#define CORE1_TASK72_TYPE            PERIODIC
#define CORE1_TASK72_PERIOD          (500)  /* unit:ms */
#define CORE1_TASK72_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK72_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK72_PRIORITY        LEVEL_2
#define CORE1_TASK72_MODE            SUPER
#define CORE1_TASK72_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK72_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK73_SWITCH == ON)
#define CORE1_TASK73_TYPE            EVENT
#define CORE1_TASK73_PERIOD          (0)
#define CORE1_TASK73_ACTIVED         CORE1_TASK_ID4
#define CORE1_TASK73_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK73_PRIORITY        LEVEL_3
#define CORE1_TASK73_MODE            SUPER
#define CORE1_TASK73_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK73_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK74_SWITCH == ON)
#define CORE1_TASK74_TYPE            EVENT
#define CORE1_TASK74_PERIOD          (0)
#define CORE1_TASK74_ACTIVED         CORE1_TASK_ID5
#define CORE1_TASK74_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK74_PRIORITY        LEVEL_4
#define CORE1_TASK74_MODE            SUPER
#define CORE1_TASK74_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK74_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK75_SWITCH == ON)
#define CORE1_TASK75_TYPE            EVENT
#define CORE1_TASK75_PERIOD          (0)
#define CORE1_TASK75_ACTIVED         CORE1_TASK_ID6
#define CORE1_TASK75_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK75_PRIORITY        LEVEL_5
#define CORE1_TASK75_MODE            SUPER
#define CORE1_TASK75_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK75_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK76_SWITCH == ON)
#define CORE1_TASK76_TYPE            EVENT
#define CORE1_TASK76_PERIOD          (0)
#define CORE1_TASK76_ACTIVED         CORE1_TASK_ID7
#define CORE1_TASK76_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK76_PRIORITY        LEVEL_6
#define CORE1_TASK76_MODE            SUPER
#define CORE1_TASK76_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK76_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK77_SWITCH == ON)
#define CORE1_TASK77_TYPE            EVENT
#define CORE1_TASK77_PERIOD          (0)
#define CORE1_TASK77_ACTIVED         CORE1_TASK_ID8
#define CORE1_TASK77_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK77_PRIORITY        LEVEL_7
#define CORE1_TASK77_MODE            SUPER
#define CORE1_TASK77_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK77_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK78_SWITCH == ON)
#define CORE1_TASK78_TYPE            EVENT
#define CORE1_TASK78_PERIOD          (0)
#define CORE1_TASK78_ACTIVED         CORE1_TASK_ID9
#define CORE1_TASK78_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK78_PRIORITY        LEVEL_8
#define CORE1_TASK78_MODE            SUPER
#define CORE1_TASK78_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK78_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK79_SWITCH == ON)
#define CORE1_TASK79_TYPE            EVENT
#define CORE1_TASK79_PERIOD          (0)
#define CORE1_TASK79_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK79_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK79_PRIORITY        LEVEL_9
#define CORE1_TASK79_MODE            SUPER
#define CORE1_TASK79_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK79_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK80_SWITCH == ON)
#define CORE1_TASK80_TYPE            PERIODIC
#define CORE1_TASK80_PERIOD          (300)  /* unit:ms */
#define CORE1_TASK80_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK80_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK80_PRIORITY        LEVEL_8
#define CORE1_TASK80_MODE            SUPER
#define CORE1_TASK80_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK80_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif
#if (CORE1_TASK81_SWITCH == ON)
#define CORE1_TASK81_TYPE            PERIODIC
#define CORE1_TASK81_PERIOD          (300)  /* unit:ms */
#define CORE1_TASK81_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK81_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK81_PRIORITY        LEVEL_8
#define CORE1_TASK81_MODE            SUPER
#define CORE1_TASK81_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK81_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK82_SWITCH == ON)
#define CORE1_TASK82_TYPE            PERIODIC
#define CORE1_TASK82_PERIOD          (500)  /* unit:ms */
#define CORE1_TASK82_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK82_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK82_PRIORITY        LEVEL_2
#define CORE1_TASK82_MODE            SUPER
#define CORE1_TASK82_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK82_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK83_SWITCH == ON)
#define CORE1_TASK83_TYPE            EVENT
#define CORE1_TASK83_PERIOD          (0)
#define CORE1_TASK83_ACTIVED         CORE1_TASK_ID4
#define CORE1_TASK83_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK83_PRIORITY        LEVEL_3
#define CORE1_TASK83_MODE            SUPER
#define CORE1_TASK83_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK83_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK84_SWITCH == ON)
#define CORE1_TASK84_TYPE            EVENT
#define CORE1_TASK84_PERIOD          (0)
#define CORE1_TASK84_ACTIVED         CORE1_TASK_ID5
#define CORE1_TASK84_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK84_PRIORITY        LEVEL_4
#define CORE1_TASK84_MODE            SUPER
#define CORE1_TASK84_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK84_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK85_SWITCH == ON)
#define CORE1_TASK85_TYPE            EVENT
#define CORE1_TASK85_PERIOD          (0)
#define CORE1_TASK85_ACTIVED         CORE1_TASK_ID6
#define CORE1_TASK85_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK85_PRIORITY        LEVEL_5
#define CORE1_TASK85_MODE            SUPER
#define CORE1_TASK85_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK85_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK86_SWITCH == ON)
#define CORE1_TASK86_TYPE            EVENT
#define CORE1_TASK86_PERIOD          (0)
#define CORE1_TASK86_ACTIVED         CORE1_TASK_ID7
#define CORE1_TASK86_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK86_PRIORITY        LEVEL_6
#define CORE1_TASK86_MODE            SUPER
#define CORE1_TASK86_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK86_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK87_SWITCH == ON)
#define CORE1_TASK87_TYPE            EVENT
#define CORE1_TASK87_PERIOD          (0)
#define CORE1_TASK87_ACTIVED         CORE1_TASK_ID8
#define CORE1_TASK87_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK87_PRIORITY        LEVEL_7
#define CORE1_TASK87_MODE            SUPER
#define CORE1_TASK87_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK87_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK88_SWITCH == ON)
#define CORE1_TASK88_TYPE            EVENT
#define CORE1_TASK88_PERIOD          (0)
#define CORE1_TASK88_ACTIVED         CORE1_TASK_ID9
#define CORE1_TASK88_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK88_PRIORITY        LEVEL_8
#define CORE1_TASK88_MODE            SUPER
#define CORE1_TASK88_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK88_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK89_SWITCH == ON)
#define CORE1_TASK89_TYPE            EVENT
#define CORE1_TASK89_PERIOD          (0)
#define CORE1_TASK89_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK89_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK89_PRIORITY        LEVEL_9
#define CORE1_TASK89_MODE            SUPER
#define CORE1_TASK89_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK89_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK90_SWITCH == ON)
#define CORE1_TASK90_TYPE            PERIODIC
#define CORE1_TASK90_PERIOD          (300)  /* unit:ms */
#define CORE1_TASK90_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK90_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK90_PRIORITY        LEVEL_9
#define CORE1_TASK90_MODE            SUPER
#define CORE1_TASK90_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK90_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK91_SWITCH == ON)
#define CORE1_TASK91_TYPE            PERIODIC
#define CORE1_TASK91_PERIOD          (300)  /* unit:ms */
#define CORE1_TASK91_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK91_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK91_PRIORITY        LEVEL_9
#define CORE1_TASK91_MODE            SUPER
#define CORE1_TASK91_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK91_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK92_SWITCH == ON)
#define CORE1_TASK92_TYPE            PERIODIC
#define CORE1_TASK92_PERIOD          (500)  /* unit:ms */
#define CORE1_TASK92_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK92_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK92_PRIORITY        LEVEL_2
#define CORE1_TASK92_MODE            SUPER
#define CORE1_TASK92_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK92_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK93_SWITCH == ON)
#define CORE1_TASK93_TYPE            EVENT
#define CORE1_TASK93_PERIOD          (0)
#define CORE1_TASK93_ACTIVED         CORE1_TASK_ID4
#define CORE1_TASK93_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK93_PRIORITY        LEVEL_3
#define CORE1_TASK93_MODE            SUPER
#define CORE1_TASK93_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK93_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK94_SWITCH == ON)
#define CORE1_TASK94_TYPE            EVENT
#define CORE1_TASK94_PERIOD          (0)
#define CORE1_TASK94_ACTIVED         CORE1_TASK_ID5
#define CORE1_TASK94_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK94_PRIORITY        LEVEL_4
#define CORE1_TASK94_MODE            SUPER
#define CORE1_TASK94_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK94_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK95_SWITCH == ON)
#define CORE1_TASK95_TYPE            EVENT
#define CORE1_TASK95_PERIOD          (0)
#define CORE1_TASK95_ACTIVED         CORE1_TASK_ID6
#define CORE1_TASK95_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK95_PRIORITY        LEVEL_5
#define CORE1_TASK95_MODE            SUPER
#define CORE1_TASK95_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK95_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK96_SWITCH == ON)
#define CORE1_TASK96_TYPE            EVENT
#define CORE1_TASK96_PERIOD          (0)
#define CORE1_TASK96_ACTIVED         CORE1_TASK_ID7
#define CORE1_TASK96_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK96_PRIORITY        LEVEL_6
#define CORE1_TASK96_MODE            SUPER
#define CORE1_TASK96_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK96_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK97_SWITCH == ON)
#define CORE1_TASK97_TYPE            EVENT
#define CORE1_TASK97_PERIOD          (0)
#define CORE1_TASK97_ACTIVED         CORE1_TASK_ID8
#define CORE1_TASK97_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK97_PRIORITY        LEVEL_7
#define CORE1_TASK97_MODE            SUPER
#define CORE1_TASK97_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK97_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK98_SWITCH == ON)
#define CORE1_TASK98_TYPE            EVENT
#define CORE1_TASK98_PERIOD          (0)
#define CORE1_TASK98_ACTIVED         CORE1_TASK_ID9
#define CORE1_TASK98_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK98_PRIORITY        LEVEL_8
#define CORE1_TASK98_MODE            SUPER
#define CORE1_TASK98_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK98_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK99_SWITCH == ON)
#define CORE1_TASK99_TYPE            EVENT
#define CORE1_TASK99_PERIOD          (0)
#define CORE1_TASK99_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK99_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK99_PRIORITY        LEVEL_9
#define CORE1_TASK99_MODE            SUPER
#define CORE1_TASK99_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK99_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif	
#if (CORE1_TASK100_SWITCH == ON)
#define CORE1_TASK100_TYPE            EVENT
#define CORE1_TASK100_PERIOD          (0)
#define CORE1_TASK100_ACTIVED         NO_ACTIVED_TASK
#define CORE1_TASK100_ACTIVED_COREID  CORE_ID1
#define CORE1_TASK100_PRIORITY        LEVEL_9
#define CORE1_TASK100_MODE            SUPER
#define CORE1_TASK100_STACK_SIZE      PTHREAD_DEFAULT_STACK_SIZE
#define CORE1_TASK100_CALL_DEPTH      CALL_DEPTH_OVERFLOW_AT_64 
#endif
	
#endif /* End of CORE1_TASK_CFG_H_ */	

